import test from 'node:test';import assert from 'node:assert/strict';
import {createBreakingState,recordBreakingEvent,decideBreakingEvent,evaluateBreaking,mergeBreaking} from '../lib/breaking-news.mjs';
const discovered='2026-09-28T01:00:00Z',issued='2026-09-28T02:00:00Z',codes=['005930','000660'];
function fixture(){const sessions=[];for(let t=Date.parse('2026-08-01');t<=Date.parse('2026-10-30');t+=86400000){const d=new Date(t);if(![0,6].includes(d.getUTCDay()))sessions.push(d.toISOString().slice(0,10));}const input={origin:'2026-09-17',end:'2026-10-30',actualAsOf:'2026-09-28',calendar:{sessions},assets:codes.map(code=>({code,prices:[]}))};const baseline={id:'frozen-1',origin:'2026-09-17',createdAt:'2026-09-17T08:00:00Z',informationCutoff:'2026-09-17T08:00:00Z',assets:codes.map(code=>({code,name:code,news:[],originPrice:100,rows:['2026-09-28','2026-09-29','2026-09-30','2026-10-30'].map((date,i)=>({date,p50:100+i,p10:90+i,p90:110+i}))}))};return {input,baseline,options:{now:issued,input,versions:[baseline],active:baseline.id}};}
const payload={economicEventId:'economic-one',phaseId:'decision',title:'합성 사건',summary:'실제 사건을 주장하지 않는 테스트',scope:'company',targetCodes:['005930'],publishedAt:'2026-09-28T00:00:00Z',sourceUrl:'https://example.org/fixture',sourceType:'official',sourceBodyReviewed:true,status:'confirmed',importance:'normal',businessPath:'가설 사업 경로',changeToPremise:'현재 검토 전제 가설'};
const record=(state,p={})=>recordBreakingEvent(state,{...payload,...p},{now:discovered,codes});
function review(event){const samples=['2026-08-04','2026-08-11','2026-08-18','2026-08-25','2026-09-01'].map((date,i)=>{const before=new Date(Date.parse(date)-86400000).toISOString().slice(0,10);return {id:'sample'+i,groupId:'group'+i,code:'005930',phaseId:'decision',eventAt:date+'T00:00:00Z',knownAt:date+'T01:00:00Z',residualLogReturn:Math.log(1.1),horizonSessions:1,adjustmentVerified:true,expectationVerified:true,overlapChecked:true,overlappingEventIds:[],source:{url:'https://example.org/sample/'+i,bodyRead:true,digest:'synthetic'+i,reviewedAt:issued},prices:{beforeClose:100,afterClose:110,beforeAt:before+'T06:30:00Z',afterAt:date+'T06:30:00Z',observedAt:date+'T07:00:00Z',adjustmentVerified:true},expectedLogReturn:0,expectationKnownAt:before+'T05:00:00Z',expectationSourceUrl:'https://example.org/expectation/'+i};});return {code:'005930',phaseId:'decision',samples,evidenceReviewedAt:issued,method:'own_stock_phase_residual',adjustmentVerified:true,expectationVerified:true,horizonSessions:1,baselineReview:{baselineId:'frozen-1',reviewedAt:issued,eventAlreadyIncluded:false,residualOverlap:false},reviewedEventId:event.id,eventSource:{url:event.sourceUrl,bodyRead:true,digest:'synthetic-current',reviewedAt:issued}};}
test('event registration is idempotent, observed time is server assigned and claims stay unverified',()=>{const state=record(createBreakingState());assert.equal(state.events.length,1);assert.equal(record(state),state);assert.equal(state.events[0].knownAt,new Date(discovered).toISOString());assert.equal(state.events[0].evidenceStatus,'USER_RECORDED_NOT_INDEPENDENTLY_VERIFIED');assert.equal(state.premises[0].retrospectivePremiseReconstruction,true);assert.throws(()=>record(state,{publishedAt:'2026-09-29T00:00:00Z'}));assert.throws(()=>record(state,{targetCodes:['123456']}));});
test('unqualified REVISE remains WATCH; KEEP preserves baseline without claiming improvement',()=>{const {options,baseline,input}=fixture(),s=record(createBreakingState()),eventId=s.events[0].id;const held=decideBreakingEvent(s,{eventId,code:'005930',decision:'REVISE'},options);assert.equal(held.decisions[0].decision,'WATCH');assert.equal(held.decisions[0].impact.deltaLog,null);assert.equal(held.forecasts.length,0);const before=JSON.stringify(baseline);const kept=decideBreakingEvent(s,{eventId,code:'005930',decision:'KEEP'},options);assert.equal(kept.forecasts[0].kind,'KEEP');assert.deepEqual(kept.forecasts[0].rows.map(r=>r.p50),baseline.assets[0].rows.map(r=>r.p50));assert.equal(JSON.stringify(baseline),before);assert.equal(kept.forecasts[0].sourceOriginal.asset.code,'005930');input.assets[0].prices=[{date:'2026-09-29',close:104,observedAt:'2026-09-29T07:00:00Z'}];const scored=evaluateBreaking(kept,{input,now:'2026-09-29T08:00:00Z'});assert.equal(scored.evaluations[0].pairedErrorDifference,0);assert.equal(scored.evaluations[0].comparisonMeaning,'identical_baseline_not_improvement');assert.deepEqual(evaluateBreaking(scored,{input,now:'2026-09-29T08:00:00Z'}),scored);});
test('qualified synthetic own-stock impact is applied once to future rows and frozen history is untouched',()=>{const {options,baseline}=fixture(),s=record(createBreakingState()),e=s.events[0],approvedImpact=review(e),request={eventId:e.id,code:'005930',decision:'REVISE',approvedImpact};const before=JSON.stringify(baseline),next=decideBreakingEvent(s,request,options);assert.equal(next.decisions[0].decision,'REVISE',JSON.stringify(next.decisions[0].reasons));const f=next.forecasts[0];assert.equal(f.rows[0].p50,100);assert.equal(f.effectiveFrom,'2026-09-29');assert.ok(Math.abs(f.rows[1].p50/f.rows[1].baselineP50-f.rows[2].p50/f.rows[2].baselineP50)<1e-12);assert.equal(JSON.stringify(baseline),before);assert.equal(decideBreakingEvent(next,request,options),next);assert.equal(next.forecasts.length,1);});
test('a second article in the same economic phase cannot apply another numerical shock',()=>{const {options}=fixture();let s=record(createBreakingState()),e=s.events[0];s=decideBreakingEvent(s,{eventId:e.id,code:'005930',decision:'REVISE',approvedImpact:review(e)},options);s=record(s,{title:'같은 사건의 다른 기사',sourceUrl:'https://example.org/repost'});const e2=s.events.at(-1),next=decideBreakingEvent(s,{eventId:e2.id,code:'005930',decision:'REVISE',approvedImpact:review(e2)},options);assert.equal(next.decisions.at(-1).decision,'BLOCK');assert.equal(next.forecasts.length,1);});
test('unresolved same-day important phase overlap blocks numerical revision',()=>{const {options}=fixture();let s=record(createBreakingState());s=record(s,{economicEventId:'other-event',importance:'important',title:'같은 날 다른 중요 사건'});const e=s.events[0],next=decideBreakingEvent(s,{eventId:e.id,code:'005930',decision:'REVISE',approvedImpact:review(e)},options);assert.equal(next.decisions.at(-1).decision,'BLOCK');assert.equal(next.forecasts.length,0);});
test('correction and retraction append lineage while old decisions and forecasts remain frozen',()=>{const {options}=fixture();let s=record(createBreakingState()),old=s.events[0];s=decideBreakingEvent(s,{eventId:old.id,code:'005930',decision:'KEEP'},options);const frozen=JSON.stringify(s.forecasts);const revised=record(s,{status:'retracted',supersedesId:old.id,title:'철회 공지'});assert.equal(revised.events.length,2);assert.equal(JSON.stringify(revised.forecasts),frozen);assert.equal(revised.events[0].status,'confirmed');assert.equal(revised.events[1].supersedesId,old.id);const merge=mergeBreaking(s,revised);assert.equal(merge.events.length,2);assert.equal(merge.forecasts.length,1);});
test('future observed, conflicted and non-session prices cannot be scored; expiry is unchanged',()=>{const {options,input}=fixture(),s=record(createBreakingState()),kept=decideBreakingEvent(s,{eventId:s.events[0].id,code:'005930',decision:'KEEP'},options);for(const p of [{date:'2026-09-29',close:101,observedAt:'2026-09-30T07:00:00Z'},{date:'2026-09-29',close:101,observedAt:'2026-09-29T07:00:00Z',quality:'conflict'},{date:'2026-09-29',close:101}]){input.assets[0].prices=[p];assert.equal(evaluateBreaking(kept,{input,now:'2026-09-29T08:00:00Z'}).evaluations.length,0);}assert.equal(recordBreakingEvent(kept,payload,{now:'2026-10-31T00:00:00Z',codes}),kept);assert.equal(evaluateBreaking(kept,{input,now:'2026-10-31T00:00:00Z'}),kept);});

test('price-maintenance reference freezes only a quote actually observed before issuance',()=>{
 const {input,options}=fixture();input.assets[0].prices=[{date:'2026-09-18',close:103,observedAt:'2026-09-18T07:00:00Z'},{date:'2026-09-28',close:500,observedAt:'2026-09-28T07:00:00Z'}];
 const s=record(createBreakingState()),kept=decideBreakingEvent(s,{eventId:s.events[0].id,code:'005930',decision:'KEEP'},options);assert.equal(kept.forecasts[0].referencePrice,103);assert.equal(kept.forecasts[0].referenceDate,'2026-09-18');
 input.assets[0].prices.push({date:'2026-09-29',close:104,observedAt:'2026-09-29T07:00:00Z'});const scored=evaluateBreaking(kept,{input,now:'2026-09-29T08:00:00Z'});assert.equal(scored.evaluations[0].referenceErrorWon,1);assert.equal(scored.evaluations[0].referenceAbsolutePercentageError,1/104);assert.equal(scored.evaluations[0].horizonSessionIndex,1);
});
test('ambiguous baseline or actual timestamps and invalid imported issuance never score',()=>{
 const {input,options,baseline}=fixture(),s=record(createBreakingState()),request={eventId:s.events[0].id,code:'005930',decision:'KEEP'};
 const kept=decideBreakingEvent(s,request,options);input.assets[0].prices=[{date:'2026-09-29',close:104,observedAt:'2026-09-29T07:00:00'}];assert.equal(evaluateBreaking(kept,{input,now:'2026-09-29T08:00:00Z'}).evaluations.length,0);
 input.assets[0].prices[0].observedAt='2026-09-29T07:00:00Z';const broken=structuredClone(kept);broken.forecasts[0].issuedAt='garbage';assert.equal(evaluateBreaking(broken,{input,now:'2026-09-29T08:00:00Z'}).evaluations.length,0);
 baseline.informationCutoff='2026-09-17T09:00:00Z';assert.throws(()=>decideBreakingEvent(s,request,options));baseline.informationCutoff='2026-09-17T07:00:00';assert.throws(()=>decideBreakingEvent(s,request,options));
});
test('index membership absence and forked correction lineage prevent numerical revision',()=>{
 const {options}=fixture();let s=record(createBreakingState(),{scope:'index'}),e=s.events[0];assert.equal(decideBreakingEvent(s,{eventId:e.id,code:'005930',decision:'REVISE',approvedImpact:review(e)},options).decisions[0].decision,'BLOCK');
 s=record(createBreakingState());const original=s.events[0];s=record(s,{status:'corrected',supersedesId:original.id,title:'첫 번째 정정'});s=record(s,{status:'corrected',supersedesId:original.id,title:'상충하는 두 번째 정정'});e=s.events.at(-1);assert.equal(decideBreakingEvent(s,{eventId:e.id,code:'005930',decision:'REVISE',approvedImpact:review(e)},options).decisions[0].decision,'BLOCK');
});

test('explicit fresh correction replaces the prior impulse against the same frozen baseline, never compounds it',()=>{
 const {options}=fixture();let s=record(createBreakingState()),event=s.events[0];s=decideBreakingEvent(s,{eventId:event.id,code:'005930',decision:'REVISE',approvedImpact:review(event)},options);const previous=structuredClone(s.forecasts[0]);
 s=record(s,{status:'corrected',supersedesId:event.id,title:'원문 정정 후 새 검토'});const correction=s.events.at(-1),evidence=review(correction);evidence.replacesForecastId=previous.id;for(const sample of evidence.samples){sample.prices.afterClose=90;sample.residualLogReturn=Math.log(.9);}
 const revised=decideBreakingEvent(s,{eventId:correction.id,code:'005930',decision:'REVISE',approvedImpact:evidence},options);assert.equal(revised.decisions.at(-1).decision,'REVISE',JSON.stringify(revised.decisions.at(-1).reasons));assert.equal(revised.forecasts.length,2);assert.deepEqual(revised.forecasts[0],previous);const f=revised.forecasts.at(-1);assert.equal(f.replacesForecastId,previous.id);assert.ok(Math.abs(f.rows[1].p50-101*Math.exp(f.deltaLog))<1e-10);assert.ok(Math.abs(f.rows[1].p50-previous.rows[1].p50*Math.exp(f.deltaLog))>1);
 const missing=structuredClone(evidence);delete missing.replacesForecastId;assert.equal(decideBreakingEvent(s,{eventId:correction.id,code:'005930',decision:'REVISE',approvedImpact:missing},options).decisions.at(-1).decision,'BLOCK');
});

test('a second phase numerical revision cannot silently replace an outstanding independent impulse',()=>{
 const {options}=fixture();let s=record(createBreakingState()),e=s.events[0];s=decideBreakingEvent(s,{eventId:e.id,code:'005930',decision:'REVISE',approvedImpact:review(e)},options);const original=structuredClone(s.forecasts);
 s=record(s,{economicEventId:'unrelated-shock',phaseId:'decision',title:'다른 사건의 수치 영향'});e=s.events.at(-1);const next=decideBreakingEvent(s,{eventId:e.id,code:'005930',decision:'REVISE',approvedImpact:review(e)},options);assert.equal(next.decisions.at(-1).decision,'BLOCK');assert.deepEqual(next.forecasts,original);assert.ok(next.decisions.at(-1).reasons.some(r=>r.includes('공동 반응')));
});
