import test from 'node:test';import assert from 'node:assert/strict';
import {operationWindow,mergeObservedPrices,contentHash,dailyScoreRecord,scorePublicationPair} from '../lib/completion-operation.mjs';
const input={origin:'2026-09-17',end:'2026-10-30',actualAsOf:'2026-09-23',calendar:{sessions:['2026-09-23','2026-09-28','2026-09-29']},assets:[{code:'005930',prices:[{date:'2026-09-23',close:100}]}],events:[]};
const obs={code:'005930',sourceUrl:'https://finance.naver.com/x',rawHash:'a'.repeat(64),observedAt:'2026-09-28T07:01:00Z',rows:[{date:'2026-09-28',open:100,high:101,low:69,close:70,volume:10}]};
test('Korea close gate, holiday retention and period end are explicit',()=>{assert.equal(operationWindow(input,'2026-09-28T06:59:59Z').cutoff,'2026-09-23');assert.equal(operationWindow(input,'2026-09-28T07:00:00Z').eligible,true);assert.equal(operationWindow(input,'2026-09-27T08:00:00Z').eligible,false);assert.equal(operationWindow(input,'2026-10-31T01:00:00Z').ended,true);});
test('real large losses retained with full before-after price journal and CAS',()=>{const r=mergeObservedPrices(input,[obs],{now:obs.observedAt,expectedHash:contentHash(input)});assert.equal(r.input.assets[0].prices.at(-1).close,70);assert.equal(r.actualAsOf,'2026-09-28');assert.equal(r.input.priceRevisions[0].beforeRow,null);assert.equal(input.assets[0].prices.length,1);assert.throws(()=>mergeObservedPrices(input,[obs],{now:obs.observedAt,expectedHash:'stale'}),/VERSION_CONFLICT/);const again=mergeObservedPrices(r.input,[obs],{now:obs.observedAt,expectedHash:contentHash(r.input)});assert.equal(again.changed,false);});
test('intraday, contamination and contradictory dates fail before any mutation',()=>{assert.throws(()=>mergeObservedPrices(input,[obs],{now:'2026-09-28T06:00:00Z',expectedHash:contentHash(input)}),/PROVENANCE/);assert.throws(()=>mergeObservedPrices(input,[{...obs,code:'000000'}],{now:obs.observedAt,expectedHash:contentHash(input)}),/CODE/);assert.throws(()=>mergeObservedPrices(input,[{...obs,rows:[...obs.rows,{...obs.rows[0],close:80}]}],{now:obs.observedAt,expectedHash:contentHash(input)}),/CONFLICT/);});
test('daily report keeps issuance cutoff and treats stock rows as dependent',()=>{const v={id:'issued',createdAt:'2026-09-23T07:00:00Z',assets:[{code:'005930',name:'test',originPrice:100,rows:[{date:'2026-09-28',p10:60,p50:95,p90:120,wave:{daily:{selected:'down',modelProbability:.6,probabilities:{up:.3,flat:.1,down:.6}}}}]}]};const updated=mergeObservedPrices(input,[obs],{now:obs.observedAt,expectedHash:contentHash(input)}).input;const r=dailyScoreRecord(v,updated);assert.equal(r.independentDateCount,1);assert.equal(r.byDate[0].correct,1);assert.equal(r.stockRowsAreIndependent,false);v.createdAt='2026-09-28T08:00:00Z';assert.equal(dailyScoreRecord(v,updated).evaluated,0);});
test('multi-date provider batches merge by stock with per-row evidence',()=>{const next={...obs,rows:[{...obs.rows[0],date:'2026-09-29'}],observedAt:'2026-09-29T07:01:00Z'};const r=mergeObservedPrices(input,[obs,next],{now:next.observedAt,expectedHash:contentHash(input)});assert.equal(r.input.assets[0].prices.length,3);assert.equal(r.actualAsOf,'2026-09-29');assert.equal(r.input.priceRevisions.length,2);});
test('hosted legacy refresh cannot silently publish the retired engine',async()=>{const handler=(await import('../netlify/functions/refresh-background.mjs')).default;assert.equal((await handler(new Request('https://example.com'))).status,401);const before=process.env.ATLAS_JOB_TOKEN;try{process.env.ATLAS_JOB_TOKEN='local-test';const response=await handler(new Request('https://example.com',{headers:{authorization:'Bearer local-test'}}));assert.equal(response.status,503);assert.equal((await response.json()).code,'FACTOR36_HOSTED_RUNNER_REQUIRED');}finally{if(before===undefined)delete process.env.ATLAS_JOB_TOKEN;else process.env.ATLAS_JOB_TOKEN=before;}});

test('daily publication rollover retains the old result and serves the new issuance without borrowed scores',()=>{
 const old={id:'old',createdAt:'2026-09-23T07:00:00Z',assets:[{code:'005930',name:'test',originPrice:100,rows:[{date:'2026-09-28',p10:60,p50:95,p90:120,wave:{daily:{selected:'down',modelProbability:.6,probabilities:{up:.3,flat:.1,down:.6}}}}]}]};
 const current={...old,id:'new',createdAt:'2026-09-28T08:00:00Z'};
 const updated=mergeObservedPrices(input,[obs],{now:obs.observedAt,expectedHash:contentHash(input)}).input;
 const r=scorePublicationPair(old,current,updated,'2026-09-28T08:01:00Z');
 assert.equal(r.retained.forecastId,'old');assert.equal(r.retained.evaluated,1);assert.equal(r.current.forecastId,'new');assert.equal(r.current.evaluated,0);assert.equal(r.current.byDate.length,0);
 const same=scorePublicationPair(old,old,updated,'2026-09-28T08:01:00Z');assert.deepEqual(same.current,same.retained);
});
