import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {validateNewspaperEvidence} from '../lib/completion-newspaper.mjs';
const bytes=Buffer.from(JSON.stringify({url:'https://news.example.com/123',fact:'10억원'})),hash=createHash('sha256').update(bytes).digest('hex');
const source=extra=>({id:'article-1',url:'https://news.example.com/123',title:'기간별 수급 공시를 확인한 보도',publisher:'Example',publicationDate:'2026-09-25',publishedAt:null,observedAt:'2026-09-28T06:00:00Z',sourceBodyRead:true,evidenceType:'newspaper',factorIds:['F19'],targetCodes:['000001'],rawPath:'reports/completion/raw/article.json',rawHash:hash,hashKind:'verified_observation_excerpt',observations:[{metric:'개인 순매수',value:1e9,unit:'KRW',startDate:'2026-09-01',endDate:'2026-09-24',date:'2026-09-24',aggregation:'period_total'}],...extra});
const validate=sources=>validateNewspaperEvidence([{file:'fixture',sources}],{codes:['000001','000002'],asOf:'2026-09-28T07:00:00Z',readSnapshot:async()=>bytes});
test('actual snapshot bytes must match hash and collector must attest reading article body',async()=>{const a=await validate([source()]);assert.equal(a.summary.acceptedUniqueSources,1);assert.equal(a.summary.verifiedObservationSnapshots,1);assert.equal(a.summary.originalBodiesHashVerified,0);const b=await validate([source({rawHash:'a'.repeat(64)}),source({sourceBodyRead:false})]);assert.equal(b.summary.acceptedUniqueSources,0);assert.deepEqual(b.validation.rejected.map(x=>x.reason),['SNAPSHOT_HASH_MISMATCH','SOURCE_BODY_NOT_READ']);});
test('date-only publication remains time-unknown and current observation is never backdated',async()=>{const a=await validate([source()]);assert.equal(a.sources[0].publishedAt,null);assert.equal(a.sources[0].publicationTimeVerified,false);assert.equal(a.sources[0].knownToAtlasAt,'2026-09-28T06:00:00Z');assert.equal(a.observations[0].pointInTimeVerified,false);assert.equal(a.observations[0].strictTrainingEligible,false);assert.equal(a.observations[0].numericImpactAllowed,false);});
test('verified period sum stays one observation and is not expanded into daily training samples',async()=>{const a=await validate([source()]);assert.equal(a.observations.length,1);assert.equal(a.observations[0].aggregation,'period_total');assert.equal(a.summary.numericUsableObservations,1);assert.equal(a.summary.strictTrainingEligibleStocks,0);});
test('missing numeric values, units and periods remain null and unavailable rather than zero',async()=>{const a=await validate([source({observations:[{metric:'관심 증가',value:null,unit:null}]})]);const o=a.observations[0];assert.equal(o.value,null);assert.equal(o.unit,null);assert.equal(o.rawNumericObservationUsable,false);assert.deepEqual(o.missing,['numeric_value','unit','period']);});
test('HTTPS, snapshot paths and explicit universe targets fail closed',async()=>{for(const patch of[{url:'http://news.example.com/a'},{url:'https://172.20.0.1/a'},{rawPath:'../outside.json'},{targetCodes:['999999']},{factorIds:['F37']}]){const a=await validate([source(patch)]);assert.equal(a.summary.acceptedUniqueSources,0);assert.equal(a.validation.rejected.length,1);}});
test('same URL and identical observation are deduplicated across agent files without counting extra samples',async()=>{const a=await validate([source(),source({id:'copy',url:'https://news.example.com/123?utm_source=copy'})]);assert.equal(a.sources.length,1);assert.equal(a.observations.length,1);assert.equal(a.summary.duplicateSources,1);assert.equal(a.summary.duplicateObservations,1);assert.equal(a.summary.numericSourceStocks,1);});
test('conflicting same-target same-period values are retained but both withheld from usable numeric count',async()=>{const one=source(),two=source({id:'article-2',url:'https://news.example.com/456',observations:[{...one.observations[0],value:2e9}]});const a=await validate([one,two]);assert.equal(a.observations.length,2);assert.equal(a.summary.conflictingObservationGroups,1);assert.equal(a.summary.numericUsableObservations,0);assert.ok(a.observations.every(o=>o.value!==null&&!o.rawNumericObservationUsable));});
test('an observation cannot silently introduce an unrelated company or factor',async()=>{for(const observation of[{targetCodes:['000002']},{factorIds:['F18']}]){const a=await validate([source({observations:[{...source().observations[0],...observation}]})]);assert.equal(a.summary.acceptedUniqueSources,0);assert.equal(a.validation.rejected.length,1);}});
test('future observations cannot affect a past evidence view even if their other fields are malformed',async()=>{const a=await validate([source(),source({observedAt:'2026-10-01T00:00:00Z',url:'not-a-url'})]);assert.equal(a.sources.length,1);assert.equal(a.validation.rejected.length,0);assert.deepEqual(a,await validate([source()]));});

test('collector-detected source totals conflict is preserved and cannot re-enter usable numbers',async()=>{const a=await validate([source({observations:[{...source().observations[0],quality:'source_internal_conflict'}]})]);assert.equal(a.summary.numericUsableObservations,0);assert.equal(a.summary.sourceQualityBlockedObservations,1);assert.equal(a.observations[0].value,1e9);assert.equal(a.sources[0].observations[0].rawNumericObservationUsable,false);});

test('duplicate same-value observations retain any conflict flag regardless of source and input order',async()=>{const clean=source(),bad=source({id:'second',url:'https://news.example.com/456',observations:[{...source().observations[0],quality:'source_internal_conflict'}]});for(const rows of [[clean,bad],[bad,clean],[clean,{...bad,url:clean.url}]]){const a=await validate(rows);assert.equal(a.observations.length,1);assert.equal(a.summary.numericUsableObservations,0);assert.equal(a.summary.sourceQualityBlockedObservations,1);assert.ok(a.sources.every(s=>s.observations.every(o=>!o.rawNumericObservationUsable&&o.missing.includes('source_quality_conflict'))));}});
