import test from 'node:test';import assert from 'node:assert/strict';
import {MARKET_SERIES,parseFredBody,mergeCapturedSeries,parseFedPolicy,fredURL} from '../lib/completion-market.mjs';
const at='2026-09-28T06:00:00Z',spec=MARKET_SERIES.find(s=>s.id==='DFII10');
test('official rows preserve null, negative real yield and observation date',()=>{const p=parseFredBody('https://fred.stlouisfed.org/data/DFII10\n#2026-09-21|-1.1 #2026-09-22| . #2026-09-23| 0.0','DFII10',{observedAt:at});assert.deepEqual(p.rows.map(x=>x.value),[-1.1,null,0]);assert.equal(p.pointInTimeVerified,false);assert.equal(p.publishedAt,null);assert.equal(p.rawHashRepresentation,'web_text_extract');});
test('series mix-up invalid dates and future observations fail closed',()=>{assert.throws(()=>parseFredBody('https://fred.stlouisfed.org/data/DGS10\n2026-09-21|1','DFII10',{observedAt:at}),/MISMATCH/);const p=parseFredBody('observation_date,DFII10\n2026-02-30,1\n2026-09-29,2\n2026-09-22,-5','DFII10',{observedAt:at,representation:'http_csv'});assert.equal(p.rows.length,1);assert.equal(p.rows[0].value,-5);assert.equal(p.rejected.length,1);});
test('same-day source disagreement is quarantined rather than last-write-wins',()=>{const p=v=>parseFredBody(`https://fred.stlouisfed.org/data/DFII10\n2026-09-21|${v}`,'DFII10',{observedAt:at});const m=mergeCapturedSeries([p(1),p(2)],spec);assert.equal(m.rows[0].value,null);assert.equal(m.conflicts.length,1);assert.equal(m.importReady,false);});
test('partial extraction gaps are never interpolated or advertised complete',()=>{const p=parseFredBody('https://fred.stlouisfed.org/data/DFII10\n2026-09-21|1 2026-09-23|2','DFII10',{observedAt:at});const m=mergeCapturedSeries([p],spec);assert.deepEqual(m.unobservedWeekdays,['2026-09-22']);assert.equal(m.historyComplete,false);assert.equal(m.approvedForModel,false);});
test('Korean treasury factor cannot silently consume US treasury or bank call rate',()=>{assert.equal(MARKET_SERIES.find(x=>x.id==='DGS10').factorId,null);assert.equal(MARKET_SERIES.find(x=>x.id==='IRSTCI01KRM156N').factorId,null);assert.equal(MARKET_SERIES.find(x=>x.id==='IRLTLT01KRM156N').componentOnly,true);assert.throws(()=>fredURL('localhost'),/UNKNOWN/);});
test('Fed target effective date is not a surprise or historical publication timestamp',()=>{const p=parseFedPolicy('https://www.federalreserve.gov/monetarypolicy/openmarket.htm\nL25: #### 2026\nL29: September 17 | 25 | 0 | 3.75-4.00',{observedAt:at});assert.equal(p.rows[0].date,'2026-09-17');assert.equal(p.rows[0].upper,4);assert.equal(p.rows[0].surprise,null);assert.equal(p.rows[0].publishedAt,null);assert.equal(p.importReady,false);});
