import test from 'node:test';
import assert from 'node:assert/strict';
import {completedCloseDate,parseKrxStockDaily,naverPriceObservation,observationRecords,currentFomoAudit,collectCompletionFomo,parseAlphaExtracted} from '../lib/completion-fomo.mjs';
const sessions=[];for(let t=Date.parse('2025-01-01');t<=Date.parse('2026-10-30');t+=86400000){const d=new Date(t);if(d.getUTCDay()>0&&d.getUTCDay()<6)sessions.push(d.toISOString().slice(0,10));}
const input={end:'2026-10-30',actualAsOf:'2026-09-23',informationAsOf:'2026-09-28T05:00:00Z',calendar:{sessions:sessions.filter(d=>!['2026-09-24','2026-09-25'].includes(d))},assets:[{code:'005930',name:'fixture',prices:sessions.filter(d=>d<='2026-09-23').map((date,i)=>({date,close:100+i%20,quality:'single_source'}))}],sourceCorrections:[]};
const observedAt='2026-09-28T06:00:00Z',sourceUrl='https://openapi.krx.co.kr/svc/apis/sto/stk_bydd_trd?basDd=20260923';
const row={BAS_DD:'20260923',ISU_CD:'005930',TDD_OPNPRC:'100',TDD_HGPRC:'101',TDD_LWPRC:'20',TDD_CLSPRC:'30',ACC_TRDVOL:'1,000',ACC_TRDVAL:'30,000'};
const parse=rows=>parseKrxStockDaily(JSON.stringify({OutBlock_1:rows}),{date:'2026-09-23',input,sourceUrl,observedAt});
test('Korean 16:00 boundary, holidays and fixed end are respected',()=>{assert.equal(completedCloseDate(input,new Date('2026-09-28T06:59:59Z')),'2026-09-23');assert.equal(completedCloseDate(input,new Date('2026-09-28T07:00:00Z')),'2026-09-28');assert.equal(completedCloseDate(input,new Date('2026-11-03T07:00:00Z')),'2026-10-30');});
test('KRX extreme loss valid OHLC preserved with provenance, no cutoff filter',()=>{const [o]=parse([row]);assert.equal(o.rows[0].close,30);assert.equal(o.rows[0].volume,1000);assert.equal(o.availableAt,observedAt);assert.equal(o.publicationBasis,'observed_availability_only');assert.equal(o.adjustmentsVerified,false);assert.match(o.rawHash,/^[a-f0-9]{64}$/);});
test('KRX wrong date, duplicate, unit or OHLC rejects atomically',()=>{for(const rows of [[{...row,BAS_DD:'20260922'}],[row,row],[{...row,ACC_TRDVAL:'3만원'}],[{...row,TDD_CLSPRC:'102'}],[{...row,ISU_CD:'Samsung'}]])assert.throws(()=>parse(rows));});
test('KRX code can be verified standard ISIN but unrelated companies excluded',()=>{assert.equal(parse([{...row,ISU_CD:'KR7005930003'}])[0].code,'005930');assert.equal(parse([{...row,ISU_CD:'000001'}]).length,0);});
test('KRX missing fields do not become zero and private source denied',()=>{const x={...row};delete x.ACC_TRDVOL;assert.throws(()=>parse([x]));assert.throws(()=>parseKrxStockDaily(JSON.stringify({OutBlock_1:[row]}),{date:'2026-09-23',input,sourceUrl:'https://localhost/price',observedAt}));});
test('NAVER symbol and completed session validated, no artificial turnover',()=>{const raw='<chartdata symbol="005930"><item data="20260923|100|110|90|100|500"/><item data="20260928|100|110|90|101|500"/></chartdata>';const o=naverPriceObservation(raw,'005930',{input,sourceUrl:'https://fchart.stock.naver.com/sise.nhn?symbol=005930',observedAt});assert.equal(o.rows.length,1);assert.equal(observationRecords([o]).some(r=>r.field==='turnover'),false);assert.throws(()=>naverPriceObservation(raw,'000001',{input,sourceUrl:'https://fchart.stock.naver.com/sise.nhn',observedAt}));});
test('Missing attention and flow remain null; price heat never masquerades as FOMO',()=>{const before=JSON.stringify(input),audit=currentFomoAudit(input,{now:new Date(observedAt)});assert.equal(audit.fullFomoCount,0);assert.equal(audit.stocks52[0].fullFomoScore,null);assert.ok(audit.stocks52[0].priceHeat!==null);assert.equal(audit.stocks52[0].subindices.searchBurst.value,null);assert.equal(audit.stocks52[0].forecastIntegration.enabled,false);assert.equal(JSON.stringify(input),before);});
test('New OHLC source conflicting with stored close is withheld and logged',()=>{const audit=currentFomoAudit(input,{observations:parse([row]),now:new Date(observedAt)});assert.equal(audit.acceptedRecords.length,0);assert.ok(audit.conflicts.length>=4);});
test('First observed history cannot claim an earlier publication',()=>{const [o]=parse([row]);for(const r of observationRecords([o])){assert.equal(r.publishedAt,null);assert.equal(r.availableAt,observedAt);assert.equal(r.adjustmentsVerified,false);}});
test('Collector uses one shared OHLCV request per target and does not invent missing FOMO',async()=>{
 const testInput={...structuredClone(input),assets:Array.from({length:52},(_,i)=>({...structuredClone(input.assets[0]),code:String(i+1).padStart(6,'0')}))};let requests=0,snapshots=0;
 const result=await collectCompletionFomo(testInput,{now:new Date(observedAt),onSnapshot:async()=>{snapshots++;},sourceOptions:{now:()=>new Date(observedAt),lookup:async()=>[{address:'8.8.8.8',family:4}],fetcher:async url=>{requests++;const code=new URL(url).searchParams.get('symbol'),close=testInput.assets[0].prices.at(-1).close;return new Response(`<chartdata symbol="${code}"><item data="20260923|${close}|${close}|${close}|${close}|500"/></chartdata>`,{status:200,headers:{'content-type':'text/xml'}});}}});
 assert.equal(requests,52);assert.equal(snapshots,52);assert.equal(result.priceSuccessCount,52);assert.equal(result.priceObservations.length,52);assert.equal(result.fullFomoCount,0);assert.equal(result.exitCode,2);assert.ok(result.stocks52.every(s=>s.searchStatus==='not_configured'));
});
const alpha='# fixture (005930) 주가 및 종목 정보\n현재가 | 999\n## 일별 주가\n날짜 | 시가 | 고가 | 저가 | 종가 | 거래량 | 거래대금\n2026.09.23 | 100 | 110 | 90 | 100 | 500 | 50,123\n2026.09.28 | 100 | 110 | 90 | 101 | 700 | 70,123\n## 회사 정보';
const alphaOpts={input,sourceUrl:'https://alphasquare.co.kr/home/stock-summary?code=005930',observedAt};
test('Actual daily provider table excludes live quote and nonfinal current day',()=>{const p=parseAlphaExtracted(alpha,'005930',alphaOpts);assert.equal(p.rows.length,1);assert.equal(p.rows[0].close,100);assert.equal(p.rows[0].turnover,50123);assert.equal(p.rawHashType,'web_extracted_text');assert.equal(p.rawOriginHtmlAvailable,false);});
test('Provider requested code, body identity, numeric units and duplicates enforced',()=>{assert.throws(()=>parseAlphaExtracted(alpha.replace('(005930)','(000001)'),'005930',alphaOpts));assert.throws(()=>parseAlphaExtracted(alpha.replace('500 | 50,123','500K | 50,123'),'005930',alphaOpts));assert.throws(()=>parseAlphaExtracted(alpha.replace('2026.09.28','2026.09.23'),'005930',alphaOpts));assert.throws(()=>parseAlphaExtracted(alpha,'000001',alphaOpts));});
