import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{gunzipSync}from'node:zlib';import{comparisonSeries,rankAt,rankMovement,raceDates,raceKeyframes,closeRace}from'../lib/equal-start.mjs';import{validateWaveBundle}from'../lib/wave-bundle.mjs';
const wave=JSON.parse(gunzipSync(fs.readFileSync('public/data/news-wave.json.gz'))),input=wave.displayContext.input,version=wave.candidate,series=comparisonSeries({input,version}),dates=raceDates(input);
test('52 equal origins and exact latest-model endpoints',()=>{assert.equal(series.length,52);for(const a of series){assert.equal(a.rows[0].value,10000);const p=version.assets.find(x=>x.code===a.code).rows.at(-1).p50;assert.equal(a.rows.at(-1).value,10000*p/a.base);}});
test('playback dates are trading sessions including holiday gap',()=>{assert.equal(dates[0],'2026-09-17');assert.equal(dates.at(-1),'2026-10-30');assert.equal(dates[dates.indexOf('2026-09-23')+1],'2026-09-28');assert.ok(dates.every(d=>input.calendar.sessions.includes(d)));});
test('own/opponent Shapley movement reconciles every complete daily rank',()=>{for(const date of dates.slice(1)){const previous=dates[dates.indexOf(date)-1];for(const a of series){const m=rankMovement(series,date,previous,a.code);assert.equal(m.unexplainedRankChange,0);assert.equal(m.rankChange,m.ownComponent+m.otherComponent);}}});
test('all same-start stocks share rank 1 and no invented unique winner',()=>{const r=rankAt(series,dates[0]);assert.ok(r.every(x=>x.rank===1));const frame=raceKeyframes(series,dates,series[0].code).find(f=>f.index===1);assert.ok(!frame?.reasons.includes('선두 교체'));});
test('close-race rule is a value gap, never probability',()=>{const r=closeRace([{code:'A',value:10000,name:'A'},{code:'B',value:9999,name:'B'}],'B');assert.equal(r.above.gap,1);assert.equal(r.near.code,'A');assert.match(r.meaning,/not_statistical/);});
test('atomic bundle does not require saved device active ID',()=>{const b=structuredClone(wave);b.sourceForecastId='unrelated-old-device-version';assert.equal(validateWaveBundle(b).candidate.id,version.id);});
test('mixed data/forecast, missing context and wrong company are rejected',()=>{let b=structuredClone(wave);b.displayContext.input.actualAsOf='2026-09-22';assert.throws(()=>validateWaveBundle(b));b=structuredClone(wave);delete b.displayContext;assert.throws(()=>validateWaveBundle(b));b=structuredClone(wave);b.displayContext.input.assets[0].code='999999';assert.throws(()=>validateWaveBundle(b));});
