import fs from'node:fs/promises';import{createHash}from'node:crypto';
import{pricePanel,examplesFor,fitFactorModel,FEATURE_FACTORS,mean}from'../lib/factor36.mjs';
import{simulateJointFactor36}from'../lib/factor36-simulation.mjs';
import{rollingBacktestPlan,truncateObservedPanel,rankingHits}from'../lib/rolling-backtest.mjs';
import{macroDesign,macroScenario}from'../lib/macro-candidate.mjs';
const dir='reports/prediction-candidate',hash=x=>createHash('sha256').update(x).digest('hex'),bytes=await fs.readFile('public/data/atlas.json'),input=JSON.parse(bytes).input;
const series=await Promise.all(['DFII10','DEXKOUS'].map(id=>fs.readFile(`reports/completion/market-${id}.json`,'utf8').then(JSON.parse)));
const protocol={id:'macro-candidate-1',createdAt:new Date().toISOString(),inputSHA256:hash(bytes),series:series.map(s=>({id:s.id,factorId:s.factorId,sha256:hash(JSON.stringify(s))})),originDays:120,blocks:6,paths:512,seed:20260917,lagDays:7,futureMacro:'constant last observed lagged level',A:'existing price-factor model',B:'same architecture plus actual DFII10 and DEXKOUS levels; own coefficients selected only on inner training dates',adoption:'disabled until point-in-time source and corporate-action quality verified, even if retrospective metrics improve',vintage:'current retrieval retrospective; 7 day lag is an assumption, not proof of release timing',independentStockTrials:false};
await fs.mkdir(dir,{recursive:true});await fs.writeFile(dir+'/protocol.json',JSON.stringify(protocol,null,2),{flag:'wx'});
const{panel,origins}=rollingBacktestPlan(input);const base=input.assets.map((a,i)=>examplesFor(panel,i)),expanded=base.map(x=>macroDesign(x,series)),prices=input.assets.map(a=>new Map(a.prices.map(r=>[r.date,r.close]))),days=[],ledger=['origin,code,target,actual,A,B'];let A,B;
for(let k=0;k<origins.length;k++){const o=origins[k];if(k%20===0){A=base.map(x=>fitFactorModel(x.filter(r=>r.date<=o.date)));B=expanded.map(x=>fitFactorModel(x.filter(r=>r.date<=o.date),{featureFactors:[...FEATURE_FACTORS,...series.map(s=>s.factorId)]}));}
 const observed=truncateObservedPanel(panel,o.panelIndex),external=base.map(x=>macroScenario(x,series,o.date));
 const a=simulateJointFactor36(A,observed,input.assets,o.targets,{paths:512,seed:20260917}),b=simulateJointFactor36(B,observed,input.assets,o.targets,{paths:512,seed:20260917,external});
 const ea=[],eb=[],pa={},pb={},actual={};for(let i=0;i<input.assets.length;i++){const code=input.assets[i].code,anchor=prices[i].get(o.date);for(let h=0;h<20;h++){const target=o.targets[h],v=prices[i].get(target),av=a.rows[i][h].p50,bv=b.rows[i][h].p50;if(![v,av,bv].every(Number.isFinite)||v<=0)throw Error('INVALID_PAIR');ea.push(Math.abs(av-v)/v*100);eb.push(Math.abs(bv-v)/v*100);ledger.push([o.date,code,target,v,av,bv].join(','));if(h===19){pa[code]=av/anchor-1;pb[code]=bv/anchor-1;actual[code]=v/anchor-1;}}}
 days.push({date:o.date,errorA:mean(ea),errorB:mean(eb),rankA:rankingHits(pa,actual).hits,rankB:rankingHits(pb,actual).hits});if(k%10===9)console.log(JSON.stringify({completed:k+1,total:120}));}
const result={protocol,at:new Date().toISOString(),stocks:52,origins:days.length,rows:ledger.length-1,A:{meanErrorPct:mean(days.map(d=>d.errorA)),rankHits:days.reduce((s,d)=>s+d.rankA,0)},B:{meanErrorPct:mean(days.map(d=>d.errorB)),rankHits:days.reduce((s,d)=>s+d.rankB,0)},days,adopted:false,trustProbability:null};
result.numericalGate=result.B.meanErrorPct<result.A.meanErrorPct&&result.B.rankHits>=result.A.rankHits;
await fs.writeFile(dir+'/result.json',JSON.stringify(result,null,2));await fs.writeFile(dir+'/paired.csv',ledger.join('\n'));
const models=expanded.map(x=>fitFactorModel(x,{featureFactors:[...FEATURE_FACTORS,...series.map(s=>s.factorId)]})),dates=input.calendar.sessions.filter(d=>d>input.actualAsOf).slice(0,20),simulation=simulateJointFactor36(models,panel,input.assets,dates,{paths:20000,seed:20260917,external:base.map(x=>macroScenario(x,series,input.actualAsOf))});
await fs.writeFile(dir+'/forecast-research.json',JSON.stringify({schema:'atlas-quarantined-macro-candidate-1',issuedAt:new Date().toISOString(),origin:input.actualAsOf,adopted:false,trustProbability:null,limitations:protocol,assets:input.assets.map((a,i)=>({code:a.code,name:a.name,anchor:prices[i].get(input.actualAsOf),selection:models[i].factorSelection,rows:simulation.rows[i]}))}));
if(hash(await fs.readFile('public/data/atlas.json'))!==protocol.inputSHA256)throw Error('OPERATING_INPUT_CHANGED');console.log(JSON.stringify({A:result.A,B:result.B,numericalGate:result.numericalGate,adopted:false}));
