import fs from'node:fs/promises';import{contentHash,mergeObservedPrices}from'../lib/completion-operation.mjs';
const arg=n=>process.argv[process.argv.indexOf(n)+1],file='public/data/atlas.json',raw=await fs.readFile(file,'utf8'),bundle=JSON.parse(raw),proposal=JSON.parse(await fs.readFile(arg('--input'),'utf8')),at=new Date().toISOString();
if(!process.argv.includes('--expected-hash')||arg('--expected-hash')!==contentHash(raw))throw Error('BUNDLE_VERSION_CONFLICT');
const observations=proposal.priceObservations??[];
// This import only enriches matching, completed-session closes; a discrepancy needs separate correction review.
for(const o of observations)for(const r of o.rows){const retained=bundle.input.assets.find(a=>a.code===o.code)?.prices.find(p=>p.date===r.date);if(retained&&retained.close!==r.close)throw Error('RETAINED_CLOSE_CONFLICT '+o.code+' '+r.date);}
const merged=mergeObservedPrices(bundle.input,observations,{now:at,expectedHash:contentHash(bundle.input)});await fs.mkdir('reports/completion/price-imports',{recursive:true});
const beforeHash=contentHash(bundle.input);await fs.writeFile('reports/completion/price-imports/'+beforeHash+'.json',JSON.stringify(bundle.input),{flag:'wx'}).catch(e=>{if(e.code!=='EEXIST')throw e;});
if(merged.changed){if(await fs.readFile(file,'utf8')!==raw)throw Error('CONCURRENT_INPUT_EDIT');await fs.writeFile(file+'.next',JSON.stringify({...bundle,input:merged.input}));await fs.rename(file+'.next',file);await fs.writeFile('public/data/input.json',JSON.stringify(merged.input));}
const report={at,beforeInputHash:beforeHash,afterInputHash:contentHash(merged.input),changed:merged.changed,observedStocks:observations.length,freshStocks:merged.freshCodes.length,actualAsOf:merged.actualAsOf,priceRows:observations.reduce((n,o)=>n+o.rows.length,0),originalUnchanged:contentHash(bundle.original)===contentHash(JSON.parse(await fs.readFile(file,'utf8')).original),provider:'ALPHASQUARE',scope:'matching_historical_closed_prices_only_not_current_intraday',fullyAdjustedOrVintageVerified:false};await fs.writeFile('reports/completion/price-imports/'+at.replace(/[:.]/g,'-')+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
