import fs from 'node:fs/promises';import {createHash} from 'node:crypto';
import {fitJointFomo,simulateFomoPath} from '../lib/fomo-path-v2.mjs';
import {calculateFomoV2} from '../lib/fomo-v2.mjs';import {mergeFomoRecords} from '../lib/fomo-records.mjs';import {collectFomoV2} from '../lib/fomo-collector-v2.mjs';import {walkForward} from '../lib/fomo-model-v2.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex'),raw=await fs.readFile('public/data/atlas.json'),bundle=JSON.parse(raw),at=new Date().toISOString(),dir='reports/fomo-v2/runs/'+at.replace(/[:.]/g,'-');await fs.mkdir(dir,{recursive:true});let input=bundle.input,collection=null;
const arg=name=>{const i=process.argv.indexOf(name);return i<0?null:process.argv[i+1];};
if(process.argv.includes('--collect')){collection=await collectFomoV2(input,{naverId:process.env.NAVER_CLIENT_ID,naverSecret:process.env.NAVER_CLIENT_SECRET,onSnapshot:async s=>{const p='reports/fomo-v2/snapshots/'+s.metadata.contentSha256;await fs.mkdir('reports/fomo-v2/snapshots',{recursive:true});try{await fs.writeFile(p+'.bin',s.body,{flag:'wx'});}catch(e){if(e.code!=='EEXIST')throw e;}await fs.writeFile(p+'.json',JSON.stringify(s.metadata));}});await fs.writeFile(dir+'/collection.json',JSON.stringify(collection,null,2));if(collection.payload.records.length)input=mergeFomoRecords(input,collection.payload,{now:new Date().toISOString()});}
const importPath=arg('--import');if(importPath)input=mergeFomoRecords(input,JSON.parse(await fs.readFile(importPath)),{now:new Date().toISOString()});
const trainingPath=arg('--training'),training=trainingPath?JSON.parse(await fs.readFile(trainingPath)):[];if(!Array.isArray(training))throw Error('Training must be an array');if(trainingPath)await fs.writeFile(dir+'/training.json',JSON.stringify(training));
const date=new Date(Date.now()+9*3600000).toISOString().slice(0,10),observations=input.assets.map(a=>calculateFomoV2({input,code:a.code,date})),validation=input.assets.map(a=>walkForward(training,{code:a.code}));
const dailyPathCandidates=input.assets.map(a=>{const o=observations.find(o=>o.code===a.code);const model=fitJointFomo(training,{code:a.code,cutoff:'2026-09-16'});if(model.status!=='shadow_research'||!o.vector)return{code:a.code,status:'insufficient_evidence',priceImpactEnabled:false};const asset=bundle.candidate.assets.find(x=>x.code===a.code),base=asset.numericSummary?.rows?.filter(r=>r.date>input.actualAsOf).map(r=>({date:r.date,mean:r.increment?.logReturnMean}));if(!base?.length||base.some(r=>!Number.isFinite(r.mean)))return{code:a.code,status:'baseline_increments_missing',priceImpactEnabled:false};const price=a.prices.find(p=>p.date===input.actualAsOf)?.close;return{frozenArtifact:model,trainingSHA256:hash(JSON.stringify(training)),...simulateFomoPath(model,{state:o.vector.slice(0,4),originPrice:price,baseIncrements:base}),sourceForecastId:bundle.candidate.id,informationAsOf:o.informationAsOf};});
let priorCollection=null;if(!collection){try{priorCollection=JSON.parse(await fs.readFile('reports/fomo-v2/latest.json')).collection;}catch(e){if(e.code!=='ENOENT')throw e;}}
const report={schema:2,dailyPathCandidates,collectionReused:!collection&&!!priorCollection,at,sourceSHA256:hash(raw),candidateInputSHA256:hash(JSON.stringify(input)),actualAsOf:input.actualAsOf,observations,validation,complete:observations.filter(o=>o.score!==null).length,assets:observations.length,collection:collection?{priceSuccess:collection.price.successfulSources,priceFailed:collection.price.failedSources,priceDeferred:collection.price.deferredSources,searchObserved:collection.search.filter(r=>r.status==='observed').length,searchNotConfigured:collection.search.filter(r=>r.status==='not_configured').length,flowAvailable:0}:priorCollection,operatingForecastChanged:false,trustProbability:null};
await fs.writeFile(dir+'/report.json',JSON.stringify(report,null,2));await fs.writeFile('reports/fomo-v2/latest.json',JSON.stringify(report,null,2));await fs.writeFile('public/data/fomo-research.json',JSON.stringify(report));
// Candidate carries original input untouched except separately journaled feature records.
if(input!==bundle.input)await fs.writeFile(dir+'/input-candidate.json',JSON.stringify(input));
if(hash(await fs.readFile('public/data/atlas.json'))!==hash(raw))throw Error('Operating bundle changed');
console.log(JSON.stringify({assets:report.assets,complete:report.complete,actualAsOf:report.actualAsOf,collection:report.collection,validationReady:validation.filter(v=>v.coefficients).length,forecastChanged:false,report:dir+'/report.json'}));
process.exitCode=report.complete===52&&validation.every(v=>v.coefficients)?0:2;
