import fs from 'node:fs/promises';import{createHash}from'node:crypto';import{gzipSync,gunzipSync}from'node:zlib';
import{FACTOR36_POLICY,pricePanel,examplesFor,fitFactorModel,validateFactorRecords,mean}from'../lib/factor36.mjs';
import{externalDesign,mergeFactorRecords}from'../lib/factor36-input.mjs';import{simulateJointFactor36}from'../lib/factor36-simulation.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex'),raw=await fs.readFile('public/data/atlas.json'),b=JSON.parse(raw),input=b.input,at=new Date().toISOString(),sourceSHA256=sha(raw),dir='reports/factor36';await fs.mkdir(dir+'/versions',{recursive:true});
const arg=name=>{const i=process.argv.indexOf(name);return i<0?null:process.argv[i+1];};const paths=arg('--paths')?Number(arg('--paths')):FACTOR36_POLICY.paths;
let recordRaw;try{recordRaw=await fs.readFile('public/data/factor36-records.json','utf8');}catch(e){if(e.code!=='ENOENT')throw e;recordRaw=JSON.stringify({schema:'atlas-factor36-records-1',records:[],revisions:[]});}
let payload=JSON.parse(recordRaw);const importFile=arg('--import');if(importFile){const next=validateFactorRecords(JSON.parse(await fs.readFile(importFile)),{codes:input.assets.map(a=>a.code),cutoff:at});payload=mergeFactorRecords(payload,next,{expectedHash:arg('--expected-hash'),actualHash:sha(recordRaw),at});await fs.writeFile(dir+'/input-before-'+Date.now()+'.json',recordRaw);recordRaw=JSON.stringify(payload);await fs.writeFile('public/data/factor36-records.json',recordRaw);}
const records=validateFactorRecords(payload,{codes:input.assets.map(a=>a.code),cutoff:at}),registry=JSON.parse(await fs.readFile('public/data/factor36-registry.json'));
const codeFiles=['lib/factor36.mjs','lib/factor36-input.mjs','lib/factor36-simulation.mjs','scripts/research_factor36.mjs'];const implementationSHA256=sha((await Promise.all(codeFiles.map(f=>fs.readFile(f)))).map(x=>x.toString()).join('\n')),semanticInput={origin:input.origin,end:input.end,actualAsOf:input.actualAsOf,calendar:input.calendar.sessions,assets:input.assets.map(a=>({code:a.code,sector:a.sector,prices:a.prices.map(p=>({date:p.date,close:p.close,quality:p.quality??null}))})),news:b.candidate.assets.map(a=>({code:a.code,news:a.news.map(n=>({id:n.id,name:n.name,date:n.date,scope:n.scope,status:n.status,publishedAt:n.publishedAt,sources:n.sources?.map(s=>({url:s.url,name:s.name}))}))}))},semanticSHA256=sha(JSON.stringify(semanticInput)),id=input.actualAsOf+'-factor36-'+sha(semanticSHA256+implementationSHA256+JSON.stringify(records)+paths).slice(0,12),file=dir+'/versions/'+id+'.json';
let out;try{out=JSON.parse(await fs.readFile(file));console.log('reused '+id);}catch(e){if(e.code!=='ENOENT')throw e;}
if(!out){
 const panel=pricePanel(input),models=[],external=[];for(let i=0;i<input.assets.length;i++){const a=input.assets[i],design=externalDesign(records,a,panel,examplesFor(panel,i),at),model=fitFactorModel(design.rows,{featureFactors:design.featureFactors});if(model.status!=='research_estimate')throw Error('MODEL_HISTORY '+a.code+' '+model.reason);external.push(design);models.push(model);console.log(JSON.stringify({code:a.code,model:model.selected.id,history:model.trainCount,holdoutDays:model.validation.days}));}
 const dates=input.calendar.sessions.filter(d=>d>input.actualAsOf&&d<=input.end);console.log('joint simulation '+paths+' paths x 52 x '+dates.length+' sessions');
 const simulation=simulateJointFactor36(models,panel,input.assets,dates,{paths,seed:FACTOR36_POLICY.seed,external});
 const assets=input.assets.map((a,i)=>{const old=b.candidate.assets.find(x=>x.code===a.code),m=models[i],originPrice=a.prices.find(p=>p.date===input.actualAsOf).close,anchor={date:input.actualAsOf,p10:originPrice,p50:originPrice,p90:originPrice,mean:originPrice,return:0,anchor:true,eventIds:[]};const factorRows=registry.factors.map(f=>{const ext=external[i].selected.find(s=>s.factorId===f.id),isMean=m.featureFactors.some((id,j)=>id===f.id&&(m.factorSelection?.acceptedFeatureIndices??m.featureFactors.map((_,k)=>k)).includes(j)),vol=f.id==='F36',used=isMean||vol;return{...f,status:used?(f.id==='F11'?'measured_universe_proxy':'measured_research'):'missing',role:vol?'variance':isMean?'conditional_mean':'not_used',dataAsOf:used?input.actualAsOf:null,validatedImportance:null,currentContribution:null,reason:f.id==='F11'?'ATLAS52 동일가중 가격 폭 대용값 · KOSPI/공식 업종지수 아님':f.id==='F35'?'자기 종목 1·2·5·20·60 거래일':f.id==='F36'?(m.volatility.kind==='garch11'?'자기 잔차 GARCH(1,1) 변동폭':'자기 잔차 경험적 고정 변동폭'):ext?'시점별 검토 원자료 · '+ext.current.unit:'검증된 시점별 원자료·학습 이력 미확보',sourceUrl:ext?ext.current.sourceUrl:used?a.priceSource.url:null};});
 return{...old,numericSummary:null,score:null,training:{status:'factor36_research',through:m.trainedThrough},evidence:{status:'research_only',trustProbability:null},probTop10:null,originPrice,rows:[anchor,...simulation.rows[i]],news:old.news.map(n=>({...n,used:false,effect:null,impact:null,selection:null,positiveFrequency:null,downside:null,upside:null,numericImpactAllowed:false,reason:'일정은 설명 자료 · 기대 대비 결과와 추가 예측력 미검증',waveStatus:'withheld'})),conditionalPath:{trainedThrough:m.trainedThrough,status:'RESEARCH_ESTIMATE'},waveModel:{events:[],fomo:{enabled:m.featureFactors.some((f,j)=>f==='FOMO'&&(m.factorSelection?.acceptedFeatureIndices??m.featureFactors.map((_,k)=>k)).includes(j)),reason:m.featureFactors.some((f,j)=>f==='FOMO'&&(m.factorSelection?.acceptedFeatureIndices??m.featureFactors.map((_,k)=>k)).includes(j))?'검토된 FOMO 이력의 연구 계산':'검증된 관심·개인 수급 학습 입력 미확보'},policy:FACTOR36_POLICY},factorModel:{id:FACTOR36_POLICY.id,selected:m.selected,trainedThrough:m.trainedThrough,trainCount:m.trainCount,regression:m.regression,volatility:m.volatility,featureNames:external[i].featureNames,featureFactors:m.featureFactors,factors:factorRows,factorSelection:m.factorSelection,inputHistory:external[i].history,validation:{...m.validation,rows:undefined},ablations:m.ablations,externalRejected:external[i].rejected,sourceStatus:'retrospective_single_provider_unadjusted',newsStatus:'context_only_no_verified_surprise',trustProbability:null},mode:'research_only',fullHorizonValidated:false,newsEffect:'context_only',probabilityCalibrationId:null,eventsUsed:0};});
 const holdoutDates=[...new Set(models.flatMap(m=>m.validation.rows.map(r=>r.date)))].sort();const byDate=holdoutDates.map(date=>{const rows=models.map(m=>m.validation.rows.find(r=>r.date===date)).filter(Boolean);return{date,stocks:rows.length,crps:mean(rows.map(r=>r.crps)),baselineCRPS:mean(rows.map(r=>r.baseline.crps)),brier:mean(rows.map(r=>r.brier)),baselineBrier:mean(rows.map(r=>r.baseline.brier)),interval:mean(rows.map(r=>r.interval)),baselineInterval:mean(rows.map(r=>r.baseline.interval)),directionAccuracy:mean(rows.map(r=>Number(r.directionCorrect))),baselineDirectionAccuracy:mean(rows.map(r=>Number(r.baseline.directionCorrect))),coverage:mean(rows.map(r=>Number(r.covered))),baselineCoverage:mean(rows.map(r=>Number(r.baseline.covered))),absolutePriceError:mean(rows.map(r=>Number(r.absolutePriceError))),baselineAbsolutePriceError:mean(rows.map(r=>Number(r.baseline.absolutePriceError))),bandWidthLog:mean(rows.map(r=>Number(r.bandWidthLog))),baselineBandWidthLog:mean(rows.map(r=>Number(r.baseline.bandWidthLog))),bandWidthPrice:mean(rows.map(r=>Number(r.bandWidthPrice))),baselineBandWidthPrice:mean(rows.map(r=>Number(r.baseline.bandWidthPrice)))};});
 const candidate={...b.candidate,conditionalPolicy:FACTOR36_POLICY,probabilityCalibration:null,dataDigest:sourceSHA256,inputDigest:sha(JSON.stringify(input)),id,origin:input.actualAsOf,end:input.end,createdAt:at,informationCutoff:at,modelVersion:FACTOR36_POLICY.id,modelStatus:'research_only',validatedPromotion:false,isRetrospectiveReconstruction:true,rowCount:assets.reduce((n,a)=>n+a.rows.length,0),paths,seed:FACTOR36_POLICY.seed,assets,targets:[input.actualAsOf,...dates],trustProbability:null,rankingStatus:'experimental_only',ranking:[],notes:['36요인 사용·미확보 공개','시점·기업행위 미검증 가격의 후향적 비교이며 실전 우위 아님','뉴스 일정 단독 수치 가산 없음']};
 out={schema:'atlas-news-wave-1',id,at,sourceSHA256,semanticSHA256,implementationSHA256,actualAsOf:input.actualAsOf,policy:{...FACTOR36_POLICY,paths},candidate,displayContext:{input,eventGate:b.candidate.eventGate,newsCoverage:b.candidate.newsCoverage,evidenceCoverage:b.candidate.evidenceCoverage,sourceSHA256},summary:{stocks:52,jointPaths:paths,assetPaths:paths*52,availableFactorTypes:[...new Set(assets.flatMap(a=>a.factorModel.factors.filter(f=>f.status!=='missing').map(f=>f.id)))],missingFactorTypes:registry.factors.filter(f=>assets.every(a=>a.factorModel.factors.find(x=>x.id===f.id).status==='missing')).map(f=>f.id),fomoEnabledStocks:assets.filter(a=>a.waveModel.fomo.enabled).length,trustProbability:null,independentAccuracyTests:0,liveAdvantageProven:false,newPricesCollected:false},audit:simulation.audit,validation:{scope:'retrospective_diagnostic_holdout_not_live_or_verified_vintage',dates:byDate,days:byDate.length,rows:models.reduce((s,m)=>s+m.validation.days,0),crps:mean(byDate.map(d=>d.crps)),baselineCRPS:mean(byDate.map(d=>d.baselineCRPS)),brier:mean(byDate.map(d=>d.brier)),baselineBrier:mean(byDate.map(d=>d.baselineBrier)),interval:mean(byDate.map(d=>d.interval)),baselineInterval:mean(byDate.map(d=>d.baselineInterval)),directionAccuracy:mean(byDate.map(d=>d.directionAccuracy)),baselineDirectionAccuracy:mean(byDate.map(d=>d.baselineDirectionAccuracy)),coverage:mean(byDate.map(d=>d.coverage)),baselineCoverage:mean(byDate.map(d=>d.baselineCoverage)),absolutePriceError:mean(byDate.map(d=>d.absolutePriceError)),baselineAbsolutePriceError:mean(byDate.map(d=>d.baselineAbsolutePriceError)),bandWidthLog:mean(byDate.map(d=>d.bandWidthLog)),baselineBandWidthLog:mean(byDate.map(d=>d.baselineBandWidthLog)),bandWidthPrice:mean(byDate.map(d=>d.bandWidthPrice)),baselineBandWidthPrice:mean(byDate.map(d=>d.baselineBandWidthPrice)),fullHorizonTested:false,targets:'one_session',causal:false}};
 await fs.writeFile(file,JSON.stringify(out),{flag:'wx'});
}
const previous=await fs.readFile('public/data/news-wave.json.gz');const oldHash=sha(previous);await fs.mkdir(dir+'/previous',{recursive:true});try{await fs.writeFile(dir+'/previous/'+oldHash+'.json.gz',previous,{flag:'wx'});}catch(e){if(e.code!=='EEXIST')throw e;}
const result=JSON.stringify(out);await fs.writeFile('public/data/news-wave.json.gz',gzipSync(result,{level:9}));await fs.writeFile('public/data/factor36-records.json',recordRaw);await fs.writeFile('public/data/factor36-status.json',JSON.stringify({id:out.id,at:out.at,summary:out.summary,validation:out.validation}));await fs.writeFile(dir+'/latest.json',JSON.stringify({id:out.id,at:out.at,sourceSHA256,implementationSHA256,summary:out.summary,validation:out.validation,audit:out.audit},null,2));
await fs.writeFile('public/downloads/ATLAS_FACTOR36_52_EQUATIONS.json',JSON.stringify(out.candidate.assets.map(a=>({code:a.code,name:a.name,...a.factorModel})),null,2));if(sha(await fs.readFile('public/data/atlas.json'))!==sourceSHA256)throw Error('ORIGINAL_CHANGED');console.log(JSON.stringify({id:out.id,summary:out.summary,validation:{...out.validation,dates:undefined},originalPreserved:true}));
