import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createPressResearch,replacePressResearch,appendPressReport} from '../lib/press-runtime.mjs';
const root=new URL('../',import.meta.url),file=new URL('public/data/atlas.json',root);
const b=JSON.parse(await fs.readFile(file,'utf8'));
const before=JSON.stringify({input:b.input,original:b.original,candidate:b.candidate,priorVersions:b.priorVersions,evaluation:b.evaluation,collectionLogs:b.collectionLogs,actions:b.actions});
const args=process.argv.slice(2),at=new Date().toISOString();
const path=args.includes('--import')?args[args.indexOf('--import')+1]:new URL('public/data/press-history.json',root);
if(!path)throw Error('--import 뒤 파일 경로가 필요합니다.');
const data=JSON.parse(await fs.readFile(path,'utf8'));
const p=b.pressResearch?replacePressResearch(b.pressResearch,b.input,b.candidate,data,{cutoff:at,expectedDataHash:b.pressResearch.dataHash}):createPressResearch(b.input,b.candidate,data,{cutoff:at});
const oldId=b.pressResearch?.report.id;b.pressResearch=appendPressReport(p,b.input,b.candidate,{cutoff:at});
if(JSON.stringify({input:b.input,original:b.original,candidate:b.candidate,priorVersions:b.priorVersions,evaluation:b.evaluation,collectionLogs:b.collectionLogs,actions:b.actions})!==before)throw Error('원본·기존 전망·입력 변경 거부');
if(createHash('sha256').update(JSON.stringify(b.original)).digest('hex')!=='1af446f745c88cfb308de348f238f2fa8d31265b5322e2f035f5aafb6d5833ca')throw Error('최초 재구성본 해시 오류');
await fs.mkdir(new URL('reports/press-history/',root),{recursive:true});
const report=b.pressResearch.report;
await fs.writeFile(new URL('reports/press-history/'+report.id+'.json',root),JSON.stringify(report,null,2)+'\n');
await fs.writeFile(new URL('public/downloads/press_history_report.json',root),JSON.stringify(report,null,2)+'\n');
await fs.writeFile(new URL('public/data/atlas.press.next.json',root),JSON.stringify(b));
await fs.rename(new URL('public/data/atlas.press.next.json',root),file);
console.log(JSON.stringify({reportId:report.id,changed:oldId!==report.id,...report.counts,priceAdjustmentApplied:false,oldForecastsPreserved:true},null,2));
