#!/usr/bin/env python3
import datetime,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1];OUT=ROOT/'reports/completion'
def load(p):return json.loads((ROOT/p).read_text())
inp=load('public/data/input.json');reg=load('public/data/factor36-registry.json')['factors'];obs=load('reports/completion/company-observations.json');commodity=load('reports/completion/company-commodity-history.json');scan=load('reports/completion/company-scan-latest.json');research=load('public/data/researched-news.json')['research']
blockers={
'F25':['historical_guidance_or_consensus_revision_series_incomplete','same_scope_guidance_comparability_unverified','exact_publication_time_and_historical_vintage_missing'],
'F26':['preannouncement_consensus_missing','actual_earnings_alone_are_not_surprise','historical_vintage_and_event_phase_history_incomplete'],
'F27':['TTM_earnings_share_count_and_corporate_actions_unverified','point_in_time_sector_comparables_missing','single_quarter_EPS_not_TTM_valuation'],
'F28':['full_cash_flow_and_debt_maturity_notes_missing','historical_financial_statements_series_incomplete','exact_publication_time_and_vintage_missing'],
'F29':['announced_budget_not_executed_buyback_or_cancellation','phase_execution_history_missing','exact_publication_date_time_missing'],
'F30':['existing_calendar_evidence_is_not_adjusted_corporate_action_factor','terms_latest_corrections_adjustment_and_stage_history_missing'],
'F31':['cumulative_order_total_not_current_quarter_new_orders','company_order_exposure_history_incomplete','publication_vintage_missing'],
'F32':['official_sector_inventory_utilization_history_not_collected','qualitative_full_utilization_is_not_a_percent_time_series'],
'F33':['company_cost_exposure_hedging_contract_lags_missing','historical_release_vintages_not_collected','some_series_estimates_definition_changes_and_third_party_terms_need_per_series_review'],
'F34':['product_selling_price_and_matched_input_cost_series_missing','no_company_product_mix_or_margin_exposure_weights'],
}
factors=[]
for fid in ['F'+str(i) for i in range(25,35)]:
    found=[f for f in obs['facts'] if fid in f['factorIds']];codes=sorted(set(f['code'] for f in found));refs=sorted(set(f['sourceId'] for f in found));src=[s for s in obs['sources'] if s['sourceId'] in refs]
    if fid=='F33':src=[{k:commodity[k] for k in ['sourceUrl','rawHash','rawPath','hashKind','observedAt','publishedAt','pointInTimeVerified']}]
    periods=sorted(set(f['period'] for f in found));history=commodity['observationCount'] if fid=='F33' else len(found)
    factors.append({'factorId':fid,'name':next(f['name'] for f in reg if f['id']==fid),'sourceVerified':bool(src),'componentOnly':bool(src),'definitionComplete':False,'targetCodes':codes,'sourceStockCount':len(codes),'count':history,'historyStart':commodity['historyStart'] if fid=='F33' else periods[0] if periods else None,'historyEnd':commodity['historyEnd'] if fid=='F33' else periods[-1] if periods else None,'historyComplete':False,'publicationVintageVerified':False,'numericalConnectedCodes':[],'numericalConnectedCount':0,'validatedCodes':[],'validatedCount':0,'sources':src,'collectorStatus':'partial_source_body_collection','blockers':blockers[fid],'note':'원자료 구성요소 확보와 계산 가능한 완성 요인을 구분한다.'})
assetReviews=[]
for a in inp['assets']:
    old=next(x for x in research['assets'] if x['code']==a['code']);req=[r for r in scan['results'] if a['code'] in r['codes']];found=[f for f in obs['facts'] if f['code']==a['code']]
    assetReviews.append({'code':a['code'],'name':a['name'],'sector':a['sector'],'sourceScan':req,'newReviewedFactCount':len(found),'newReviewedFactorComponents':sorted(set(fid for f in found for fid in f['factorIds'])),'existingResearchStatus':old['status'],'existingResearchCheckedAt':old.get('latestRecheckAt',old.get('checkedAt')),'existingResearchNote':old.get('note'),'existingEventIds':old.get('eventIds',[]),'historicalResearchReused':True,'newEventApproved':False,'factorChecks':[{'factorId':f['factorId'],'rawComponentAvailable':a['code'] in f['targetCodes'],'sharedRawComponentAvailable':f['factorId']=='F33','completeFactorAvailable':False,'collectorAttempted':bool(req),'collectorBodyReceived':any(r['status']=='body_downloaded_unreviewed' for r in req),'numericObservationCount':sum(f['factorId'] in x['factorIds'] for x in found),'historyComplete':False,'numericalConnection':False,'screenConnection':False,'validation':'not_predictively_validated','blockers':f['blockers']} for f in factors]})
summary={'schema':'atlas-company-completion-summary-1','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z'),'ownedFactorIds':[f['factorId'] for f in factors],'universeCount':len(inp['assets']),'factorStockChecks':len(inp['assets'])*len(factors),'perFactor':factors,'companiesWithNewReviewedNumericalComponents':sorted(set(f['code'] for f in obs['facts'])),'reviewedCompanyObservationCount':len(obs['facts']),'newCompleteFactorCount':0,'newEligibleModelRecords':0,'newApprovedEvents':0,'sourceScan':{'attemptedStocks':len(set(c for r in scan['results'] for c in r['codes'])),'httpBodyStocks':len(set(c for r in scan['results'] if r['status']=='body_downloaded_unreviewed' for c in r['codes'])),'failedStocks':len(set(c for r in scan['results'] if r['status']=='failed' for c in r['codes'])),'sourceBodyVerificationNotImplied':True},'commodity':{k:commodity[k] for k in ['sourceUrl','rawHash','observedAt','seriesCount','observationCount','missingCount','historyStart','historyEnd']},'assets':assetReviews,'requiredAccess':['OpenDART API key (DART_API_KEY or OPENDART_API_KEY) for repeatable financial statement filing history; keep secrets server-side','Licensed timestamped preannouncement consensus history for F25/F26; public actual earnings alone cannot supply it','Authorised sector/product price, inventory/utilisation history and company exposure disclosures for F32/F34/F33 mappings'],'notes':['52개 종목의 기존 조사 자료·실패 이력 유지. 이번 원문 HTTP 성공은 12개이며 미검토 경로를 재무 요인 확보로 세지 않음.','검토한 회사별 수치 50개는 6종목. 원자재 월별 수치 50,383개는 71개 시계열이며 회사별 노출을 뜻하지 않음.','동일 월별 값을 거래일마다 복사해 독립 표본이나 새 사건으로 세지 않음.','원자료·결측·모형 적격성은 별도. 숫자를 억지로 전망에 가산하지 않음.']}
summary['factors']=summary['perFactor']
(OUT/'company-summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
(OUT/'company-summary.md').write_text('# 기업·업종 요인 실제 조사\n\n52종목 × F25~F34 520칸 점검. 공식 회사 본문에서 6종목의 수치 구성요소 50개, 세계은행 월별 원자재 71시계열·50,383관측(1960-01~2026-08)을 확보했다. 과거 빈티지·발표 전 기대치·회사 원가 노출 등 미확보 항목은 계산 적격으로 승격하지 않았다.\n\n|요인|회사별 구성요소 확보|계산 연결|차단|\n|---|---:|---:|---|\n'+'\n'.join('|'+f['factorId']+' '+f['name']+'|'+str(f['sourceStockCount'])+'/52|0/52|'+'; '.join(f['blockers'])+'|' for f in factors)+'\n\n전체 52종목 기존 경로 HTTP 재접속은 12성공·40시간초과. 검색 요약과 홈페이지 수신을 원자료 검증 완료로 바꾸지 않았다. Node 운영 수집기는 기존 createCompanyCollector를 재사용해 후보 원문만 저장하며 과거 모형을 발행하지 않는다.\n')
print(json.dumps({'factorChecks':summary['factorStockChecks'],'reviewedFacts':len(obs['facts']),'sourceScan':summary['sourceScan'],'factorComponents':{f['factorId']:f['sourceStockCount'] for f in factors}},ensure_ascii=False))
