import fs from 'node:fs';import {spawn} from 'node:child_process';import {chromium} from '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const server=spawn('python3',['-m','http.server','5175','--bind','127.0.0.1','--directory','../web'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,500));
const browser=await chromium.launch({executablePath:'/tmp/atlas-chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process']});const p=await browser.newPage({viewport:{width:1366,height:768}});const r={checks:[],errors:[]};const check=(name,pass)=>{r.checks.push({name,pass});if(!pass)throw Error(name);};p.on('pageerror',e=>r.errors.push(e.message));
try{await p.goto('http://127.0.0.1:5175');await p.locator('.focus-card [data-pulse-chart]').waitFor({timeout:120000});await p.locator('[data-studio-code="005930"]').click();
check('new chart default',await p.locator('.focus-card [data-pulse-chart]').count()===1);check('daily bars present',await p.locator('.focus-card [data-pulse-date]').count()>15);
const bars=await p.locator('.focus-card [data-pulse-date]').evaluateAll(es=>es.map(e=>({date:e.getAttribute('data-pulse-date'),rate:Number(e.getAttribute('data-rate'))})));check('rises and falls visible',bars.some(b=>b.rate<0)&&bars.some(b=>b.rate>0));
const down=bars.find(b=>b.rate<0);await p.locator(`.focus-card [data-pulse-date="${down.date}"]`).click();check('bar selects same date explanation',await p.locator('.focus-card [data-play-date]').textContent()===down.date);check('exact daily percentage displayed',await p.locator('.focus-card .pulse-callout').textContent().then(t=>t.includes((down.rate*100).toFixed(2)+'%')));
await p.screenshot({path:'reports/pulse/desktop.png'});await p.locator('.focus-card .pulse-toolbar').getByRole('button',{name:'전체 가격',exact:true}).click();check('full actual and forecast view preserved',await p.locator('.focus-card [data-actual-path]').count()===1&&await p.locator('.focus-card [data-forecast-code]').count()===1);await p.locator('.focus-card .pulse-toolbar').getByRole('button',{name:'일별 등락',exact:true}).click();
await p.locator('.focus-card [data-pulse-chart]').focus();await p.keyboard.press('End');check('keyboard selects last forecast date',await p.locator('.focus-card [data-play-date]').textContent()==='2026-10-30');
for(const [width,height]of [[1366,640],[390,844],[320,740]]){await p.setViewportSize({width,height});if(await p.locator('.mobile-sheet-close').isVisible())await p.locator('.mobile-sheet-close').click();const m=await p.evaluate(()=>{const a=document.querySelector('.focus-card .pulse-shell').getBoundingClientRect(),c=document.querySelector('.focus-card .stock-controls').getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>innerWidth,separated:a.bottom<=c.top+1,height:a.height};});check(`layout ${width}`,!m.overflow&&m.separated&&m.height>=180);await p.screenshot({path:`reports/pulse/screen-${width}.png`,fullPage:true});}
await p.setViewportSize({width:1366,height:768});await p.locator('.focus-card [data-date="2026-09-28"]').click();await p.locator('.focus-card [data-play-toggle]').click();await p.waitForTimeout(1150);check('playback advances with new chart',await p.locator('.focus-card [data-play-date]').textContent()!=='2026-09-28');await p.locator('#atlas-nav-race').click();check('equal start page retained',await p.locator('[data-equal-code]').count()===52);
}catch(e){r.errors.push(e.stack);}finally{r.passed=r.errors.length===0&&r.checks.every(c=>c.pass);fs.writeFileSync('reports/pulse/browser.json',JSON.stringify(r,null,2));await browser.close();server.kill();}console.log(JSON.stringify(r));if(!r.passed)process.exitCode=1;
