import fs from'node:fs';import{spawn}from'node:child_process';import{chromium}from'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';import{initialState,clientState}from'../lib/service.mjs';
const b=JSON.parse(fs.readFileSync('public/data/atlas.json')),stale=clientState(initialState(b));stale.active=stale.versions[0].id;stale.input.actualAsOf='2026-09-22';
const server=spawn('python3',['-m','http.server','5179','--bind','127.0.0.1','--directory','../web'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,400));const browser=await chromium.launch({executablePath:'/tmp/atlas-chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process']});const p=await browser.newPage({viewport:{width:1366,height:900}}),report={checks:[],errors:[]};p.on('pageerror',e=>report.errors.push(e.message));const check=(name,pass)=>{report.checks.push({name,pass});if(!pass)throw Error(name);};
try{
 await p.route('**/api/atlas',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state:stale,authConfigured:false})}));
 await p.goto('http://127.0.0.1:5179');await p.locator('.focus-card [data-wave-reason]').waitFor({timeout:20000});await p.waitForTimeout(600);check('different saved version and quote date cannot block the screen',await p.locator('[data-selected-forecast]').getAttribute('data-selected-forecast').then(x=>x.includes('-wave-')));check('matching quote snapshot displayed',await p.locator('.workspace-context').textContent().then(s=>s.includes('09/23')));
 await p.locator('#atlas-nav-race').click();check('all 52 series coexist in one graph',await p.locator('[data-race-series]').count()===52);check('all 52 dots begin at same value',await p.locator('[data-race-dot]').evaluateAll(es=>new Set(es.map(e=>e.getAttribute('cy'))).size===1));check('all 52 current ranks rendered',await p.locator('[data-equal-code]').count()===52);
 await p.locator('[data-equal-play]').click();await p.waitForTimeout(1150);check('one second advances one trading day',await p.locator('[data-equal-date]').textContent()==='2026-09-18');await p.locator('[data-equal-play]').click();
 await p.locator('[data-race52-chart]').focus();await p.keyboard.press('End');check('keyboard reaches final date',await p.locator('[data-equal-date]').textContent()==='2026-10-30');check('52 lines remain after playback',await p.locator('[data-race-series]').count()===52);
 const row=p.locator('[data-equal-code="010170"]');await row.click();check('selected line and own explanation share company',await p.locator('[data-race-selected]').getAttribute('data-race-selected')==='010170'&&await p.locator('.race52 [data-wave-reason="010170"]').count()===1);
 await p.screenshot({path:'reports/race52/desktop.png',fullPage:true});
 for(const width of[390,320]){await p.setViewportSize({width,height:844});check(`mobile ${width} no outer overflow`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(`mobile ${width} all paths stay available`,await p.locator('[data-race-series]').count()===52);await p.screenshot({path:`reports/race52/mobile-${width}.png`,fullPage:true});}
 await p.setViewportSize({width:1366,height:900});await p.locator('[data-equal-code="005930"]').click();const dates=b.input.calendar.sessions.filter(d=>d>=b.input.origin&&d<=b.input.end),i=dates.indexOf('2026-09-29');await p.getByLabel('1만원 순위 날짜').fill(String(i));await p.getByLabel('중요 장면에서 멈춤').check();await p.locator('[data-equal-play]').click();await p.waitForTimeout(1150);check('important selected news pauses on arrival',await p.locator('[data-equal-date]').textContent()==='2026-09-30'&&await p.locator('[data-equal-play]').textContent()==='설명 확인 · 계속');await p.waitForTimeout(1150);check('news pause persists until confirmation',await p.locator('[data-equal-date]').textContent()==='2026-09-30');await p.locator('[data-equal-play]').click();await p.waitForTimeout(1150);check('confirmation continues to next trading session',await p.locator('[data-equal-date]').textContent()==='2026-10-01');await p.locator('#atlas-nav-score').click();check('new-only score page stays available',await p.locator('[data-wave-score]').count()===1);
}catch(e){report.errors.push(e.stack);report.body=(await p.locator('body').textContent()).slice(0,2000);}finally{report.passed=!report.errors.length&&report.checks.every(c=>c.pass);fs.writeFileSync('reports/race52/browser.json',JSON.stringify(report,null,2));await browser.close();server.kill();}console.log(JSON.stringify(report));if(!report.passed)process.exitCode=1;
