import fs from'node:fs';import{createHash}from'node:crypto';import{gunzipSync}from'node:zlib';import{spawn}from'node:child_process';import{chromium}from'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const dir='reports/factor36';const server=spawn('python3',['-m','http.server','5182','--bind','127.0.0.1','--directory','../release/web'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,400));const browser=await chromium.launch({executablePath:'/tmp/atlas-chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process']});const p=await browser.newPage({viewport:{width:1366,height:768}}),report={checks:[],errors:[],physicalDevice:false,buildIndexSHA256:createHash('sha256').update(fs.readFileSync('../release/web/index.html')).digest('hex'),forecastId:JSON.parse(gunzipSync(fs.readFileSync('../release/web/data/news-wave.json.gz'))).id};p.on('pageerror',e=>report.errors.push(e.message));const check=(name,pass)=>{report.checks.push({name,pass});if(!pass)throw Error(name);};
try{
 await p.goto('http://127.0.0.1:5182');await p.locator('.focus-card [data-factor36-reason]').waitFor({timeout:60000});await p.waitForTimeout(500);
 check('new factor36 version renders',await p.locator('[data-selected-forecast]').getAttribute('data-selected-forecast').then(x=>x.includes('-factor36-')));
 check('52 selectable companies',await p.locator('[data-studio-code]').count()===52);
 await p.locator('[data-studio-code="005930"]').click();await p.locator('.focus-card [data-pulse-chart]').waitFor();
 check('complete trading-date graph displayed initially',await p.locator('.focus-card [data-angular-segment]').count()===23);
 const xs=await p.locator('.focus-card [data-session-x]').evaluateAll(es=>es.map(e=>Number(e.getAttribute('data-session-x'))));check('equal trading-day spacing',xs.slice(2).every((x,i)=>Math.abs(x-xs[i+1]-(xs[1]-xs[0]))<1e-6));
 const last=p.locator('.focus-card [data-pulse-date="2026-10-30"]');await last.click();check('chart click changes this company date',await p.locator('.focus-card [data-reason-date]').getAttribute('data-reason-date')==='2026-10-30');
 check('36 factors and honest probability wording',await p.locator('.focus-card [data-factor-id]').count()===36&&await p.locator('.focus-card [data-factor36-reason]').textContent().then(s=>s.includes('적중 확률은 미검증')));
 await p.screenshot({path:dir+'/desktop.png'});
 await p.getByRole('button',{name:'실제와 전체',exact:true}).click();check('actual and forecast paths retained',await p.locator('.focus-card [data-actual-path]').count()===1&&await p.locator('.focus-card [data-forecast-code]').count()===1);await p.getByRole('button',{name:'전망 확대',exact:true}).click();
 for(const [width,height]of[[1280,600],[390,844],[320,740]]){await p.setViewportSize({width,height});await p.waitForTimeout(180);if(await p.locator('.mobile-sheet-close').isVisible())await p.locator('.mobile-sheet-close').click();check('no horizontal overflow '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('last date within graph '+width,await last.evaluate(e=>{const a=e.querySelector('circle').getBoundingClientRect(),b=e.closest('svg').getBoundingClientRect();return a.left>=b.left&&a.right<=b.right;}));await p.screenshot({path:dir+'/screen-'+width+'.png',fullPage:width<500});}
 await p.setViewportSize({width:1366,height:768});await p.locator('#atlas-nav-race').click();check('52 paths at once',await p.locator('[data-race-series]').count()===52);check('52 ranks',await p.locator('[data-equal-code]').count()===52);check('same 10000 starting value',await p.locator('[data-race-dot]').evaluateAll(es=>new Set(es.map(e=>e.getAttribute('cy'))).size===1));await p.locator('[data-equal-play]').click();await p.waitForTimeout(1150);check('one second one trading day',await p.locator('[data-equal-date]').textContent()==='2026-09-18');await p.locator('[data-equal-play]').click();
 await p.locator('[data-equal-code="005930"]').click();const b=JSON.parse(fs.readFileSync('public/data/atlas.json')),dates=b.input.calendar.sessions.filter(d=>d>=b.input.origin&&d<=b.input.end);await p.getByLabel('1만원 순위 날짜').fill(String(dates.indexOf('2026-09-28')));await p.locator('[data-equal-play]').click();await p.waitForTimeout(1150);check('news pauses at first event',await p.locator('[data-equal-date]').textContent()==='2026-09-29'&&await p.locator('[data-equal-play]').textContent()==='설명 확인 · 계속');await p.waitForTimeout(1100);check('pause awaits confirmation',await p.locator('[data-equal-date]').textContent()==='2026-09-29');await p.locator('[data-equal-play]').click();await p.waitForTimeout(1150);check('consecutive news pauses again',await p.locator('[data-equal-date]').textContent()==='2026-09-30'&&await p.locator('[data-equal-play]').textContent()==='설명 확인 · 계속');
 await p.locator('[data-race52-chart]').focus();await p.keyboard.press('End');check('all 52 paths reach final date',await p.locator('[data-equal-date]').textContent()==='2026-10-30'&&await p.locator('[data-race-series]').count()===52);await p.screenshot({path:dir+'/race-desktop.png'});
 for(const width of[390,320]){await p.setViewportSize({width,height:844});check('race mobile fits '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:dir+'/race-'+width+'.png',fullPage:true});}
 await p.setViewportSize({width:1366,height:768});await p.locator('#atlas-nav-score').click();check('52 daily outcomes kept pending without new actual prices',await p.locator('[data-wave-score] tbody tr').count()===52&&await p.locator('[data-wave-score]').textContent().then(s=>s.includes('대기 52')));
 await p.locator('#atlas-nav-evolution').click();await p.locator('[data-factor36-audit]').waitFor();check('holdout and failed collection disclosed',await p.locator('[data-factor36-audit]').textContent().then(s=>s.includes('60거래일')&&s.includes('개선되지 않음')&&s.includes('정상 응답 0')));
 for(const url of['/downloads/ATLAS_FACTOR36_52_EQUATIONS.json','/downloads/ATLAS_FACTOR36_PLAN.md'])check('download available '+url,(await p.request.get('http://127.0.0.1:5182'+url)).ok());
}catch(e){report.errors.push(e.stack);report.body=(await p.locator('body').textContent()).slice(0,2200);await p.screenshot({path:dir+'/browser-failure.png',fullPage:true});}finally{report.passed=!report.errors.length&&report.checks.every(c=>c.pass);fs.writeFileSync(dir+'/browser.json',JSON.stringify(report,null,2));await browser.close();server.kill();}console.log(JSON.stringify(report));if(!report.passed)process.exitCode=1;
