import fs from 'node:fs';
import {researchCoverage} from '../lib/researched-news.mjs';
import {scopeCounts} from '../lib/news-scope.mjs';
const b=JSON.parse(fs.readFileSync('public/data/atlas.json')),rows=researchCoverage(b.input,b.candidate),c=scopeCounts(b.candidate.eventGate.accepted),n=rows.filter(r=>r.byScope.company+r.byScope.sector>0).length;
const summary=`52종목의 확인 내역을 수록하고 ${n}종목에 기업·업종 관련 일정을 연결했습니다. 남은 미래 일정은 시장 공통 ${c.market}건, 지수 ${c.index}건, 업종 ${c.sector}건, 기업 ${c.company}건입니다. 기업 일정에는 한국가스공사의 적용월 시작 안내 1건이 포함됩니다. 나머지 ${52-n}종목은 확정 날짜를 확보하지 못했습니다.`;
const batch=b.input.newsResearch.batchReview;
const batchSection=[...(b.input.newsResearch.batchReviewHistory??[]),batch].filter(v=>v?.addedEventIds).map(v=>`## ${v.searchedCount}종목 조사 기록\n\n${v.checkedAt}: ${v.agentCount}개 조사팀이 ${v.searchedCount}종목을 확인해 ${v.newlyConfirmedCodes.length}종목 일정 ${v.addedEventIds.length}건을 추가했습니다. 당시 미확보 ${v.unresolvedCodes.length}종목. 조사 기록과 날짜 확보 완료는 다릅니다.\n\n${v.addedEventIds.map(id=>{const e=b.input.events.find(e=>e.id===id);return e?`- ${e.name}: ${e.eventDate} → 그래프 표시 ${e.targetDate}. 수치 영향 유보.`:''}).filter(Boolean).join('\n')}\n\n${(v.reports??[]).map(p=>`- [종목별 근거·한계](${p.split('/').at(-1).replace('.json','.md')})`).join('\n')}\n\n`).join('');
const md=`# ATLAS 6.1.2 — 종목별 뉴스 입력\n\n${b.input.newsResearch.checkedAt}\n\n${summary}\n\n${batchSection}업종 일정은 해당 기업 참가·수주가 확정됐다는 뜻이 아닙니다. 홈페이지·조사 경로·날짜 미확인 계획은 뉴스 건수에 합산하지 않습니다. 신규 입력 중 수치 계산에 사용된 사건은 대한항공 유류할증료 정책 1건입니다. 확인한 과거 7개 적용월 중 같은 날 다른 발표와 겹친 2건을 제외한 5개 표본을 사용합니다. 방향 검증이 부족하면 평균 효과는 0이고 발표일 변동폭만 사용합니다. 다른 신규 일정은 비교 표본이 부족해 가격 영향을 유보합니다.\n\n## 52종목 확인 내역\n\n| 종목 | 기업 | 업종 | 확인 내용 | 조사 경로 |\n|---|---:|---:|---|---|\n${rows.map(r=>`| ${r.name} (${r.code}) | ${r.byScope.company} | ${r.byScope.sector} | ${r.note} | ${r.sources.map(s=>`[자료](${s.url})`).join(' · ')} |`).join('\n')}\n\n## 추가한 미래 일정\n\n| 일정 | 행사·정책일 | 그래프 표시일 | 구분 | 원문 |\n|---|---|---|---|---|\n${b.candidate.eventGate.accepted.filter(e=>e.id.startsWith('REVIEW:')).map(e=>`| ${e.name} | ${e.eventDate} | ${e.targetDate} | ${e.scope.type==='company'?'기업':'업종 관찰'} | [원문](${e.sources[0].url}) |`).join('\n')}\n\n## 25종목 후속 조사\n\n요청한 25종목 중 ${b.input.newsResearch.followup25.fullyConfirmedCompanyScheduleCodes.length}종목의 기업 관련 일정 원문을 확인했으며, ${b.input.newsResearch.followup25.unresolvedCodes.length}종목은 미확인 상태입니다. 두산에너빌리티 9/29 기업설명회에 더해 삼성생명·삼성화재의 10/2 재공시 예정일을 DART 본문으로 확인했습니다. 두 보험사의 인수 결정은 미확정이며, 예정일 전에 후속 공시할 수도 있습니다. 에스원의 10/12 공동 세미나는 주최사 공지로 확인했습니다. 현대글로비스와 현대건설의 9/30 기업설명회는 각 DART 공시 본문, 현대모비스의 10/23 램프사업 거래 검토 재공시는 한국거래소 원문으로 대조했습니다. 현대모비스 거래 성사 여부는 미확정입니다. 이 일정은 각 기업에만 연결하며 비교 표본 부족으로 수치 영향은 유보했습니다. ${b.input.newsResearch.followup25.unresolvedCodes.includes("226950")?"올릭스 10/7 IR 참가의 공식 기업 명단 대조는 미완료입니다.":"올릭스 10/7 IR 참가는 금융위원회 공동주최 자료의 기업 명단과 현행 한국거래소 행사 날짜로 확인했습니다. 기존 KIRS 접근 실패와 후속 대용량 브로슈어 미대조 한계는 보존했습니다."}\n\n## 남은 ${b.input.newsResearch.followup25.unresolvedCodes.length}종목의 확인 상태\n\n| 종목 | 마지막 확인과 미확보 이유 | 우선 원문 |\n|---|---|---|\n${b.input.newsResearch.followup25.unresolvedCodes.map(code=>{const r=rows.find(v=>v.code===code);return `| ${r.name} (${r.code}) | ${r.note} | [IR·공시](${r.sources[0].url}) |`}).join('\n')}\n\n## 남은 확인 사항\n\n지수 구성 근거가 부족해 지수 0건을 유지했습니다. 특정 종목의 기업 고유 일정이 없다는 것은 뉴스 자체가 없다는 확정 판단이 아닙니다. 일부 IR 화면은 접근 제한 또는 빈 화면이었습니다. 회사 홈페이지 링크는 일정 확인의 증거가 아닙니다. K-BEAUTY와 케어젠 연구 자료는 9/24 공식 검색자료 확인 기록을 사용했고, 9/25 원문 재접속은 제한됐습니다.\n\n작업 공간 자동 정리 뒤 보관 ZIP에서 복원하고 9/24 조사 요약을 다시 입력했습니다. 확인한 사건과 근거를 보수적으로 이번 재입력 시각부터 사용합니다. 기존 9/17 재구성본과 보관 ZIP에 있던 모든 이전 전망·감사는 유지했습니다. 정리로 사라진 미저장 중간 계산 파일을 복구했다고 주장하지 않습니다.\n\n새로운 뉴스 추가가 예측 정확도를 입증하지는 않습니다. 기존 사후 감사는 이번 입력의 검증 결과가 아닙니다.\n`;
for(const p of ['public/downloads/NEWS_RESEARCH_52.md','reports/NEWS_RESEARCH_52.md'])fs.writeFileSync(p,md);
for(const p of ['README.md','public/downloads/README.md','public/downloads/NEWS_INPUT.md']){
 let s=fs.readFileSync(p,'utf8');s=s.replace(/현재[^\n]*지수[^\n]*0건[^\n]*/g,'');
 s=s.replace(/\n\n## 6\.1(?:\.\d+)? 종목별 뉴스 추가[\s\S]*$/, '');
 s+='\n\n## 6.1.2 종목별 뉴스 추가\n\n'+summary+'\n\n뉴스 탭의 52종목 조사 결과와 종목 상세의 조사 결과·출처에서 확인합니다. 기존 저장 자료에도 누적 뉴스 목록 전체가 이전되며 원본과 사용자 수정은 보존됩니다. 상세 근거는 NEWS_RESEARCH_52.md와 researched-news.json에 있습니다.\n';fs.writeFileSync(p,s);
}
console.log(summary);
