import fs from 'node:fs';import{createHash}from'node:crypto';
const read=p=>fs.readFileSync(p,'utf8'),hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const bundle=JSON.parse(read('public/data/atlas.json')),before=JSON.parse(read('reports/breaking/preservation-before.json')),breaking=bundle.breaking;
const versions=new Map([bundle.original,...bundle.priorVersions,bundle.candidate].map(v=>[v.id,v]));for(const[id,h]of Object.entries(before.versions))if(hash(versions.get(id))!==h)throw Error('기존 발행본 변경: '+id);
if(process.argv.includes('--release'))for(const[k,h]of Object.entries(before.fields))if(hash(bundle[k])!==h)throw Error('개발 릴리스 기존 자료 변경: '+k);
const tap=read('reports/tests.tap');if(!/# fail 0\s/.test(tap))throw Error('최종 검사 미완료');
const report={at:new Date().toISOString(),uiVersion:'8.3.0',baselineEngine:bundle.candidate.modelVersion,originalSHA:hash(bundle.original),preservedForecasts:Object.keys(before.versions).length,tests:Number(tap.match(/# tests (\d+)/)?.[1]),failed:0,events:breaking.events.length,candidates:breaking.candidates.length,decisions:breaking.decisions.length,forecasts:breaking.forecasts.length,evaluations:breaking.evaluations.length,actualAsOf:bundle.input.actualAsOf,realtimeMonitorConnected:false,sourceVerificationAutomated:false,liveDeployment:false,pixelBrowserVerified:false,forecastSkillValidated:false,newCollectionDuringDevelopment:false};
fs.writeFileSync('reports/breaking/validation.json',JSON.stringify(report,null,2));
const body=`# ATLAS 8.3 — 돌발 뉴스와 전망 변경 추적\n\n기존 52종목·9/17~10/30·${report.preservedForecasts}개 발행 전망과 진화 이력을 보존하고, 돌발 사건→전제 검토→유지/관찰/정성 시나리오/변경 검토→별도 전망→사후 비교를 연결했습니다. 현재 사건${report.events}건·수집 검토 후보${report.candidates}건·결정${report.decisions}건·별도 전망${report.forecasts}건·평가${report.evaluations}건입니다.\n\n## 운영 방법\n돌발 뉴스 탭에서 종목을 클릭하고 출처·공개 시각·경제 사건·단계·사업 연결·전제 변화 내용을 등록합니다. 수집 후보는 원문 검토 전이며 후보 선택만으로 사실이나 기업 참가·가격 영향이 승인되지 않습니다. 등록 시각은 시스템이 저장합니다. 같은 내용은 중복 기록하지 않고 정정·철회는 이전 사건 ID를 연결한 새 기록입니다.\n\n유지/관찰/시나리오/변경을 요청하면 실제 처리와 유보 사유를 저장합니다. 필요한 수치 근거가 없으면 변경 요청이 관찰로 남습니다. 정성 시나리오는 가격이나 확률을 만들어내지 않습니다. 고급 검토 자료 JSON 입력을 지원하며 URL·원문 식별값의 존재 검사는 원문의 진위를 자동 인증하지 않습니다. 과거 예측의 원전제가 없던 경우 현재 전제 설명은 사후 재구성 가설입니다.\n\n## 방정식\n별도 돌발뉴스 모형은 동일 종목·동일 사건 단계의 독립 과거 사건에서 조정 가격과 발표 전 예상으로 재현 가능한 로그 잔차를 사용합니다. 최소5개 조건 통과 뒤 Δ=Σ잔차/(n+5), P변경=P기준×exp(Δ)를 한 번 적용하고 이후 수준에 유지하는 시험 모형입니다. 매일 Δ를 반복 더하지 않습니다. 정정 대체는 원래 기준 전망과 이전 변경안의 ID를 명시하고 새 사건 revision의 근거를 재검토한 경우만 별도 저장하며, 이전 충격에 새 충격을 누적하지 않습니다. 기존 진화 잔차 보정과 중복 반영을 차단합니다. 5표본·축소상수5는 최적값이나 실전 효과 인증이 아닙니다. 상세 조건: ATLAS_BREAKING_EQUATIONS.md.\n\n숫자 변경은 다음 한국 거래일부터 표시하는 현재 구현입니다. 장중 즉시 체결·실시간 반영 모델이 아닙니다. 발행 전 구간은 새 선으로 꾸미지 않습니다. 이미 기준 가격·예측에 반영된 사건, 미해결 중요 사건 중첩은 수치 변경을 유보합니다.\n\n## 성과와 원인\n이후 확보한 동일 목표일·동일 가격 빈티지에서 |기준예측−실제|/실제 − |변경예측−실제|/실제를 기록합니다. 양수는 변경안의 오차 감소, 음수는 악화입니다. KEEP의 두 전망은 같으므로 개선0이지 성공 인증이 아닙니다. 원인 미확인은 UNKNOWN이며 사용자 사업 경로는 가설입니다. 가격 정정은 예전 평가를 지우지 않고 새 빈티지를 추가합니다. 발행 시 확인 가능한 가격이 있으면 가격 유지 기준과도 비교하고 없으면 미산정으로 남깁니다. 서로 다른 변경안의 같은 날짜를 독립 표본으로 세지 않습니다.\n\n## 수집과 배포 범위\n기존 npm run refresh에 수집 후보 연결과 돌발 전망 평가를 통합했습니다. npm run breaking은 보관 수집자료를 연결할 뿐 새 원문 수집이 아닙니다. 기존 일일 수집과 수동 등록을 지원하며 실시간 감시 서비스는 연결하지 않았습니다. 기존의 수집 실패·가격 단일 제공자·기업행위 조정 및 발표 예상 자료 부족을 보존합니다.\n\n경량 ATLAS_Evolution_Netlify.zip은 정적 화면/기기 저장용입니다. 전체 ATLAS_Netlify.zip에 서버 코드가 포함되지만 Netlify 계정 배포·서버 수집·구글로그인 설정까지 완료됐다는 뜻은 아닙니다.\n\n## 검증\n최종 자동 검사${report.tests}개 통과, 실패0. 원본 SHA ${report.originalSHA}. 기존 전망 및 진화 이력의 불변 검사는 개발 릴리스 단계에서 실시했습니다. 실제 브라우저 픽셀 검사는 미완료입니다. 합성 반례·수학·UI 검사가 실제 뉴스 인과관계나 투자 적중을 인증하지 않습니다.\n\n참고: https://otexts.com/fpp3/forecasting-regression.html 및 https://otexts.com/fpp3/tscv.html — 당시 정보와 이후 결과를 분리해 평가하는 원칙. 본 모형의 실전 우위 증거가 아닙니다.\n`;
fs.writeFileSync('public/downloads/ATLAS_BREAKING.md',body);
for(const name of ['README.md','VALIDATION.md']){const old=read(name);if(!old.startsWith('# ATLAS 8.3'))fs.writeFileSync(name,body+'\n---\n이하 이전 릴리스 보존 기록\n\n'+old);}
console.log(JSON.stringify(report));
