import fs from 'node:fs';import{createHash}from'node:crypto';
const read=p=>fs.readFileSync(p,'utf8'),hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const b=JSON.parse(read('public/data/atlas.json')),before=JSON.parse(read('reports/evolution/preservation-before.json'));
const allVersions=new Map([b.original,...b.priorVersions,b.candidate].map(v=>[v.id,v]));for(const [id,h]of Object.entries(before.versions))if(hash(allVersions.get(id))!==h)throw Error('Original forecast changed: '+id);
if(process.argv.includes('--release'))for(const [k,h]of Object.entries(before.bundleFields))if(hash(b[k])!==h)throw Error('Release input changed: '+k);
const tap=read('reports/tests.tap');if(!/# fail 0\s/.test(tap))throw Error('Final tests not passed');
const last=b.evolution.versions.find(v=>v.id===b.evolution.activeId)??b.evolution.versions.at(-1),tests=Number(tap.match(/# tests (\d+)/)?.[1]);
const report={at:new Date().toISOString(),uiVersion:'8.2.0',baselineEngine:'atlas-news-8.0.1',evolutionPolicy:last.policy.id,originalHash:hash(b.original),preservedForecasts:Object.keys(before.versions).length,tests,failed:0,shadowVersions:b.evolution.versions.length,assets:last.assets.length,trained:last.assets.filter(a=>a.training.status==='TRAINED').length,actualAsOf:b.input.actualAsOf,newPriceCollection:process.argv.includes('--release')?false:null,latestCollection:b.collectionLogs?.at(-1)??null,pixelBrowserVerified:false,liveDeployment:false,forecastSkillValidated:false};
fs.writeFileSync('reports/evolution/validation.json',JSON.stringify(report,null,2));
const body=`# ATLAS 8.2 — 진화창\n\n기존 17개 전망을 보존하고 별도 진화 예측·발행 기록·실제 오차·수정 가설을 추가했습니다. 현재 ${last.assets.length}종목 중 학습 자격 충족 ${report.trained}종목이며, 미충족 종목은 기존 경로를 복사한 학습 대기로 표시합니다. 보관 공통 종가 ${b.input.actualAsOf}; ${process.argv.includes('--release')?'이번 개발에서 새 종가를 수집하지 않았습니다.':'최근 수집의 성공/실패는 자료·운영 기록과 collectionLogs를 확인하세요.'}\n\n## 매일 운영\n거래일 한국시간16시 수집 시작. 수집에 성공한 종목의 확인된 종가만 기록하고 부분 실패를 유지합니다. npm run refresh는 진화 기록을 함께 갱신합니다. npm run evolve는 보관 자료에서 진화 기록만 갱신하며 네트워크 수집이 아닙니다. 기간9/17~10/30은 고정합니다.\n\n## 방정식과 검증\n독립 종목의 결과 전에 발행된 다음 거래일 잔차만 사용합니다. e=log(실제/당시예측), c=Σe/(5+n), n>=5에서만 보정합니다. 향후 h거래일 가격은 원래 가격×exp(c×h)입니다. 최소5일·축소상수5는 검증된 최적값이 아닌 고정 시험정책입니다. 최대최근20개 고유목표일, 미래자료·사후재구성·자기 진화예측 학습 제외. 자세한 식은 ATLAS_EVOLUTION_EQUATIONS.md. 실전 우위는 미입증입니다.\n\n학습에 사용한 자료·계수·발행 시각을 고정해 저장합니다. 새 공식의 평가는 발행 이후 실제값만 사용합니다. 과거 전체 구간의 중앙값을 덮어쓰지 않습니다. P10~P90도 시험 보정 범위이며 보정된 적중확률로 인증하지 않습니다.\n\n## 진화창\n52종목 클릭 선택 → 원본/선택전망/실제/진화안 비교 → 날짜별 오차 → 확인된 기록·가설·미확인 구분 → 공식·학습 자료 → 버전 이력. 미래결과·휴장종가를 만들지 않습니다. 발행 전 진화예측은 표시하지 않습니다. 추가/축소/제외 의견은 가설로 보존하며 자동계수승인하지 않습니다.\n\n## 검사와 한계\n최종 자동 검사 ${tests}개 통과, 실패0. 최초 SHA ${report.originalHash}. 원래17개 전망 해시 보존. 기존 자료 필드 전체 불변 검사는 8.2 개발 릴리스에 한정합니다. 실제 브라우저 픽셀/기기 검사는 미완료입니다. Netlify실제배포는 수행하지 않았습니다. 정적Drop ZIP은 화면/기기저장용이며 서버 자동수집·구글로그인은 별도Netlify설정이 필요합니다. 기존일정갱신은ZIP을갱신하며정적배포사이트에자동전달됐다는뜻은아닙니다.\n\n기존 model_audit·Design365·daily-report는 당시 릴리스 기록이며 진화모형의 정확도 인증이 아닙니다. 신규 기업 뉴스 인과자료·가격 기업행위 조정·이중출처 검증 부족은 계속 남아 있습니다.\n\n참고: https://otexts.com/fpp3/tscv.html — 시간순 과거학습/이후평가 원칙. 본 잔차식의 실제 우위를 보장하는 출처는 아닙니다.\n`;
fs.writeFileSync('public/downloads/ATLAS_EVOLUTION.md',body);
for(const f of ['README.md','VALIDATION.md']){const s=read(f);if(!s.startsWith('# ATLAS 8.2'))fs.writeFileSync(f,body+'\n---\n이하 이전 릴리스 보존 기록\n\n'+s);}
console.log(JSON.stringify({...report,latestCollection:report.latestCollection?{at:report.latestCollection.at,day:report.latestCollection.day,partial:report.latestCollection.partial,exitCode:report.latestCollection.exitCode}:null}));
