import fs from 'node:fs';
import {createHash} from 'node:crypto';
const read=p=>fs.readFileSync(p,'utf8'),sha=x=>createHash('sha256').update(x).digest('hex');
const b=JSON.parse(read('public/data/atlas.json')),before=JSON.parse(read('reports/clarity/preservation-before.json'));
const release=process.argv.includes('--release');
const versions=new Map();for(const v of [b.original,...b.priorVersions,b.candidate]){const h=sha(JSON.stringify(v));if(versions.has(v.id)&&versions.get(v.id)!==h)throw Error('Conflicting forecast '+v.id);versions.set(v.id,h);}
for(const[id,h]of Object.entries(before.versions))if(versions.get(id)!==h)throw Error('Prior forecast changed '+id);
if(release)for(const[p,h]of Object.entries(before.files))if(sha(fs.readFileSync(p))!==h)throw Error('UX release changed model/data '+p);
const tap=read('reports/tests.tap'),n=k=>Number(tap.match(new RegExp('# '+k+' (\\d+)(?:\\s|$)'))?.[1]);
if(n('fail')!==0||n('pass')!==n('tests')||!n('tests'))throw Error('Final tests are incomplete');
const report={at:new Date().toISOString(),version:'8.5.0',edition:'ATELIER365 · CLARITY',primaryDestinations:['종목','뉴스','성적','진화'],tests:n('tests'),passed:n('pass'),failed:0,assets:b.input.assets.length,actualAsOf:b.input.actualAsOf,originalSHA:sha(JSON.stringify(b.original)),preservedForecasts:Object.keys(before.versions).length,currentForecasts:versions.size,releaseDataAndEngineUnchanged:release?true:null,pixelBrowserVerified:false,physicalDeviceVerified:false,liveDeployment:false,accuracyCertification:false};
fs.writeFileSync('reports/clarity/validation.json',JSON.stringify(report,null,2));if(release)fs.writeFileSync('reports/clarity/release-validation.json',JSON.stringify(report,null,2));
const body=`# ATLAS 8.5 — 보기와 사용 순서 정리\n\n종목 선택 → 그래프 확인 → 날짜별 이유 → 실제 결과 비교의 순서로 첫 화면을 정돈했습니다. 8.4의 색·마크·서체를 유지하고 정보 구조를 개편한 릴리스입니다.\n\n## 실제 변경\n- 주요 메뉴8개를 종목·뉴스·성적·진화4개로 정리했습니다. 예정·돌발 뉴스는 뉴스 안에서 전환합니다. 관심종목은 종목 목록 필터에 있습니다.\n- 헤더의 조작 버튼4개를 계정·설정자료2개로 줄였습니다. 계산·갱신·방정식·운영 기록은 설정·자료 대화상자에 모았습니다.\n- 종목 선택 입구의 반복을 제거했습니다. 클릭 선택을 먼저 보이고 검색은 필요할 때 펼칩니다.\n- 52종목 그래프와9/17~10/30 전체 경로를 처음부터 표시합니다. 기본 카드에서는 재생·이유 보기·관심 등록을 바로 누릅니다. 날짜·속도·표시 설정·연구자료는 날짜·설정·근거에서 펼칩니다.\n- 집중 보기의 그래프 왼쪽·설명 오른쪽·조작 아래는 유지합니다. 종목별 하루1초·독립 날짜와 중요 뉴스마다 멈춤을 유지합니다. 설명은 먼저 요약, 이어서 펼치는 날짜별 근거·계산값 순서입니다. 필터를 바꿀 때도 재생을 정지해 보이지 않는 카드가 계속 움직이지 않게 합니다.\n- 긴 소개와 반복 안내를 접고 가격 기준·연구용·방향 유보는 바로 확인하게 했습니다. 자료 기준과 적중 확률 미검증 설명을 숨기거나 성공 배지로 바꾸지 않았습니다.\n- 데스크톱은 간결한 가로 탐색, 휴대폰은 네 메뉴가 모두 보이는 하단 탐색입니다. 계산/기록 화면에는 종목으로 돌아가는 버튼이 있습니다. 이전 기록 보기의 오래된 overview 경로도 종목 화면으로 수정했습니다.\n\n## 이용 순서\n1. 종목 화면에서 카드를 고르거나52종목에서 선택을 누릅니다.\n2. 카드의 이유 보기 또는 그래프 날짜를 눌러 집중 보기를 엽니다.\n3. 재생 중 중요 뉴스에서 멈추면 설명을 읽고 확인 후 계속합니다.\n4. 뉴스에서 예정 일정과 돌발 사건을 따로 확인합니다.\n5. 성적에서 실제와의 차이, 진화에서 별도 개선안과 기록을 확인합니다.\n\n## 보존과 검증\n최종 자동 검사${report.tests}개 통과·실패0. 같은 검사 안에서 새 네 메뉴, 예정/돌발 뉴스의 관계, 설정·자료의 네 기능, 모달 초점 복귀, 접힌 자료와 항상 보이는 전체 그래프, 관심종목·종목별 재생·연속 중요 뉴스·Worker 계산을 확인했습니다. 기존 메뉴 개수/버튼 위치 기대를 새 구조에 맞춰 갱신했습니다. 전체 검사에서 발견한 기존 시각 의존 테스트2건에는 정정 관측시각과 사전 발행시각을 명시해 실행날짜에 따라 기대가 달라지지 않게 했습니다. 실패 기록을 보존하고 원본 보존·계산·중요 뉴스 정지·사전 발행 요건은 유지했습니다.\n\n기존${report.preservedForecasts}개 발행 전망,${report.assets}개 고유 종목, 전체 입력과 모든 기존lib 및 차트 좌표 코드를 보존했습니다. 보관 공통 종가는${report.actualAsOf}. 디자인 작업으로 새 가격을 수집하거나 예측 정확도가 개선됐다고 주장하지 않습니다. 최초 재구성본 SHA: ${report.originalSHA}.\n\n개발 릴리스 전체 불변 검사는 reports/clarity/release-validation.json에 보관합니다. 일상 갱신은 새 입력과 전망 추가를 허용하며 --release 검사를 과거 입력 불변 인증으로 재사용하지 않습니다.\n\n실제 브라우저 픽셀·휴대폰 검수는 접근 환경 제한으로 미완료입니다. 자동 DOM/CSS 검사는 실제 줄바꿈·손가락 조작·사용성 관찰을 대신하지 않습니다. 8.4의365개 제작장부는 당시 기록으로 유지하며 전부 완료로 승격하지 않습니다.\n\n## 다운로드와 배포\nATLAS_Evolution_Netlify.zip은 정적 수동 배포용입니다. 압축을 풀고 index.html이 바로 있는 폴더를 올립니다. ATLAS_Netlify.zip에는 전체 소스와 서버 코드가 있습니다. 실제 사이트 배포·서버 자동 수집·Google 로그인 연결은 이번 작업에서 수행하지 않았습니다.\n`;
fs.writeFileSync('public/downloads/ATLAS_UX_85.md',body);
for(const file of ['README.md','VALIDATION.md']){const old=read(file),mark='\n<!-- CLARITY85_HISTORY -->\n',history=old.includes(mark)?old.split(mark).slice(1).join(mark):old;fs.writeFileSync(file,body+mark+history);}
console.log(JSON.stringify(report));
