import fs from'node:fs/promises';import{gunzipSync}from'node:zlib';import{createHash}from'node:crypto';
const read=async p=>{try{return JSON.parse(await fs.readFile(p,'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}};
const wave=JSON.parse(gunzipSync(await fs.readFile('public/data/news-wave.json.gz'))),input=wave.displayContext.input,registry=await read('public/data/factor36-registry.json'),at=new Date().toISOString();
const summaries=await Promise.all(['market','flows','company'].map(n=>read('reports/completion/'+n+'-summary.json'))),fomoReport=await read('reports/completion/fomo-latest.json'),operation=await read('reports/completion/operations/latest.json'),scheduler=await read('reports/completion/scheduler.json');
const quoteRows=(fomoReport?.priceObservations??[]).flatMap(o=>['F23'].map(factorId=>({factorId,targetCodes:[o.code],sourceVerified:true,componentOnly:true,count:o.rows.length,historyStart:o.rows[0]?.date,historyEnd:o.rows.at(-1)?.date,collectorStatus:o.rows.some(r=>r.date===input.actualAsOf)?'ready':'partial',sources:[{url:o.sourceUrl,rawHash:o.rawHash,observedAt:o.observedAt}],blockers:['거래량·거래대금·OHLC 원자료 확보. 장기 가격 충격 계수·호가·당시 빈티지는 미확보']})));
const rows=[...summaries.flatMap(s=>[...(s?.factors??s?.perFactor??[]),...(s?.additionalSharedFactor?[s.additionalSharedFactor]:[])]),...quoteRows],state=(status,reason,extra={})=>({status,reason,...extra});
const targets=(r,code)=>r.targetCodes==='all52'||r.targetCodes==='all'||r.scope==='market'||r.targetCodes?.includes?.(code)||r.codes?.includes?.(code);
const sources=r=>(r.sources??[]).map(s=>({url:s.url??s.sourceUrl,title:s.title??s.name,rawHash:s.rawHash??s.sha256,observedAt:s.observedAt}));
const stocks=input.assets.map(a=>{
  const model=wave.candidate.assets.find(x=>x.code===a.code),fomo=fomoReport?.stocks52?.find(x=>x.code===a.code);
  return {code:a.code,name:a.name,sector:a.sector,factors:registry.factors.map(f=>{
    const evidence=rows.filter(r=>(r.factorId??r.id)===f.id&&(targets(r,a.code)||(!r.sourceVerified&&!(r.targetCodes?.length)))),used=['conditional_mean','variance'].includes(model.factorModel.factors.find(x=>x.id===f.id)?.role),core=['F11','F35','F36'].includes(f.id);
    const ready=evidence.filter(r=>r.sourceVerified===true&&!r.componentOnly),partial=evidence.filter(r=>r.sourceVerified===true&&r.componentOnly),allSources=evidence.flatMap(sources);
    const count=evidence.reduce((n,r)=>n+(r.byCodeCount?.[a.code]??r.count??r.observationCount??0),0),blockers=evidence.flatMap(r=>r.blockers??[]).join(' · '),reason=blockers||evidence.map(r=>r.reason??r.statusReason).filter(Boolean).join(' · ')||'원자료·당시 공개 이력 미확보';
    const rawStatus=ready.length?'ready':partial.length||core?'partial':'missing';
    const historyCount=core?a.prices.length:count,historyFirst=core?a.prices[0]?.date:evidence.map(r=>r.historyStart).filter(Boolean).sort()[0],historyLast=core?a.prices.at(-1)?.date:evidence.map(r=>r.historyEnd).filter(Boolean).sort().at(-1);
    return {id:f.id,name:f.name,
      rawSource:state(rawStatus,core?'가격 이력에서 계산한 대용 성분. 공식 시장·업종 통제/갭·기업행위 검증을 모두 확보한 완성 요인은 아님':reason,{count:historyCount,sources:allSources.length?allSources:core?[{url:a.priceSource?.url,title:'보관 NAVER 단일 제공자 가격',rawHash:wave.sourceSHA256,observedAt:input.retrievedAt}]:[]}),
      collector:state(evidence.some(r=>r.collectorStatus==='ready'||r.collectorStatus==='success'||r.collectorStatus==='official_xlsx_download_and_read_success')?'ready':evidence.some(r=>String(r.collectorStatus).includes('partial')||r.collectorStatus==='official_market_summary_success_history_error')?'partial':core?(quoteRows.some(r=>r.targetCodes.includes(a.code))?'partial':'failed'):'blocked',core?'보관 종가와 최근 일부 OHLCV 대조. 장기 빈티지 검증과 별개':reason),
      history:state(historyCount>0?'partial':'missing',historyCount>0?'실제 관측 이력 존재. 당시 빈티지·공개시각·계수 추정 적격성 별도 확인 필요':reason,{count:historyCount,firstDate:historyFirst,lastDate:historyLast}),
      calculation:state(used?'ready':'excluded',used?model.factorModel.factors.find(x=>x.id===f.id).reason:(model.factorModel.externalRejected?.find(x=>x.factorId===f.id)?.reason??'원자료 전체 요건/시점별 연속 이력/추가 예측력 미확보로 수치 가산 제외')),
      ui:state('ready',used?'동일 발행본의 종목별 그래프·52개 비교·순위·날짜 설명·성적에 연결':'미확보·부분자료·제외 이유를 현재 발행본에 연결'),
      validation:state('partial',used?'후향적 수학·기능 검사 대상. 실전 예측 우위·조정 빈티지 미검증':'원문·형식 검사를 가격 예측력 검증으로 세지 않음')};
  }),fomo:{score:fomo?.fullFomoScore??null,partialMetric:{name:'종가 기반 가격 열기 · FOMO 전체 점수 아님',score:fomo?.priceHeat??null,reason:'관심도·개인 수급 미확보. 가격에서 계산된 설명용 부분지표이며 가격 예측에 가산하지 않음'},asOf:fomoReport?.cutoffDate??null,
    rawSource:state(fomo?.fullFomoScore!=null?'ready':fomo?.subindices&&Object.values(fomo.subindices).some(x=>x!=null)?'partial':'missing',(fomo?.missing??['관심도·개인 수급·거래량/거래대금 검증 원자료 미확보']).join(' · ')),
    collector:state(fomo?.priceStatus==='success'?'partial':'blocked','NAVER 데이터랩 인증·허가된 개인수급 자료가 필요. 공급자 요청 실패 기록 보존'),
    history:state('missing','과거 10거래일 핵심 관측의 연속성 및 장기 검증 이력 미확보'),
    calculation:state(model.waveModel.fomo.enabled?'ready':'excluded',model.waveModel.fomo.reason),ui:state('ready','점수 미산출/부분 지표를 그대로 표시'),validation:state('partial','입력·누수·결측 검사를 수행. 실제 FOMO 가격 반응 검증 미완료')}};
});
const factors=registry.factors.map(f=>({id:f.id,name:f.name,rawSourceStocks:stocks.filter(s=>s.factors.find(r=>r.id===f.id).rawSource.status==='ready').length,partialSourceStocks:stocks.filter(s=>s.factors.find(r=>r.id===f.id).rawSource.status==='partial').length,usedStocks:stocks.filter(s=>s.factors.find(r=>r.id===f.id).calculation.status==='ready').length}));
const summary={expectedStocks:52,matrixCells:52*36,stageCells:52*37*6,factorTypesWithRawSource:factors.filter(f=>f.rawSourceStocks>0).length,componentSourceFactorTypes:factors.filter(f=>f.partialSourceStocks>0).length,factorTypesUsed:factors.filter(f=>f.usedStocks>0).length,fomoComputedStocks:stocks.filter(s=>s.fomo.score!==null).length,collectedStocks:new Set((fomoReport?.priceObservations??[]).filter(o=>o.rows?.some(r=>r.date===fomoReport.cutoffDate)).map(o=>o.code)).size,calculationConnections:factors.reduce((n,f)=>n+f.usedStocks,0),displayConnections:52*37};
const report={schema:'atlas-completion-status-1',forecastId:wave.id,generatedAt:at,actualAsOf:input.actualAsOf,period:[input.origin,input.end],summary,factors,stocks,operation:{serverInstalled:false,schedulerInstalled:scheduler?.confirmed===true,lastRunAt:operation?.at??null,lastRunStatus:operation?.status??'not_run',reason:'예약은 ZIP 갱신 작업에 연결. 정적 Netlify 배포만으로 실시간 서버 수집은 설치되지 않음. 마지막 정상 종가와 부분 실패 유지.'},complete:false};
const body=JSON.stringify(report),hash=createHash('sha256').update(body).digest('hex');await fs.mkdir('reports/completion/status',{recursive:true});await fs.writeFile('reports/completion/status/'+hash+'.json',body);await fs.writeFile('public/data/completion-status.json',body);
const csv=['code,name,factor,rawSource,collector,history,calculation,ui,validation',...stocks.flatMap(s=>[...s.factors,{...s.fomo,id:'FOMO'}].map(f=>[s.code,s.name,f.id,...['rawSource','collector','history','calculation','ui','validation'].map(k=>f[k].status)].join(',')))].join('\n');await fs.writeFile('public/downloads/ATLAS_52_FACTOR_STATUS.csv','\ufeff'+csv);console.log(JSON.stringify({summary,forecastId:wave.id,complete:false}));
