import fs from 'node:fs';import {createHash} from 'node:crypto';
const sha=v=>createHash('sha256').update(v).digest('hex'),read=p=>fs.readFileSync(p,'utf8');
for(const [p,h]of Object.entries(JSON.parse(read('reports/fomo-v2/before.json'))))if(sha(fs.readFileSync(p))!==h)throw Error('Preserved input/engine changed: '+p);
const r=JSON.parse(read('reports/fomo-v2/latest.json')),tap=read('reports/tests.tap'),count=k=>Number(tap.match(new RegExp('# '+k+' (\\d+)(?:\\s|$)'))?.[1]);
if(!count('tests')||count('tests')!==count('pass')||count('fail'))throw Error('Final tests incomplete');
const unit=read('reports/fomo-v2/latest-unit.tap');const unitCount=k=>Number(unit.match(new RegExp('# '+k+' (\\d+)(?:\\s|$)'))?.[1]);if(!unitCount('tests')||unitCount('tests')!==unitCount('pass')||unitCount('fail'))throw Error('FOMO targeted tests incomplete');
const browser=JSON.parse(read('reports/fomo-v2/browser/browser.json'));if(!browser.passed)throw Error('Browser validation failed');
const finalTap=read('reports/fomo-v2/final-targeted.tap'),fc=k=>Number(finalTap.match(new RegExp('(?:#|ℹ) '+k+' (\\d+)'))?.[1]);if(!fc('tests')||fc('pass')!==fc('tests')||fc('fail'))throw Error('Final targeted tests incomplete');
const equalBrowser=JSON.parse(read('reports/fomo-v2/browser/equal-final.json'));if(!equalBrowser.passed)throw Error('Final equal-start browser failed');
const movement=JSON.parse(read('reports/daily-movement/latest.json'));
const report={finalEqualBrowser:{checks:equalBrowser.checks.length,passed:equalBrowser.passed},equalStart:{assets:52,initialWon:10000,calendarDays:44,tickMs:1000,newsEnergy:'max_existing_per_event_distribution_change_pp',fomoPriceImpactEnabled:false},finalTargeted:{tests:fc('tests'),pass:fc('pass'),fail:fc('fail')},dailyMovement:{id:movement.id,assets:movement.summary.length,stocksWithTurns:movement.summary.filter(x=>x.turns>0).length,accuracyValidated:false},fullSuiteScope:'FOMO implementation before separate daily-movement addition; final targeted tests cover new changes',targetedFomo:{tests:unitCount('tests'),pass:unitCount('pass'),fail:unitCount('fail'),overlapsFullSuite:true},browser:{checks:browser.checks.length,passed:browser.passed,physicalDevice:false},collectionReused:r.collectionReused,version:'9.1.0',at:new Date().toISOString(),assets:52,actualAsOf:r.actualAsOf,coreFomoAvailable:r.complete,collection:r.collection,tests:count('tests'),pass:count('pass'),fail:count('fail'),originalAndAllForecastsUnchanged:true,sourceSHA256:r.sourceSHA256,priceImpactEnabled:false,accuracyValidated:false,liveDeployed:false,pending:['검색 API 인증','공식 개인 수급 원자료','연결 가능한 가격 원문','당시 원본·기업행위 검증','독립 향후 검증과 일별 상태 전이 계수 근거']};
fs.writeFileSync('reports/fomo-v2/validation.json',JSON.stringify(report,null,2));
const text=`# ATLAS 9.1 — FOMO 핵심 관측·수집·연구 검증\n\n52개 원래 종목·모든 기존 전망·가격 엔진을 보존했습니다. 핵심 6항목의 관심/참여/추격을 기하평균으로 계산하고 과열 위치를 따로 표시합니다. 선택 자료인 작성자 수가 없어도 핵심 자료가 있으면 점수를 계산합니다. 확률이 아닌 관측 지수입니다.\n\n## 일별 등락 연구 추가\n52종목의 1·2·5·20·60거래일 반응을 사용하는 별도 연구 전망을 저장했습니다. 날짜별 변화값·하루 상승/하락 모형 비율·하루 변동 범위를 제공합니다. 기존 전망과 겹치지 않고 「일별 등락 연구 보기」로 같은 그래프를 전환합니다. 원래 발행본과 과거 채점은 그대로입니다. 자세한 방식은 ATLAS_DAILY_MOVEMENT.md를 참조합니다. 방향과 변동 폭의 실제 적중 우위는 아직 검증되지 않았습니다.\n\n## 1만원 출발 페이지\n상단 1만원 탭에 동일 9/17 출발·52종목 순위·44일 1초 재생·종목별 뉴스 영향순 목록을 추가했습니다. 기존 뉴스 영향값을 재사용하며 중복 가산하지 않습니다. FOMO 포함 결합 순위는 입력과 계수 검증 부족으로 미완성이라고 표시합니다. 자세한 방정식과 구분은 ATLAS_EQUAL_START.md를 참조합니다.\n\n## 실제 결과\n- 종가 기준 ${r.actualAsOf}. 완전한 핵심 FOMO ${r.complete}/52종목.\n- 가격 원문 성공 ${r.collection?.priceSuccess??0}, 실패 ${r.collection?.priceFailed??0}, 회로 차단 유보 ${r.collection?.priceDeferred??0}.\n- 검색 인증 미설정 ${r.collection?.searchNotConfigured??52}종목. 개인 수급 원자료 미확보.\n- FOMO 구현 단계 전체 회귀 검사 ${report.tests}개 통과. 이후 일별 등락 추가 변경의 최종 대상 검사 ${report.finalTargeted.tests}개 통과. 검사 수는 주가 적중 검증 횟수가 아닙니다.\n- FOMO에 의한 실제 예측 보정 0종목. 기존 데이터 SHA256 ${r.sourceSHA256}.\n\n## 구현된 것\n자료별 출처·단위·원문 해시·공개/관측/기록 시각 검증(원문 공개 시각 미확보 시 publishedAt=null과 관측 가능 시각만 기록), 다중 출처 보조 입력, 충돌 거부, 검색 요청별 척도 분리, 핵심 지수·과열 표시, 종목별 정규화 잔차 회귀와 비중복 시간순 시험, 일별 가격·상태 전이 연구 경로, 52종목 수집 상태·실패 기록, 원본 불변 검사. npm run refresh가 정상 갱신 저장 후 FOMO 수집·연구 기록도 실행합니다.\n\n## 실행\n서버에서 npm run fomo:collect를 실행합니다. NAVER_CLIENT_ID 및 NAVER_CLIENT_SECRET은 서버 환경에만 설정하며 배포 파일에 넣지 않습니다. 인증 없이 검색은 not_configured로 남습니다. 정상 프록시·공개 접근 범위만 사용합니다.\n개인 수급은 공식 자료를 atlas-fomo-records-2 규격으로 준비하여 node scripts/research_fomo_v2.mjs --import 파일.json으로 후보에 병합합니다. 화면의 종목별 원자료 추가도 같은 규격을 지원합니다. 값 충돌은 거부하며 원본을 덮지 않습니다.\n과거 학습행은 --training 파일.json 옵션입니다. code/date/targetDate/issuedAt/observedAt/horizon/featureVersion/vector/baseLogReturn/actualLogReturn/pointInTimeVerified/adjustmentsVerified가 필요합니다. 시점 검증 플래그는 입력자의 근거 선언이며 독립 인증이 아닙니다. 모형 계수는 연구용에만 저장합니다.\n부분 실패는 종료 코드 2입니다. 매번 reports/fomo-v2/runs에 별도 기록하며 새 자료는 input-candidate.json에 보관합니다. 운영 가격 파일을 자동 교체하지 않습니다.\n\n## 아직 못 마친 것\n자료가 없어 52종목 실제 FOMO·학습 계수·독립 검증 성적은 생성할 수 없었습니다. 종목별 고정 지평 회귀와 가격·관심 상태의 결합 일별 경로 계산도 구현했습니다. 일별 경로는 60개 이상 적격 학습행이 있어야 연구용으로 생성하며, 상태·가격 잔차를 함께 블록 재표집합니다. 실제 계수 근거·범위 보정 성적·실전 승격은 미확보입니다. 경로 모형은 종목별 연구용이며 52종목 공동 충격·상관 구조의 검증은 아직 하지 않았습니다. 따라서 10/30까지 그래프에 임의 보정선을 넣지 않았습니다. 검색 인증만으로 개인 수급과 과거 원본 문제가 해결되는 것은 아닙니다.\n\n## 배포\nNetlify Drop용 ZIP은 정적 화면입니다. 압축을 풀어 index.html 폴더를 업로드합니다. 서버 수집은 전체 소스와 서버 환경이 필요하며, 이번 작업으로 계정 배포나 자동 서버 실행이 설치된 것은 아닙니다.\n`;
const table='\n## 52종목 현재 상태\n\n| 종목 | 핵심 자료 | FOMO 지수 | 가격 열기 | 예측 반영 |\n|---|---:|---:|---:|---|\n'+r.observations.map(o=>`| ${o.name} (${o.code}) | ${o.coverage}/6 | ${o.score===null?'미확보':o.score.toFixed(1)} | ${o.priceHeat===null?'미확보':o.priceHeat.toFixed(1)} | 유보 |`).join('\n')+'\n';
fs.writeFileSync('public/downloads/ATLAS_FOMO_V2.md',text+table);fs.writeFileSync('public/downloads/FOMO_V2_VALIDATION.json',JSON.stringify(report,null,2));
for(const p of ['README.md','VALIDATION.md']){const old=read(p),marker='\n<!-- FOMO_V2_HISTORY -->\n';fs.writeFileSync(p,text+marker+(old.includes(marker)?old.split(marker).slice(1).join(marker):old));}
console.log(JSON.stringify(report));
