import React,{useMemo,useState} from 'react';
/** Manual, append-only breaking-news UI. It never assigns an impact or modifies a forecast.
 * onAction('breakingRecord',{event}) / onAction('breakingDecision',{eventId,code,decision,reason}). */
const number=(n:any)=>typeof n==='number'&&Number.isFinite(n);
const won=(n:any)=>number(n)?`${n>0?'+':''}${Math.round(n).toLocaleString('ko-KR')}원`:'미산정';
const time=(s:any)=>{const n=Date.parse(s);return Number.isFinite(n)?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(n))+' 한국시간':'시각 미확보';};
const localTime=(s:any)=>Number.isFinite(Date.parse(s))?new Date(Date.parse(s)+9*3600000).toISOString().slice(0,16):'';
const safeUrl=(s:any)=>typeof s==='string'&&/^https?:\/\//i.test(s);
const labels:Record<string,string>={KEEP:'유지',WATCH:'관찰',SCENARIO:'시나리오 검토',REVISE:'변경 검토',BLOCK:'반영 차단'};
const statusLabels:Record<string,string>={reported:'등록',confirmed:'사용자가 확인으로 기록',corrected:'정정',retracted:'철회'};
const observedByNow=(r:any)=>{const close=Date.parse(`${r.date}T15:30:00+09:00`),observed=r.observedAt??r.retrievedAt;return Number.isFinite(close)&&close<=Date.now()&&(!observed||(Number.isFinite(Date.parse(observed))&&Date.parse(observed)<=Date.now()));};
const reasonLabels:Record<string,string>={NO_REVIEWED_IMPACT_EVIDENCE:'가격 변경에 필요한 검토 자료가 없습니다.',FEWER_THAN_FIVE_INDEPENDENT_EVENT_GROUPS:'서로 독립적인 과거 사건이 최소 5개 필요합니다.',EVENT_NOT_CONFIRMED:'사건의 확인 상태를 더 검토해야 합니다.',EVENT_STATUS_NOT_REVIEWED:'확인·정정 상태의 사건 근거가 필요합니다.',EVENT_SOURCE_BODY_NOT_REVIEWED:'원문 본문을 읽고 기록한 근거가 부족합니다.',EVENT_REVISION_SOURCE_REVIEW_MISSING:'현재 정정본에 맞는 원문 검토 기록이 없습니다.',ADJUSTMENT_OR_EXPECTATION_UNVERIFIED:'기업행위 조정 가격 또는 발표 전 기대 자료가 확인되지 않았습니다.',IMPACT_STOCK_OR_PHASE_MISMATCH:'검토 자료의 종목 또는 사건 단계가 다릅니다.',NO_INDEPENDENT_SAMPLES:'사용 가능한 독립 과거 표본이 없습니다.',EVENT_ALREADY_INCLUDED_IN_BASELINE:'이 사건이 기준 전망에 이미 포함되어 있습니다.',BASELINE_INCLUSION_REVIEW_MISSING_OR_STALE:'기준 전망의 기존 반영 여부를 다시 확인해야 합니다.',OTHER_PHASE_OVERLAP_REVIEW_MISSING:'같은 사건의 다른 단계와 중복되는지 확인이 필요합니다.',RESIDUAL_EVOLUTION_OVERLAP_UNRESOLVED:'기존 진화 보정과 같은 반응을 이중 반영할 가능성이 남아 있습니다.',SOURCE_REVIEW_PROVENANCE_MISSING:'실제로 확인한 원문의 보존 기록이 부족합니다.',PRE_EVENT_EXPECTATION_MISSING:'발표 전에 알려진 기대 자료가 부족합니다.',OVERLAPPING_EVENTS_NOT_EXCLUDED:'겹친 사건의 영향을 분리하지 못했습니다.',RESIDUAL_NOT_REPRODUCIBLE_FROM_EVIDENCE:'입력한 반응값이 근거 가격과 기대값으로 재현되지 않습니다.',NUMERIC_RANGE_LIMIT:'계산 가능한 숫자 범위를 벗어났습니다.',FIXED_PERIOD_ENDED:'고정된 예측 기간이 끝났습니다.'};
const readableReason=(value:any)=>{let text=typeof value==='string'?value:JSON.stringify(value);for(const [key,label] of Object.entries(reasonLabels))text=text.replaceAll(key,label);return /^[A-Z][A-Z0-9_]+(?::|$)/.test(text)?'추가 검토 요건이 충족되지 않았습니다. 상세 검사 코드를 확인하세요.':text;};
const emptyDraft=(code:string)=>({title:'',summary:'',sourceUrl:'',publishedAt:'',sourceType:'unverified',sourceBodyReviewed:false,economicEventId:'',phaseId:'',scope:'company',targetCodes:[code],businessPath:'',changeToPremise:'',importance:'normal',status:'reported',supersedesId:''});
function BreakingPriceChart({asset,baseline,forecast,input}:any){
  const start='2026-09-17',end='2026-10-30',dates:string[]=[];
  for(let t=Date.parse(start+'T00:00:00Z');t<=Date.parse(end+'T00:00:00Z');t+=86400000)dates.push(new Date(t).toISOString().slice(0,10));
  const sessions=new Set(input.calendar?.sessions??[]);
  const actual=(asset?.prices??[]).filter((r:any)=>r.date>=start&&r.date<=end&&observedByNow(r)&&sessions.has(r.date)&&number(r.close)&&r.close>0&&r.quality!=='conflict'&&(asset.prices??[]).filter((x:any)=>x.date===r.date).length===1);
  const base=(baseline?.rows??[]).filter((r:any)=>dates.includes(r.date)&&number(r.p50)&&r.p50>0);
  const changed=(forecast?.rows??[]).filter((r:any)=>forecast.effectiveFrom&&r.date>=forecast.effectiveFrom&&dates.includes(r.date)&&number(r.p50)&&r.p50>0);
  const displayed=forecast?changed:base;
  const all=[...actual.map((r:any)=>r.close),...displayed.map((r:any)=>r.p50)];
  if(!all.length)return <p>비교할 저장 가격이 없습니다.</p>;
  const W=1000,H=280,L=82,R=24,T=20,B=36,min=Math.min(...all),max=Math.max(...all),pad=Math.max(1,(max-min)*.1,max*.02),lo=min-pad,hi=max+pad;
  const x=(d:string)=>L+dates.indexOf(d)*(W-L-R)/(dates.length-1),y=(v:number)=>T+(hi-v)/(hi-lo)*(H-T-B);
  const path=(rows:any[],field:string)=>rows.map((r:any,i:number)=>`${i?'L':'M'}${x(r.date)},${y(r[field])}`).join(' ');
  return <svg className="breaking-price-chart" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`${asset?.name}의 선택한 저장 전망 하나와 실제 종가 비교`} data-breaking-chart>
    {[0,.5,1].map(t=><g key={t}><line x1={L} x2={W-R} y1={T+t*(H-T-B)} y2={T+t*(H-T-B)} className="breaking-chart-grid"/><text x={L-10} y={T+t*(H-T-B)+4} textAnchor="end">{Math.round(hi-t*(hi-lo)).toLocaleString('ko-KR')}</text></g>)}
    <path d={path(displayed,'p50')} className={forecast?"breaking-chart-change":"breaking-chart-baseline"} data-breaking-displayed-forecast data-breaking-effective-from={forecast?.effectiveFrom??''}/>
    <path d={path(actual,'close')} className="breaking-chart-actual"/>
    {actual.map((r:any)=><circle key={r.date} cx={x(r.date)} cy={y(r.close)} r="3" className="breaking-chart-dot"><title>{`${r.date} 실제 종가 ${Math.round(r.close).toLocaleString('ko-KR')}원`}</title></circle>)}
    {forecast?.effectiveFrom&&dates.includes(forecast.effectiveFrom)&&<line x1={x(forecast.effectiveFrom)} x2={x(forecast.effectiveFrom)} y1={T} y2={H-B} className="breaking-chart-start"/>}
    {[start,'2026-10-01','2026-10-15',end].map(d=><text key={d} x={x(d)} y={H-10} textAnchor="middle">{d.slice(5).replace('-','/')}</text>)}
  </svg>;
}
export function BreakingWorkbench({state,selectedVersion,onAction}:any){
  const assets=state.input.assets??[],breaking=state.breaking??{events:[],decisions:[],forecasts:[],evaluations:[],premises:[]};
  const [code,setCode]=useState(assets[0]?.code??''),[selectedId,setSelectedId]=useState(''),[forecastId,setForecastId]=useState('operating'),[formOpen,setFormOpen]=useState(false),[draft,setDraft]=useState(()=>emptyDraft(assets[0]?.code??'')),[decision,setDecision]=useState('WATCH'),[reason,setReason]=useState(''),[impactJson,setImpactJson]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const asset=assets.find((a:any)=>a.code===code)??assets[0];
  const events=useMemo(()=>[...(breaking.events??[])].filter((e:any)=>e.targetCodes?.includes(code)).sort((a:any,b:any)=>String(b.knownAt??b.discoveredAt).localeCompare(String(a.knownAt??a.discoveredAt))||String(b.id).localeCompare(String(a.id))),[breaking.events,code]);
  const selected=events.find((e:any)=>e.id===selectedId)??events[0];
  const stockDecisions=[...(breaking.decisions??[])].filter((d:any)=>d.code===code).sort((a:any,b:any)=>String(b.issuedAt).localeCompare(String(a.issuedAt)));
  const eventDecisions=stockDecisions.filter((d:any)=>d.eventId===selected?.id);
  const latest=eventDecisions[0];
  const successor=selected?(breaking.events??[]).find((e:any)=>e.supersedesId===selected.id):null;
  const premises=(breaking.premises??[]).filter((p:any)=>p.code===code||p.targetCodes?.includes(code));
  const stockForecasts=(breaking.forecasts??[]).filter((f:any)=>f.code===code||f.assets?.some((a:any)=>a.code===code));
  const activeForecast=stockForecasts.find((f:any)=>f.id===forecastId)??[...stockForecasts].sort((a:any,b:any)=>String(b.issuedAt).localeCompare(String(a.issuedAt)))[0];
  const versions=state.versions??[state.original,...(state.priorVersions??[]),state.candidate].filter((v:any)=>v&&typeof v==='object');
  const forecastReplacement=(breaking.forecasts??[]).find((f:any)=>f.replacesForecastId===activeForecast?.id);
  const forecastEventSuperseded=activeForecast&&(breaking.events??[]).some((e:any)=>e.supersedesId===activeForecast.eventId);
  const baselineVersion=versions.find((v:any)=>v.id===activeForecast?.baselineId)??versions.at(-1);
  const baselineAsset=activeForecast?.sourceOriginal?.asset??baselineVersion?.assets?.find((a:any)=>a.code===code);
  const operatingVersion=selectedVersion??versions.find((v:any)=>v.id===state.active)??versions.at(-1);
  const displayedForecast=forecastId==='operating'?null:activeForecast;
  const displayedBaseline=displayedForecast?baselineAsset:operatingVersion?.assets?.find((a:any)=>a.code===code);
  const evaluations=[...(breaking.evaluations??[])].filter((r:any)=>r.code===code&&number(r.actual)&&number(r.errorWon)&&number(r.baselineErrorWon));
  // Display recorded pairs only; do not estimate outcomes for an event with no result.
  const pairMap=new Map<string,any>();for(const r of evaluations){const key=`${r.forecastId??r.versionId??r.id}:${r.date}`;const old=pairMap.get(key);if(!old||String(r.recordedAt)>String(old.recordedAt))pairMap.set(key,r);}
  const pairs=[...pairMap.values()],uniqueDates=new Set(pairs.map((r:any)=>r.date)).size;
  const candidates=(breaking.candidates??[]).filter((c:any)=>c.code===code);
  const collection=breaking.collectionStatus?.at(-1);
  const fromCandidate=(candidate:any)=>{setDraft({...emptyDraft(candidate.code),title:candidate.title??'',sourceUrl:candidate.url??''});setFormOpen(true);setNotice('수집 후보를 입력창에 옮겼습니다. 공개 시각·대상 기업·원문을 직접 확인한 뒤 등록하세요. 아직 승인된 사건이 아닙니다.');};
  const update=(k:string,value:any)=>setDraft(d=>({...d,[k]:value}));
  const newEvent=()=>{setDraft(emptyDraft(code));setFormOpen(true);setNotice('');};
  const amend=()=>{if(!selected)return;setDraft({...emptyDraft(code),...selected,publishedAt:localTime(selected.publishedAt),sourceBodyReviewed:false,status:'corrected',supersedesId:selected.id,targetCodes:[...selected.targetCodes]});setFormOpen(true);setNotice('이전 기록은 보존합니다. 정정 내용을 새 기록으로 저장하세요.');};
  const save=async(e:React.FormEvent)=>{e.preventDefault();if(!onAction||busy)return;setBusy(true);setNotice('');try{const url=new URL(draft.sourceUrl);if(url.protocol!=='https:')throw Error('출처는 HTTPS 원문 URL이어야 합니다.');if(!draft.targetCodes.length)throw Error('대상 종목을 한 개 이상 선택하세요.');const publishedAt=new Date(`${draft.publishedAt}${draft.publishedAt.length===16?':00':''}+09:00`).toISOString();const event={title:draft.title.trim(),summary:draft.summary.trim(),sourceUrl:draft.sourceUrl.trim(),publishedAt,sourceType:draft.sourceType,sourceBodyReviewed:draft.sourceBodyReviewed,economicEventId:draft.economicEventId.trim(),phaseId:draft.phaseId.trim(),scope:draft.scope,targetCodes:draft.targetCodes,businessPath:draft.businessPath.trim(),changeToPremise:draft.changeToPremise.trim(),importance:draft.importance,status:draft.status,...(draft.supersedesId?{supersedesId:draft.supersedesId}:{})};await onAction('breakingRecord',{event});setFormOpen(false);setDraft(emptyDraft(code));setSelectedId('');setNotice('뉴스 기록을 저장했습니다. 공식 검증이나 가격 반영이 완료됐다는 뜻은 아닙니다.');}catch(e:any){setNotice(e.message??'등록하지 못했습니다. 입력 내용은 유지합니다.');}finally{setBusy(false);}};
  const decide=async(e:React.FormEvent)=>{e.preventDefault();if(!onAction||!selected||busy||successor)return;setBusy(true);setNotice('');try{let approvedImpact:any;if(decision==='REVISE'&&impactJson.trim()){try{approvedImpact=JSON.parse(impactJson);}catch{throw Error('검증 자료 JSON 문법을 확인하세요.');}if(!approvedImpact||typeof approvedImpact!=='object'||Array.isArray(approvedImpact))throw Error('검증 자료 JSON은 객체여야 합니다.');}await onAction('breakingDecision',{eventId:selected.id,code,decision,reason:reason.trim(),...(approvedImpact?{approvedImpact}:{})});setReason('');setNotice('판단 요청을 기록했습니다. 아래 실제 처리 결과와 유보 사유를 확인하세요.');}catch(e:any){setNotice(e.message??'판단을 저장하지 못했습니다.');}finally{setBusy(false);}};
  return <section className="breaking-workbench" data-breaking-workbench>
    <header className="breaking-heading"><div><span className="section-kicker">새 정보 · 전제 점검 · 별도 판단</span><h2>예정에 없던 뉴스가 나왔다면</h2><p>뉴스를 남기고, 어떤 전제가 달라졌는지 검토합니다. 기존 전망은 그대로 보존합니다.</p></div><button className="primary" onClick={newEvent}>돌발 뉴스 등록 ＋</button></header>
    <div className="breaking-mode"><b>수동 등록 창</b><span>실시간 감시 연결을 확인한 상태가 아닙니다. 등록된 뉴스 {breaking.events?.length??0}건 · 가격 반영과 별개</span></div>
    {notice&&<p className="breaking-notice" role="status">{notice}</p>}
    <details className="breaking-stock-picker"><summary>종목 선택 <b>{asset?.name}</b><span>{assets.length}종목 · 클릭해서 선택</span></summary><div className="breaking-stock-grid" role="group" aria-label="돌발 뉴스 종목">{assets.map((a:any)=><button key={a.code} data-breaking-code={a.code} aria-pressed={code===a.code} onClick={()=>{setCode(a.code);setSelectedId('');setForecastId('operating');}}><b>{a.name}</b><small>{a.sector} · {a.code}</small></button>)}</div></details>
    <div className="breaking-overview"><article><span>무슨 뉴스인가요?</span><b>{events.length}건</b><small>{asset?.name} 명시 대상</small></article><article><span>바뀐 전제 기록</span><b>{events.filter((e:any)=>e.changeToPremise).length}건</b><small>사용자 진술 · 인과 검증 아님</small></article><article><span>최근 처리</span><b>{stockDecisions[0]?labels[stockDecisions[0].decision]??stockDecisions[0].decision:'판단 전'}</b><small>{stockForecasts.length}개 별도 변경안 보관</small></article><article><span>변경 후 실제 비교</span><b>{pairs.length}건</b><small>{uniqueDates}개 고유 날짜 · 적중 확률 아님</small></article></div>
    <details className="breaking-candidates"><summary>수집 후보 검토 · {asset?.name} {candidates.length}건</summary><p>{collection?`최근 수집 연결: 성공 출처 ${collection.successfulSources??0} · 실패 ${collection.failedSources??0} · 유보 ${collection.deferredSources??0}. 일상 수집기의 후보 연결이며 실시간 감시가 아닙니다.`:'연결된 수집 실행 기록이 없습니다.'}</p>{candidates.length?<><p>제목·링크 후보입니다. 대상 회사 일치와 공개 시각은 등록 전 원문으로 확인해야 합니다.</p><div className="breaking-candidate-list">{candidates.map((c:any,i:number)=><button key={c.id??i} onClick={()=>fromCandidate(c)}><b>{c.title}</b><small>{c.url}</small><small>관측 {time(c.observedAt)} · 눌러서 검토 후 등록</small></button>)}</div></>:<p>이 종목의 검토 후보가 없습니다. 수집 실패·접근 제한 또는 미발견일 수 있으며, 돌발 뉴스가 없다는 뜻은 아닙니다.</p>}</details>
    {formOpen&&<section className="breaking-entry" aria-labelledby="breaking-form-title"><div className="breaking-entry-heading"><h3 id="breaking-form-title">{draft.supersedesId?'정정 기록 추가':'돌발 뉴스 등록'}</h3><button type="button" onClick={()=>setFormOpen(false)}>입력 닫기</button></div><p>뉴스가 사실인지, 가격에 영향을 주는지는 별도 검토가 필요합니다. 출처 종류와 원문 확인은 사용자가 입력한 상태로 저장됩니다.</p><form onSubmit={save} data-breaking-form>
      <label className="breaking-wide">뉴스 제목<input required maxLength={300} value={draft.title} onChange={e=>update('title',e.target.value)}/></label><label className="breaking-wide">확인한 내용과 아직 모르는 점<textarea required maxLength={5000} value={draft.summary} onChange={e=>update('summary',e.target.value)}/></label>
      <label className="breaking-wide">발표·기사 원문 HTTPS URL<input required type="url" placeholder="https://…" value={draft.sourceUrl} onChange={e=>update('sourceUrl',e.target.value)}/></label><label>공개 시각 · 한국시간<input required type="datetime-local" value={draft.publishedAt} onChange={e=>update('publishedAt',e.target.value)}/><small>원문 시각을 확인해 입력합니다. 등록 시각과 다릅니다.</small></label><label>출처 종류<select value={draft.sourceType} onChange={e=>update('sourceType',e.target.value)}><option value="unverified">확인되지 않음</option><option value="official">공식 발표라고 입력</option><option value="press">언론 보도</option></select></label>
      <label>같은 경제 사건 식별명<input required placeholder="예: 회사명-사건명-2026" maxLength={200} value={draft.economicEventId} onChange={e=>update('economicEventId',e.target.value)}/><small>다른 기사라도 같은 사건이면 같은 식별명</small></label><label>사건 단계 식별명<input required placeholder="예: 발표 / 정정 / 최종결정" maxLength={200} value={draft.phaseId} onChange={e=>update('phaseId',e.target.value)}/><small>발표와 결과 등 다른 단계는 구분</small></label>
      <label>적용 범위<select value={draft.scope} onChange={e=>update('scope',e.target.value)}><option value="company">기업</option><option value="sector">업종</option><option value="market">시장 공통</option><option value="index">지수 · 구성 근거 별도 필요</option></select></label><label>중요도<select value={draft.importance} onChange={e=>update('importance',e.target.value)}><option value="normal">일반</option><option value="important">중요 · 검토 우선</option></select></label>
      <details className="breaking-wide breaking-targets" open><summary>명시 대상 {draft.targetCodes.length}종목 · 자동 전체 적용 없음</summary><div>{assets.map((a:any)=><label key={a.code}><input type="checkbox" checked={draft.targetCodes.includes(a.code)} onChange={e=>update('targetCodes',e.target.checked?[...draft.targetCodes,a.code]:draft.targetCodes.filter((c:string)=>c!==a.code))}/>{a.name}</label>)}</div></details>
      <label className="breaking-wide">어떤 사업 경로로 연결되나요? · 선택<textarea maxLength={2000} placeholder="매출·비용·공급·수요 등 확인한 연결을 적습니다. 모르면 미확보로 남깁니다." value={draft.businessPath} onChange={e=>update('businessPath',e.target.value)}/></label><label className="breaking-wide">어떤 전제가 달라졌나요? · 선택<textarea maxLength={2000} placeholder="기존 가정과 달라진 내용, 확인할 근거를 구분해 적습니다." value={draft.changeToPremise} onChange={e=>update('changeToPremise',e.target.value)}/></label>
      <label>이 기록의 상태<select value={draft.status} onChange={e=>update('status',e.target.value)}><option value="reported">등록 · 확인 필요</option><option value="confirmed">사용자가 확인으로 기록</option><option value="corrected">정정 기록</option><option value="retracted">철회 기록</option></select></label><label className="breaking-review"><input type="checkbox" checked={draft.sourceBodyReviewed} onChange={e=>update('sourceBodyReviewed',e.target.checked)}/>내가 원문 본문을 읽었습니다.<small>사용자 확인 표시이며 공식 인과 검증·독립 검증은 아닙니다.</small></label>
      {draft.supersedesId&&<p className="breaking-wide">이어지는 이전 기록: <code>{draft.supersedesId}</code> · 원문 기록은 삭제하지 않습니다.</p>}<div className="breaking-wide breaking-form-actions"><button className="primary" disabled={busy||!onAction}>{busy?'저장 중…':'뉴스 기록 저장'}</button><span>가격 충격이나 상승률을 임의로 입력하지 않습니다.</span></div>
    </form></section>}
    <section className="breaking-chart-panel"><div className="breaking-section-heading"><h3>선택한 전망과 실제 종가</h3><details><summary>다른 보관 판단 확인</summary><label>차트에 표시할 저장 기록<select aria-label="돌발 판단 전망 선택" value={displayedForecast?.id??'operating'} onChange={e=>setForecastId(e.target.value)}><option value="operating">현재 선택한 운영 전망</option>{[...stockForecasts].reverse().map((f:any)=><option key={f.id} value={f.id}>{time(f.issuedAt)} · {labels[f.kind]??f.kind}</option>)}</select></label><p>하나를 선택하면 그 전망만 표시합니다. 기존 기록은 보존됩니다.</p></details></div><div className="breaking-chart-legend"><span className={displayedForecast?'change':'base'}>{displayedForecast?(displayedForecast.kind==='KEEP'?'선택한 유지 기록':'선택한 돌발 연구안'):'현재 선택한 운영 전망'}</span><span className="actual">실제 종가</span></div>{displayedForecast&&forecastEventSuperseded&&<p className="breaking-successor">이 보관 판단선의 뉴스에 정정·후속 기록이 있습니다. 정정 이후에도 유효한 최신 판단이라고 해석하지 마세요.{forecastReplacement&&<button onClick={()=>setForecastId(forecastReplacement.id)}>후속 판단선 보기</button>}</p>}{displayedForecast?.replacesForecastId&&<p className="breaking-source-state">이 별도안이 이어받은 이전 판단선: {activeForecast.replacesForecastId}</p>}<BreakingPriceChart asset={asset} baseline={displayedBaseline} forecast={displayedForecast} input={state.input}/><p>{displayedForecast?`${displayedForecast.effectiveFrom}부터 선택한 연구안 하나를 표시합니다. 발행 전 가격을 새 예측으로 그리지 않습니다. 발행: ${time(displayedForecast.issuedAt)}.`:'현재 선택한 운영 전망 하나와 실제 종가를 표시합니다. 뉴스 등록만으로 가격선을 바꾸지 않습니다.'}</p><small>표시 발행본 {displayedForecast?.id??operatingVersion?.id??'미확보'} · 연구용 비교 · 실전 우위 미검증</small><details><summary>보관된 원본·변경 가격 비교 기록</summary><div className="breaking-chart-table"><table><thead><tr><th>날짜</th><th>기준 전망</th><th>실제 종가</th><th>이후 별도 판단선</th></tr></thead><tbody>{(baselineAsset?.rows??[]).filter((r:any)=>r.date>='2026-09-17'&&r.date<='2026-10-30').map((r:any)=>{const matches=(asset?.prices??[]).filter((p:any)=>p.date===r.date&&observedByNow(p)&&(state.input.calendar?.sessions??[]).includes(p.date)&&p.quality!=='conflict'),a=matches.length===1?matches[0]:null,b=activeForecast?.effectiveFrom&&r.date>=activeForecast.effectiveFrom?activeForecast.rows.find((p:any)=>p.date===r.date):null;const display=(v:any)=>number(v)?Math.round(v).toLocaleString('ko-KR')+'원':'—';return <tr key={r.date}><td>{r.date}</td><td>{display(r.p50)}</td><td>{display(a?.close)}</td><td>{display(b?.p50)}</td></tr>;})}</tbody></table></div></details></section>
    <div className="breaking-reading"><section className="breaking-timeline"><div className="breaking-section-heading"><h3>{asset?.name}의 새 정보</h3><span>확인 시각 최신순</span></div>{events.length?<div role="group" aria-label="등록된 돌발 뉴스">{events.map((e:any)=><button key={e.id} className="breaking-event" aria-pressed={e.id===selected?.id} onClick={()=>{setSelectedId(e.id);setDecision('WATCH');setReason('');setImpactJson('');}}><small>{time(e.knownAt??e.discoveredAt)} · {statusLabels[e.status]??e.status}</small><b>{e.title}</b><span>{e.economicEventId} / {e.phaseId}</span>{e.supersedesId&&<em>이전 기록의 정정·후속</em>}</button>)}</div>:<div className="breaking-empty"><span aria-hidden="true">＋</span><h3>등록된 돌발 뉴스가 없습니다.</h3><p>이 회사의 새 발표나 공시 원문을 등록하면 판단과 변경 기록을 이어갑니다. 뉴스가 없다는 확인을 뜻하지는 않습니다.</p><button onClick={newEvent}>첫 뉴스 등록</button></div>}</section>
    <section className="breaking-detail" aria-label="선택 뉴스와 전제 검토" tabIndex={0}>{selected?<><div className="breaking-evidence-badge">사용자 등록 · 독립 검증 전</div><h3>{selected.title}</h3><p className="breaking-summary">{selected.summary}</p><dl className="breaking-timestamps"><div><dt>공개 시각</dt><dd>{time(selected.publishedAt)}</dd></div><div><dt>수집·등록 시각</dt><dd>{time(selected.discoveredAt)}</dd></div><div><dt>판단에 사용 가능한 시각</dt><dd>{time(selected.knownAt)}</dd></div></dl><p className="breaking-source-state">출처 종류: {{official:'공식으로 입력',press:'언론 보도로 입력',unverified:'미확인'}[selected.sourceType as string]??selected.sourceType} · 원문 본문: {selected.sourceBodyReviewed?'사용자가 읽었다고 표시':'확인 표시 없음'}</p>{safeUrl(selected.sourceUrl)&&<a className="breaking-source" href={selected.sourceUrl} target="_blank" rel="noreferrer">등록된 출처 열기 ↗<small>{selected.sourceUrl}</small></a>}
    <div className="breaking-premise"><h4>기존 전제에서 달라진 점</h4><p>{selected.changeToPremise||'연결된 전제 변경 근거가 아직 입력되지 않았습니다.'}</p><h4>해당 기업의 사업 연결</h4><p>{selected.businessPath||'매출·비용 등 구체적 사업 연결은 미확보입니다.'}</p><small>입력된 설명은 가설입니다. 가격 변동의 원인으로 확정하지 않습니다.</small></div>
    {successor&&<p className="breaking-successor">이 기록 이후 정정·후속 기록이 있습니다. <button onClick={()=>setSelectedId(successor.id)}>후속 기록 보기</button></p>}
    <form className="breaking-decision-form" onSubmit={decide}><h4>어떻게 대응할지 기록</h4><div role="group" aria-label="돌발 뉴스 처리 요청" className="breaking-decision-options">{['KEEP','WATCH','SCENARIO','REVISE'].map(k=><button type="button" key={k} aria-pressed={decision===k} onClick={()=>setDecision(k)}>{labels[k]}</button>)}</div><p>{decision==='REVISE'?'변경 검토 요청입니다. 필요한 수치 근거가 없으면 관찰로 유보됩니다.':decision==='SCENARIO'?'별도 시나리오 검토입니다. 실제 미래 결과나 검증된 가격 충격을 뜻하지 않습니다.':decision==='KEEP'?'기존 전망을 유지한다는 판단을 기록합니다. 뉴스가 무효라는 뜻은 아닙니다.':'가격을 바로 바꾸지 않고 추가 확인이 필요함을 기록합니다.'}</p><label>판단 이유<textarea required maxLength={3000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="유지·관찰·검토가 필요한 근거와 모르는 점"/></label>{decision==='REVISE'&&<details className="breaking-impact-import"><summary>검증 자료 JSON · 선택</summary><p>원문 기록·동일 종목/단계의 과거 사건·조정 가격·사전 기대·중복 검토 자료가 필요합니다. 업로드 자체는 검증 완료가 아니며 엔진이 요건을 다시 검사합니다. 숫자 충격값만으로 변경하지 않습니다. <a href="/downloads/ATLAS_BREAKING_EQUATIONS.md" download>방정식·검토 자료 형식 받기</a></p><label>자료 파일<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024){setNotice('검증 자료 JSON은 1MB 이하로 입력하세요.');return;}try{setImpactJson(await file.text());}catch{setNotice('파일을 읽지 못했습니다.');}e.target.value='';}}/></label><label>검증 자료 JSON<textarea aria-label="돌발 변경 검증 자료 JSON" value={impactJson} maxLength={1048576} onChange={e=>setImpactJson(e.target.value)} placeholder="확보한 검토 원본만 입력하세요. 자료가 없으면 비워 둡니다."/></label></details>}<button className="primary" disabled={!onAction||busy||!reason.trim()||Boolean(successor)}>{busy?'기록 중…':'판단 요청 저장'}</button></form>
    {latest&&<div className="breaking-decision-result"><b>실제 처리: {labels[latest.decision]??latest.decision}</b><small>요청: {labels[latest.requestedDecision]??latest.requestedDecision} · {time(latest.issuedAt)}</small>{(latest.reasons??[]).map((r:any,i:number)=><p key={i}>{readableReason(r)}</p>)}{(latest.reasons??[]).length>0&&<details><summary>상세 검사 코드</summary><pre>{JSON.stringify(latest.reasons,null,2)}</pre></details>}</div>}
    <button className="breaking-amend" onClick={amend}>이 뉴스의 정정·철회 기록 추가</button><details><summary>동일 사건과 보존 기록</summary><p>사건: <code>{selected.economicEventId}</code></p><p>단계: <code>{selected.phaseId}</code></p><p>현재 기록: <code>{selected.id}</code></p>{selected.supersedesId&&<p>이전 기록: <code>{selected.supersedesId}</code></p>}{eventDecisions.map((d:any,i:number)=><article key={d.id??i}><b>{labels[d.decision]??d.decision}</b><p>{time(d.issuedAt)} · 기준 전망 {d.baselineId}</p><p>{d.reason}</p></article>)}</details></>:<div className="breaking-empty"><h3>근거부터 확인합니다.</h3><p>뉴스를 선택하면 대상 기업, 공개 시각, 달라진 전제와 실제 처리 결과를 이곳에서 확인할 수 있습니다.</p></div>}</section></div>
    <section className="breaking-performance"><div className="breaking-section-heading"><h3>변경 뒤 실제 결과는 어땠나요?</h3><span>원본 유지 · 기록된 가격 쌍만 비교</span></div>{pairs.length?<><p>{pairs.length}개 보관 평가 쌍 · {uniqueDates}개 고유 날짜. 서로 다른 변경안의 같은 날짜 기록은 독립 표본이 아닙니다.</p><div className="breaking-performance-rows">{pairs.map((r:any,i:number)=><article key={r.id??i}><time>{r.date}</time><span>출발 전망 오차 <b>{won(r.baselineErrorWon)}</b></span><span>변경안 오차 <b>{won(r.errorWon)}</b></span><span>가격 유지 오차 <b>{won(r.referenceErrorWon)}</b></span><small>실제 − 예측 · {r.kind==='KEEP'?'유지안: 개선 아님':'연구 비교'}</small></article>)}</div></>:<div className="breaking-performance-empty"><b>아직 비교할 실제 결과 0건</b><p>변경안을 기록한 뒤 실제 종가가 확보되어야 비교합니다. 변경안이 좋아졌다고 미리 표시하지 않습니다.</p></div>}</section>
    {premises.length>0&&<details className="breaking-premises-history"><summary>이 종목의 보존 전제 {premises.length}개</summary>{premises.map((p:any,i:number)=><article key={p.id??i}><p>{p.detail??p.statement??p.description??'전제의 상세 필드 확인 필요'}</p><small>{p.status??'판정 미확보'}</small></article>)}</details>}
  </section>;
}
