import React,{useEffect,useMemo,useState,useRef} from 'react';
import {comparisonSeries,rankAt,newsEnergy,rankMovement,raceDates,raceKeyframes,closeRace} from '../lib/equal-start.mjs';
import {WaveReason} from './news-wave';
import './equal-start.css';
const won=(v:any)=>v==null?'자료 없음':Math.round(v).toLocaleString('ko-KR')+'원';
const pct=(v:any)=>v==null?'—':(v>=0?'+':'')+(v*100).toFixed(2)+'%';
const colors=['#38dfcd','#ffcc75','#c8a1ff','#83baff','#ff8e9e'];
export function EqualStartPage({input,version,active,onSessionChange}:any){
 const dates=useMemo(()=>raceDates(input),[input]);
 const series=useMemo(()=>comparisonSeries({input,version}),[input,version]);
 const [index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[selected,setSelected]=useState(input.assets[0].code),[pauseImportant,setPauseImportant]=useState(true),[stop,setStop]=useState<any>(null),[rankingEnd,setRankingEnd]=useState(false);
 useEffect(()=>{onSessionChange?.(playing||!!stop);return()=>onSessionChange?.(false);},[playing,stop,onSessionChange]);
 useEffect(()=>{if(!active){setPlaying(false);setStop(null);}},[active]);
 useEffect(()=>{setPlaying(false);setStop(null);setIndex(i=>Math.min(i,dates.length-1));},[version.id,dates.length]);
 useEffect(()=>{const pause=()=>{if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause);},[]);
 const frames=useMemo(()=>raceKeyframes(series,dates,selected),[series,dates,selected]);
 useEffect(()=>{if(!playing||!active)return;if(index>=dates.length-1){setPlaying(false);return;}const t=setTimeout(()=>{const n=index+1;setIndex(n);const key=frames.find((f:any)=>f.index===n);if(pauseImportant&&key){setPlaying(false);setStop(key);}else if(n===dates.length-1)setPlaying(false);},1000);return()=>clearTimeout(t);},[playing,active,index,dates,frames,pauseImportant]);
 const date=dates[index],ranked=useMemo(()=>rankAt(series,date),[series,date]),final=useMemo(()=>rankAt(series,dates.at(-1)),[series,dates]);
 const shown=rankingEnd?final:ranked,chosen=ranked.find((a:any)=>a.code===selected)??ranked[0],top=ranked.filter((a:any)=>a.rank!=null).slice(0,5).map((a:any)=>a.code);
 const moves=useMemo(()=>new Map(series.map((a:any)=>[a.code,index?rankMovement(series,date,dates[index-1],a.code):null])),[series,date,dates,index]);
 const movement:any=moves.get(chosen.code),near=closeRace(ranked,chosen.code),allNews=useMemo(()=>newsEnergy(chosen.asset,chosen.source,input.origin,input.end),[chosen,input.origin,input.end]);
 const stage=useRef<HTMLDivElement>(null),[chartWidth,setChartWidth]=useState(900);
 useEffect(()=>{if(!stage.current)return;const ob=new ResizeObserver(([e])=>setChartWidth(Math.max(280,e.contentRect.width)));ob.observe(stage.current);return()=>ob.disconnect();},[]);
 const W=chartWidth,H=chartWidth<650?310:400,L=52,R=16,T=35,B=43;
 const domain=useMemo(()=>{const values=series.flatMap((a:any)=>a.rows.filter((r:any)=>dates.includes(r.date)).map((r:any)=>r.value).filter((v:any)=>Number.isFinite(v)));const low=Math.min(10000,...values),high=Math.max(10000,...values),pad=Math.max(100,(high-low)*.08);return{low:low-pad,high:high+pad};},[series,dates]);
 const x=(d:string)=>L+Math.max(0,dates.indexOf(d))*(W-L-R)/Math.max(1,dates.length-1),y=(v:number)=>T+(domain.high-v)*(H-T-B)/(domain.high-domain.low);
 const path=(a:any,future:boolean)=>{let joined=false;return dates.map((d:string,i:number)=>{const r=a.rows.find((r:any)=>r.date===d),join=future&&d===input.actualAsOf,isFuture=d>input.actualAsOf;if(r?.value==null||(!join&&isFuture!==future)){joined=false;return '';}const s=`${joined?'L':'M'}${x(d)},${y(r.value)}`;joined=true;return s;}).join(' ');};
 const seek=(i:number)=>{setPlaying(false);setStop(null);setIndex(Math.max(0,Math.min(dates.length-1,i)));};
 const pick=(code:string)=>{setSelected(code);setPlaying(false);setStop(null);};
 const next=frames.find((f:any)=>f.index>index);
 const newsWindows=chosen.asset.waveModel?.events.filter((e:any)=>e.status==='exploratory')??[];
 const lastActual=dates.filter((d:string)=>d<=input.actualAsOf).at(-1);
 return <section className="equal-page race52" hidden={!active} data-equal-page data-forecast-id={version.id}>
  <header className="equal-heading"><div><small>52종목 · 같은 1만원 출발</small><h2>누가 앞서고, 누가 추월하는가</h2><p>9/17—10/30 · 실제 / 음영 구간 모형 · 52개 선 전체 표시</p></div><div className="equal-finish"><span>{date} {date<=input.actualAsOf?'실제':'모형'} 선두</span><b>{ranked.filter((a:any)=>a.rank===1).length>1?`공동 1위 · ${ranked.filter((a:any)=>a.rank===1).length}종목`:ranked[0]?.name}</b><strong>{won(ranked[0]?.value)}</strong></div></header>
  <div className="race52-grid">
   <div className="race52-stage" ref={stage}>
    <div className="race52-legend"><span>상위 5개 + 선택 종목 강조</span><b data-equal-date>{date}</b><span>전 기간 고정 눈금</span></div>
    <svg style={{height:H}} viewBox={`0 0 ${W} ${H}`} role="group" aria-label="52종목 1만원 환산 전체 그래프" data-race52-chart tabIndex={0} onKeyDown={e=>{const n=e.key==='ArrowRight'?index+1:e.key==='ArrowLeft'?index-1:e.key==='Home'?0:e.key==='End'?dates.length-1:null;if(n!==null){e.preventDefault();seek(n);}}} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();seek(Math.round(((e.clientX-rect.left)*W/rect.width-L)/(W-L-R)*(dates.length-1)));}}>
     {[0,.25,.5,.75,1].map(t=>{const value=domain.low+t*(domain.high-domain.low);return <g key={t}><line className="race52-gridline" x1={L} x2={W-R} y1={y(value)} y2={y(value)}/><text x={L-8} y={y(value)+4} textAnchor="end">{Math.round(value).toLocaleString()}</text></g>;})}
     <line className="equal-base" x1={L} x2={W-R} y1={y(10000)} y2={y(10000)}/><text x={L} y={y(10000)-7}>출발 10,000원</text>
     {lastActual&&<><rect x={x(lastActual)} y={T} width={W-R-x(lastActual)} height={H-T-B} fill="#ffffff03"/><line x1={x(lastActual)} x2={x(lastActual)} y1={T} y2={H-B} stroke="#7890a5" strokeDasharray="3 5"/><text x={x(lastActual)+5} y="19">이후 모형 전망</text></>}
     {newsWindows.map((e:any)=>{const start=dates.indexOf(e.date);if(start<0)return null;const end=dates[Math.min(dates.length-1,start+2)];return <rect key={e.id} data-race-wave={e.id} x={x(e.date)} y={T} width={Math.max(3,x(end)-x(e.date))} height={H-T-B} fill="#f5c777" opacity=".045"><title>{chosen.name} · {e.name} · 3거래일 관측 파장</title></rect>;})}
     {[...series].sort((a:any,b:any)=>Number(top.includes(a.code)||a.code===selected)-Number(top.includes(b.code)||b.code===selected)).map((a:any)=>{const i=top.indexOf(a.code),highlight=i>=0||a.code===selected,color=a.code===selected?'#fff0c5':i>=0?`hsl(${(series.findIndex((s:any)=>s.code===a.code)*137.508)%360} 70% 72%)`:'#8299b1',row=a.rows.find((r:any)=>r.date===date);return <g key={a.code} data-race-series={a.code} opacity={highlight?1:.2}><g role="button" tabIndex={0} aria-label={`${a.name} 그래프 선택`} onClick={e=>{e.stopPropagation();pick(a.code);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick(a.code);}}}><path data-race-actual d={path(a,false)} fill="none" stroke={color} strokeWidth={a.code===selected?3:highlight?2:1}/><path data-race-forecast d={path(a,true)} fill="none" stroke={color} strokeWidth={a.code===selected?3:highlight?2:1} /><title>{a.name} · {won(row?.value)} · 클릭하여 이유 확인</title></g>{row?.value!=null&&<circle data-race-dot={a.code} cx={x(date)} cy={y(row.value)} r={highlight?4:1.5} fill={color}/>}</g>;})}
     <line className="equal-cursor" x1={x(date)} x2={x(date)} y1={T} y2={H-B}/>
     {dates.filter((_:string,i:number)=>i===0||i===dates.length-1||i%5===0).map((d:string)=><text key={d} x={x(d)} y={H-15} textAnchor="middle">{d.slice(5).replace('-','/')}</text>)}
    </svg>
    <div className="equal-player"><button className="primary" data-equal-play onClick={()=>{setRankingEnd(false);setStop(null);if(index===dates.length-1)setIndex(0);setPlaying(v=>!v);}}>{stop?'설명 확인 · 계속':playing?'일시 정지':'▶ 재생'}</button><button aria-label="이전 거래일" disabled={index===0} onClick={()=>seek(index-1)}>‹</button><span>{index+1}/{dates.length}거래일 · 1초</span><button aria-label="다음 거래일" disabled={index===dates.length-1} onClick={()=>seek(index+1)}>›</button><button disabled={!next} onClick={()=>{seek(next.index);setStop(next);}}>핵심 장면</button><input type="range" aria-label="1만원 순위 날짜" min="0" max={dates.length-1} value={index} onChange={e=>seek(Number(e.target.value))}/><label><input type="checkbox" checked={pauseImportant} onChange={e=>setPauseImportant(e.target.checked)}/>중요 장면에서 멈춤</label></div>
    {stop&&<p className="race52-stop" role="status">{stop.date} · {stop.reasons.join(' · ')}. 확인 후 계속할 수 있습니다.</p>}
   </div>
   <aside className="equal-ranking"><div className="race52-rank-head"><h3>{rankingEnd?'10/30 최종 예상 순위':`${date.slice(5)} ${date<=input.actualAsOf?'실제':'예상'} 순위`}</h3><button aria-pressed={rankingEnd} onClick={()=>{setPlaying(false);setRankingEnd(v=>!v);}}>{rankingEnd?'현재 날짜 순위':'10/30 순위'}</button></div><div className="equal-list" aria-label="52종목 순위"><div style={{height:shown.length*54,position:'relative'}}>{shown.map((a:any,i:number)=>{const m:any=moves.get(a.code);return <button key={a.code} data-equal-code={a.code} data-current-rank={a.rank??''} style={{position:'absolute',top:0,transform:`translateY(${i*54}px)`,height:54}} aria-pressed={chosen.code===a.code} onClick={()=>pick(a.code)}><span className="equal-rank">{a.rank??'—'}</span><span className="equal-name"><b>{a.name}</b><small>{!rankingEnd&&m?.rankChange!=null?m.rankChange===0?'순위 유지':`${m.rankChange>0?'↑':'↓'}${Math.abs(m.rankChange)}계단`:'같은 1만원 기준'}</small></span><span className="equal-value"><b>{won(a.value)}</b><small>{pct(a.return)}</small></span></button>;})}</div></div></aside>
  </div>
  <section className="race52-insight" data-race-selected={chosen.code}><div><h3>{chosen.name} · {chosen.rank??'—'}위 <small>{won(chosen.value)}</small></h3><p><b>판단</b> · {date} 환산 수익률 {pct(chosen.return)}{near?.near?` · ${near.near.name}과 접전 (${won(near.near.gap)} 차이)`:''}</p><p><b>근거</b> · {index&&movement?.ownChange!=null?`전 거래일 가격 변화 ${pct(movement.ownChange)}, 순위 ${movement.rankChange>0?'+' :''}${movement.rankChange}계단. 자기 값 변화 몫 ${movement.ownComponent>=0?'+':''}${movement.ownComponent} · 상대 값 변화 몫 ${movement.otherComponent>=0?'+':''}${movement.otherComponent}.`:'모든 종목이 같은 1만원에서 출발합니다.'}</p><p><b>다음 확인</b> · {near?.above?`${near.above.name}까지 ${won(near.above.gap)} 차이. `:'현재 선두입니다. '}{chosen.asset.news.find((n:any)=>n.date>date)?.name??'추가 확정 일정 미확보'}</p><p className="muted">접전은 환산값 차이 0.1% 이내라는 표시 기준입니다. 통계적 순위 안정성·1위 확률은 공동 모형과 민감도 검증 전까지 표시하지 않습니다. 변화 몫은 수치 분해이며 뉴스의 인과효과가 아닙니다.</p></div><div className="race52-explanation"><WaveReason asset={chosen.asset} date={date}/></div></section>
  <details className="equal-method"><summary>선택 종목 뉴스 · 영향 크기순</summary>{allNews.events.map((n:any)=><article key={n.id}><b>{n.date} · {n.title}</b><p>{n.energy==null?'수치 영향 유보':`관측 파장 크기 ${n.energy.toFixed(3)} 로그 %p`} · 자체 표본 {n.sampleCount??'미확보'}</p>{n.sources.map((s:any)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">원문 ↗ </a>)}</article>)}</details>
  <details className="equal-method"><summary>방정식과 해석</summary><p>환산 가치 = 10,000 × 해당 날짜 가격 ÷ 9/17 실제 종가. 실제 자료 이후는 새 전망 중앙값입니다. 실제 구간과 새 전망을 연결한 비교이며 9/17 당시 발행 성적이 아닙니다. 동률 공동 순위·결측 제외. 순위에 뉴스/FOMO 보너스를 다시 더하지 않습니다.</p><p>순위 변화는 자기 값만 바꾸는 경우와 상대 값만 바꾸는 경우, 두 순서의 평균으로 분해합니다. 불확실성 범위가 겹친다는 이유만으로 순위 확률을 계산하지 않습니다.</p><a href="/downloads/ATLAS_RACE52_PLAN.md" download>기획·방정식 받기</a></details>
 </section>;
}
