import React from 'react';
import './factor36.css';
const direction:any={up:'상승',flat:'보합',down:'하락'};
const pct=(x:any,n=2)=>typeof x!=='number'?'미산출':`${x>0?'+':''}${(x*100).toFixed(n)}%`;
export function Factor36Reason({asset,date}:any){
 const m=asset.factorModel,row=asset.rows.find((r:any)=>r.date===date),v=row?.factor36,choice=row?.wave?.daily,used=m.factors.filter((f:any)=>f.status!=='missing'),news=asset.news.filter((n:any)=>n.date===date);
 const contributions=Object.entries(v?.contributions??{}).map(([id,c]:any)=>({id,value:c,name:id==='F11'?'ATLAS52 가격 폭 대용값':m.factors.find((f:any)=>f.id===id)?.name??id,share:v.shares[id]})).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value));
 return <section className="factor36-reason" data-factor36-reason={asset.code} data-reason-date={date}>
  <div className="factor36-eyebrow">{date} · {asset.name}</div>
  <h3>{choice?`${direction[choice.selected]} 선택`:'실제 관측 구간'} <small>{choice?`모형 ${(100*choice.modelProbability).toFixed(1)}%`:''}</small></h3>
  {choice&&<><div className="factor36-probabilities">{['up','flat','down'].map(k=><span key={k} data-selected={choice.selected===k}>{direction[k]}<b>{(choice.probabilities[k]*100).toFixed(1)}%</b></span>)}</div><p>보합 ±0.1% · 2순위와 {(100*choice.runnerUpGap).toFixed(1)}%p 차이<br/><small>모형에서의 비율이며 실제 적중 확률은 미검증입니다. 선은 가격 분포의 중앙값이며 최대 확률 방향을 이어 붙인 경로가 아닙니다.</small></p></>}
  <h4>이 날짜를 계산한 근거</h4>
  {v?<><div className="factor36-drivers">{contributions.slice(0,3).map(c=><div key={c.id}><span>{c.name}</span><b data-sign={c.value>0?'up':c.value<0?'down':'flat'}>{pct(c.value,3)}<small> 로그수익률</small></b><small>{c.share==null?'순기여 0 · 비중 미산출':`절대 기여 비중 ${c.share.toFixed(1)}%`}</small></div>)}</div><p>기본항 {pct(v.intercept,3)} · 조건부 평균 {pct(v.meanLogReturn,3)}.<br/>기여는 모형 계산의 분해이며 실제 원인의 증명은 아닙니다.</p></>:<p>이 날짜는 새 전망의 발행 기준 이전입니다. 미래 계산값을 과거 설명으로 붙이지 않습니다.</p>}
  <p className="factor36-state"><b>변동폭</b> {m.volatility.kind==='garch11'?'GARCH(1,1) · 직전 충격과 변동 지속성 반영':'종목 자체 잔차의 경험적 분포'}<br/><b>공동 움직임</b> 52종목에 같은 과거 잔차 날짜를 적용</p>
  <details className="factor36-news"><summary>뉴스 {news.length}건 · 참고 근거</summary>{news.length?news.map((n:any)=><article key={n.id}><b>{n.name}</b><p>일정 확인과 가격 영향 입증은 별개입니다. 기대 대비 결과·독립 검증 부족으로 추가 충격은 미산출입니다.</p>{n.sources?.slice(0,2).map((s:any)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">원문 확인 ↗</a>)}</article>):<p>이 종목에 연결된 확정 일정이 없는 날입니다. 시장·자체 가격 상태는 별도로 계산합니다.</p>}</details>
  <details data-factor36-details><summary>36개 요인 · 계산 연결 {used.length} / 미연결 {36-used.length}</summary><p>계산 연결은 원자료가 모두 확보되었다는 뜻이 아닙니다. 자기 가격 추세·종가 변동폭과 ATLAS52 가격 폭은 해당 요인의 일부 또는 대용값입니다. 전체 시장·업종, 조정 가격·시가 갭의 확보 상태는 자료·운영 기록에서 확인합니다.</p><div className="factor36-list">{m.factors.map((f:any)=><div key={f.id} data-factor-id={f.id}><div><b>{f.id==='F11'?'ATLAS52 가격 폭 대용값':f.name}</b><small>{f.id} · 조사 P {f.research_priority}</small></div><strong>{f.status==='missing'?'미확보':f.role==='variance'?'변동폭 사용':'연구 계산 사용'}</strong><p>{f.reason}</p>{f.sourceUrl&&<a href={f.sourceUrl} target="_blank" rel="noreferrer">입력 원출처 ↗</a>}</div>)}</div></details>
  <p className="factor36-limits"><b>FOMO {asset.waveModel.fomo.enabled?'연구 입력 반영':'미반영'}</b> · {asset.waveModel.fomo.enabled?'핵심 관측과 학습 입력 연결':'검색·개인 수급 원자료와 결합 학습 미확보'}<br/>학습 종가: NAVER 보관 이력 · 최근 일부 종가 별도 대조; 기업행위·당시 원본 미검증.</p>
  <details><summary>이 종목의 계수·검증 기록</summary><p>{m.selected.id} · 학습 종료 {m.trainedThrough} · 최종 학습 {m.regression.n}행 · 사용 가능 이력 {m.trainCount}행.<br/>계수 선택과 분리한 후향적 평가 {m.validation.days}거래일. 현재 빈티지 가격이므로 당시 실전 재현 인증이 아닙니다.</p><p>분포 오차 CRPS {m.validation.crps.toFixed(5)} / 가격 유지 {m.validation.baselineCRPS.toFixed(5)}<br/>방향 Brier {m.validation.brier.toFixed(5)} / 기준 {m.validation.baselineBrier.toFixed(5)}<br/>모두 낮을수록 좋습니다. 10/30 전체 지평의 우위는 미검증입니다.</p><a href="/downloads/ATLAS_FACTOR36_52_EQUATIONS.json" download>52종목 계수·방정식</a></details>
 </section>;
}
export function Factor36Collection(){
 const [r,setR]=React.useState<any>(null);React.useEffect(()=>{let live=true;fetch('/data/factor36-collection.json').then(x=>x.ok?x.json():null).then(x=>{if(live)setR(x);}).catch(()=>{});return()=>{live=false;};},[]);
 if(!r)return null;const reviewed=r.reviewedCollection;return <div className="factor36-collection" data-factor36-collection>{reviewed&&<p><b>별도 공개 원문 수집</b> · 종가 {reviewed.stocks}/52종목 · {reviewed.rows.toLocaleString()}행 · 최신 요청일 자료 충족 {reviewed.latestCompleteStocks}/52종목<br/>거시 {reviewed.macroSeries}개 시계열 · {reviewed.macroRows.toLocaleString()}행. 종가를 확보한 것과 52종목의 공통 기준일을 갱신하는 것은 별개입니다.</p>}<p><b>실행 환경 수집기</b> · 확인 {new Date(r.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} · 가격 정상 응답 {r.price.successfulSources}/{r.price.sourceCount??52} · 거시 정상 응답 {r.macro.successfulSources}/{r.macro.sourceCount??4}<br/><b>52종목 공통 보관 종가 {reviewed?.asOf??r.priceAsOf}</b> 사용 · 새 승인 요인 {r.newApprovedFactorRecords}건. 수집기 실패와 별도 원문 수집을 구분하며, 미래 입력·학습 빈티지 미확보는 그대로 기록합니다.</p></div>;
}
export function Factor36Audit({version}:any){
 const [report,setReport]=React.useState<any>(null);React.useEffect(()=>{let live=true;fetch('/data/factor36-status.json').then(r=>{if(!r.ok)throw Error('자료 미확보');return r.json();}).then(x=>{if(live&&x.id===version.id)setReport(x);}).catch(()=>{});return()=>{live=false;};},[version.id]);
 if(!report)return <p>이 전망의 비교 보고서를 불러오는 중입니다.</p>;const v=report.validation;return <section className="panel factor36-audit" data-factor36-audit><h2>방법도 시장 성적으로 비교합니다</h2><Factor36Collection/><p>사전 기간의 마지막 {v.days}거래일 · {v.rows.toLocaleString()} 종목/날짜 행. 같은 날의 종목을 독립 시험으로 세지 않습니다.</p><div className="factor36-metrics">{[['분포 오차 · CRPS','crps','baselineCRPS'],['방향 오차 · Brier','brier','baselineBrier'],['폭·담김 점수','interval','baselineInterval']].map(([name,key,base])=><article key={key}><h3>{name}</h3><b>{v[key].toFixed(5)}</b><p>가격 유지 {v[base].toFixed(5)}</p><small>{v[key]<v[base]?'이 보관 자료의 비교에서 개선':'이 보관 자료의 비교에서 개선되지 않음'}</small></article>)}</div><div className="factor36-diagnostics table-scroll"><table><caption>같은 평가 날짜의 방향·가격·범위 비교</caption><thead><tr><th>지표</th><th>모형</th><th>가격 유지</th><th>비교</th></tr></thead><tbody>{[
 ['방향 일치율','directionAccuracy','baselineDirectionAccuracy','higher'],
 ['실제 대비 절대 가격 오차','absolutePriceError','baselineAbsolutePriceError','lower'],
 ['예측 범위 담김','coverage','baselineCoverage','coverage'],
 ['예측 범위 폭 비율','bandWidthPrice','baselineBandWidthPrice','width'],
].map(([name,key,base,kind])=>{const measured=Number.isFinite(v[key]),benchmark=Number.isFinite(v[base]),equal=measured&&benchmark&&Math.abs(v[key]-v[base])<1e-12;let comparison='미산출';if(measured&&benchmark)comparison=kind==='coverage'?'폭과 함께 평가':kind==='width'?(equal?'같은 폭':v[key]<v[base]?'모형 범위가 좁음':'모형 범위가 넓음'):equal?'같음':(kind==='higher'?v[key]>v[base]:v[key]<v[base])?'이 평가에서 개선':'이 평가에서 악화';return <tr key={key} data-factor-metric={key}><th>{name}</th><td>{measured?`${(v[key]*100).toFixed(2)}%`:'미산출'}</td><td>{benchmark?`${(v[base]*100).toFixed(2)}%`:'미산출'}</td><td>{comparison}</td></tr>;})}</tbody></table><p>방향 일치율은 관측 결과이며 미래 적중 확률이 아닙니다. 범위는 담김과 폭을 함께 비교합니다.</p></div><p>현재 조회 가격으로 다시 계산한 후향적 비교입니다. 당시 데이터 빈티지·기업행위 조정 미검증이며 실전 우위의 인증이 아닙니다. 1거래일 평가이며 10/30까지의 전체 경로 성적은 별도입니다.</p><p>52종목 공동 경로 {report.summary.jointPaths.toLocaleString()}개 · 수치 모의실험이며 독립 시장 검증 횟수가 아닙니다.</p><a href="/downloads/ATLAS_FACTOR36_PLAN.md" download>기획·방정식</a> · <a href="/downloads/ATLAS_FACTOR36_RESEARCH.json" download>논문 근거 7편</a></section>;
}
export function Factor36Math({version}:any){const factors=new Map();for(const asset of version?.assets??[])for(const f of asset.factorModel?.factors??[])if(f.status!=='missing')factors.set(f.id,f.id==='F11'?'F11 ATLAS52 가격 폭 대용값':`${f.id} ${f.name}`);return <section className="panel"><h2>시장이 채점하는 36요인 모형</h2><Factor36Collection/><p>확보한 요인만 사용하고, 예정 뉴스는 참고값으로 다룹니다.</p><pre>r = 종목별 조건부 평균 + 시간별 변동폭 × 공동 잔차\n조건부 평균 = 기본항 + Σ(학습 계수 × 표준화 입력)\n분산 = ω + a × 직전 오차² + b × 직전 분산\n가격 = 전일 가격 × exp(r)\n선택 방향 = argmax(상승, 보합, 하락 모형 확률)</pre><p>현재 발행본의 계산 연결: {[...factors.values()].join(' · ')||'발행본 기록 확인 필요'}. 부분 관측과 대용값을 포함할 수 있으며, 요인의 원자료 전체 확보를 뜻하지 않습니다. 52종목별 원자료·계산·검증 상태는 자료·운영 기록에서 확인합니다.</p><p>계수는 종목별로 학습합니다. 뉴스와 수급을 중복해서 더하지 않으며 미래 정보를 학습에 섞지 않습니다. 현재 과거 가격 빈티지와 조정은 미검증이므로 연구 결과입니다.</p><a href="/downloads/ATLAS_FACTOR36_PLAN.md" download>상세 기획</a> · <a href="/downloads/ATLAS_FACTOR36_52_EQUATIONS.json" download>실제 계수</a></section>;}
