import React, {useMemo, useRef, useState} from 'react';
import {verifyStudySeal} from '../lib/sealed-manifest.mjs';

const finite=(v:any)=>typeof v==='number'&&Number.isFinite(v);
const won=(v:any)=>finite(v)?`${Math.round(v).toLocaleString('ko-KR')}원`:'미산정';
const percent=(v:any)=>finite(v)?`${v>0?'+':''}${(100*v).toFixed(2)}%`:'미산정';
const pp=(v:any)=>finite(v)?`${v.toFixed(2)}%p`:'미산정';
const rate=(v:any)=>finite(v)?`${(100*v).toFixed(1)}%`:'미산정';
const stamp=(v:any)=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false})+' KST':'미확보';
const shortDate=(s:string)=>s?.slice(5).replace('-','/');
const direction=(v:any)=>({UP:'상승',DOWN:'하락',FLAT:'보합',up:'상승',down:'하락',flat:'보합','1':'상승','-1':'하락','0':'보합'}[String(v)]??'미산정');
const judgement=(v:any)=>v===true?'일치':v===false?'불일치':'미산정';
const labels:Record<string,string>={UNESTIMABLE:'뉴스 반응을 산정할 근거 부족',MISSING_ACTUAL:'실제 종가 미확보',MISSING_PRICE_VINTAGE:'당시 가격 원본 미확보',PRICE_BASIS_UNVERIFIED:'기업행위·가격 기준 확인 부족',SEAL_INVALID:'봉인 지문 불일치',RETROSPECTIVE:'사후 재구성',EXTERNAL_TIMESTAMP_PENDING:'외부 시각 인증 대기',UNVERIFIED:'미검증',UNAVAILABLE:'미확보'};
Object.assign(labels,{VERIFIED:'가격 기준 확인',FORMAL:'자료 자격 통과',OBSERVED_ONLY:'관측 진단만 가능',B_UNESTIMABLE:'B 뉴스 중심 미산정',INVALID_SEAL:'봉인 지문 불일치',ACTUAL_UNAVAILABLE:'실제 종가 미확보',ACTUAL_PRICE_MISSING:'해당 날짜 종가 미확보',ACTUAL_VINTAGE_UNVERIFIED:'당시 가격 빈티지 미검증',ACTUAL_ADJUSTMENT_UNVERIFIED:'기업행위 조정 미확인',ACTUAL_BASIS_UNKNOWN:'실제 가격 기준 식별값 미확보',ACTUAL_OBSERVATION_TIME_UNKNOWN:'종가 관측 시각 미확보',ACTUAL_PRICE_CONFLICT:'같은 날짜 종가 상충',ACTUAL_PRICE_INVALID:'종가 자료 검증 실패',ORIGIN_PRICE_BASIS_UNVERIFIED:'9/17 가격 빈티지·조정 미검증',PRICE_BASIS_MISMATCH:'출발값과 실제값의 가격 기준 일치 미확인',SEALED_ORIGIN_PRICE_CHANGED_OR_MISSING:'봉인 출발값이 현재 가격 자료와 다름',ORIGIN_PRICE_MISSING:'9/17 기준 종가 미확보',SEALED_PATH_MISSING:'해당 날짜 봉인 경로 없음',BAND_CALIBRATION_UNVERIFIED:'띠의 실제 포함률 교정 미검증',SYMMETRIC_COMMON_BAND_INVALID:'공통 대칭 띠 자격 불충족',EXPLORATORY_UNCALIBRATED_WIDTH:'과거 잔여변동으로 만든 탐색용 띠',OVERLAPPING_WINDOWS_NOT_INDEPENDENT:'서로 겹치는 과거 기간은 독립 표본 아님',INSUFFICIENT_CONTIGUOUS_HISTORY:'연속 과거 가격 자료 부족',PRICE_VINTAGE_OR_CORPORATE_ACTION_UNVERIFIED:'당시 가격 원본·기업행위 조정 미검증',NO_ESTIMABLE_NEWS_CENTER:'추가 뉴스 반응을 산정할 근거 없음',ONE_OR_MORE_NEWS_EFFECTS_UNESTIMABLE:'하나 이상 뉴스의 추가 반응 미산정',NEWS_ADDITIONAL_RESPONSE_UNAVAILABLE:'이 회사의 추가 뉴스 반응 표본 미확보',SCHEDULE_NOT_PRICE_CATALYST:'일정 확인이며 가격 영향 입증 아님',CONTEXT_ONLY:'설명용 일정',ORIGINAL_EVENT_VINTAGE_UNVERIFIED:'당시 뉴스 원본 미검증',PRIMARY_BODY_AT_CUTOFF_NOT_VERIFIED:'기준 시각의 공식 본문 미검증',PRIMARY_EVENT_BODY_NOT_VERIFIED:'사건의 공식 원문 본문 미검증',PUBLICATION_INSTANT_NOT_VERIFIED_AT_CUTOFF:'기준 시각 이전 공개를 확인하지 못함',ALREADY_PRICED_IN_COMPONENT_UNRESOLVED:'이미 가격에 반영된 부분 미확인',FUTURE_RESULT_DISTRIBUTION_UNRESOLVED:'발표 결과별 사전 분포 미확보',MATERIAL_SAME_DAY_OVERLAP_UNRESOLVED:'같은 날짜 사건의 결합 근거 부족',MULTI_EVENT_ADDITIVITY_UNVERIFIED:'여러 사건 효과의 합산 근거 부족',INSUFFICIENT_INDEPENDENT_EVENT_DATES:'독립 사건 날짜 표본 부족',KOSPI_SERIES_UNAVAILABLE:'코스피 종가 자료 미확보',FROZEN_MARKET_FORECAST_MISSING:'사전 봉인 코스피 전망 미확보',ESTIMATED:'수치 산정 · 우위 인증 아님'});
function reason(v:any):string {if(typeof v==='string')return labels[v]??v;return v?.detail??v?.reason??v?.message??labels[v?.code]??v?.code??JSON.stringify(v);}
function datesBetween(start:string,end:string){const out:string[]=[];for(let t=Date.parse(start+'T00:00:00Z');t<=Date.parse(end+'T00:00:00Z');t+=86400000)out.push(new Date(t).toISOString().slice(0,10));return out;}
function downloadJson(value:any,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function latestReports(reports:any[]){const byDate=new Map<string,any>();for(const r of reports){const old=byDate.get(r.date);if(!old||(r.revision??0)>(old.revision??0)||((r.revision??0)===(old.revision??0)&&String(r.createdAt)>String(old.createdAt)))byDate.set(r.date,r);}return [...byDate.values()].sort((a,b)=>a.date.localeCompare(b.date));}
function scoreOf(row:any,line:'a'|'b',mode:string){return mode==='formal'?row?.[line]:row?.observed?.[line];}
function metricSummary(report:any,mode:string){return report?.summary?.[mode]??{};}
function safeSource(value:any){try{const u=new URL(typeof value==='string'?value:value?.url);return /^https?:$/.test(u.protocol)?u.href:null;}catch{return null;}}

function StudyChart({asset,study,reports,date,onDate,sealValid}:any){
 const titleId=React.useId(),descriptionId=React.useId();
 const [showRange,setShowRange]=useState(false);
 const days=datesBetween(study.origin,study.end),rows=asset.rows??[],W=720,H=300,pad={l:62,r:18,t:24,b:34};
 const actual=[{date:study.origin,value:finite(asset.originPrice)?0:null},...reports.map((r:any)=>({date:r.date,value:r.rows?.find((s:any)=>s.code===asset.code)?.actual?.return??null}))];
 const newsValue=(r:any)=>sealValid&&r.b?.status==='ESTIMATED'&&finite(r.b?.centerReturn)?r.b.centerReturn:null;
 const hasNewsForecast=rows.some((r:any)=>finite(newsValue(r)));
 const validBand=(r:any)=>finite(newsValue(r))&&finite(r.b?.lowerReturn)&&finite(r.b?.upperReturn)&&r.b.lowerReturn>=-1&&r.b.lowerReturn<=r.b.centerReturn&&r.b.centerReturn<=r.b.upperReturn;
 const hasRange=rows.some(validBand);
 const values=[0,...rows.map(newsValue),...(showRange?rows.filter(validBand).flatMap((r:any)=>[r.b.lowerReturn,r.b.upperReturn]):[]),...actual.map((r:any)=>r.value)].filter(finite);
 const low=Math.min(...values),high=Math.max(...values),margin=Math.max(.015,(high-low)*.09),min=low-margin,max=high+margin;
 const x=(d:string)=>pad.l+(Date.parse(d+'T00:00:00Z')-Date.parse(study.origin+'T00:00:00Z'))/(Date.parse(study.end+'T00:00:00Z')-Date.parse(study.origin+'T00:00:00Z'))*(W-pad.l-pad.r);
 const y=(v:number)=>H-pad.b-(v-min)/(max-min)*(H-pad.t-pad.b);
 const path=(items:any[],value:(r:any)=>any)=>{let previous=false;return items.map(r=>{const v=value(r);if(!finite(v)){previous=false;return '';}const command=previous?'L':'M';previous=true;return `${command}${x(r.date).toFixed(2)},${y(v).toFixed(2)}`;}).filter(Boolean).join(' ');};
 const rangePaths=()=>{const groups:any[][]=[];let group:any[]=[];for(const r of rows){if(validBand(r))group.push(r);else if(group.length){groups.push(group);group=[];}}if(group.length)groups.push(group);return groups.map(g=>path(g,r=>r.b.upperReturn)+' '+[...g].reverse().map(r=>`L${x(r.date).toFixed(2)},${y(r.b.lowerReturn).toFixed(2)}`).join(' ')+' Z');};
 const selectFromPointer=(e:React.MouseEvent<SVGSVGElement>)=>{const box=e.currentTarget.getBoundingClientRect();if(!box.width)return;const position=((e.clientX-box.left)/box.width*W-pad.l)/(W-pad.l-pad.r);onDate(days[Math.max(0,Math.min(days.length-1,Math.round(position*(days.length-1))))]);};
 return <div className="sealed-chart-wrap"><svg className="sealed-chart" viewBox={`0 0 ${W} ${H}`} role="img" aria-labelledby={`${titleId} ${descriptionId}`} onClick={selectFromPointer} data-sealed-full-period={`${study.origin}/${study.end}`} data-sealed-forecast-mode="single-news-center">
  <title id={titleId}>{asset.name} · 보관 연구예측과 실제 종가</title><desc id={descriptionId}>9월 17일부터 10월 30일까지 전체 경로. 연구예측 점선 하나와 실제 종가 실선만 표시합니다. 뉴스 근거가 없으면 예측선을 그리지 않습니다. 기준가격은 숫자로만 확인합니다.</desc>
  {[0,1,2,3,4].map(n=>{const v=min+(max-min)*n/4;return <g key={n}><line x1={pad.l} x2={W-pad.r} y1={y(v)} y2={y(v)} className="sealed-grid"/><text x={pad.l-9} y={y(v)+4} textAnchor="end">{percent(v)}</text></g>;})}
  {hasNewsForecast&&showRange&&rangePaths().map((d,i)=><path key={i} className="sealed-band-b" d={d} data-sealed-forecast-range/>)}
  {hasNewsForecast&&<path className="sealed-line-b" d={path(rows,newsValue)} data-sealed-b-path data-sealed-forecast-path/>}
  <path className="sealed-line-actual" d={path(actual,r=>r.value)} data-sealed-actual-path/>
  {actual.filter((r:any)=>finite(r.value)).map((r:any,i:number)=><circle key={r.date+'-'+i} cx={x(r.date)} cy={y(r.value)} r="2.5" className="sealed-actual-dot"/>)}
  <line className="sealed-cursor" x1={x(date)} x2={x(date)} y1={pad.t} y2={H-pad.b}/>
  {[study.origin,'2026-10-01','2026-10-15',study.end].filter((d:string)=>d>=study.origin&&d<=study.end).map((d:string)=><text key={d} x={x(d)} y={H-8} textAnchor={d===study.origin?'start':d===study.end?'end':'middle'}>{shortDate(d)}</text>)}
 </svg><div className="sealed-legend">{hasNewsForecast&&<span className="line-b">보관 연구예측</span>}<span className="line-actual">실제 종가</span><small>9/17 종가 대비</small>{hasNewsForecast&&hasRange&&<button className="sealed-range-toggle" aria-pressed={showRange} onClick={()=>setShowRange(!showRange)}>예측 범위 {showRange?'닫기':'보기'}</button>}</div>{showRange&&hasNewsForecast&&hasRange&&<p className="sealed-range-note">보관한 연구예측의 범위입니다. 실제 포함률이 검증됐다는 뜻은 아닙니다.</p>}{!hasNewsForecast&&<p className="sealed-forecast-unavailable" data-sealed-forecast-unavailable>{sealValid?'연구예측 미산정 · 이 종목의 뉴스 반응 근거가 부족합니다.':'봉인 검증 실패 · 연구예측 표시를 보류합니다.'}</p>}</div>;
}

export function SealedStudyPanel({state}:any){
 const branch=state.sealedStudy??{studies:[],reports:[],proofs:[],errors:[]};
 const [studyId,setStudyId]=useState(''),[code,setCode]=useState(''),[date,setDate]=useState(''),[reportId,setReportId]=useState(''),[mode,setMode]=useState('formal'),[filter,setFilter]=useState('all'),[message,setMessage]=useState('');
 const tableRef=useRef<HTMLDivElement|null>(null),chartRef=useRef<HTMLDivElement|null>(null);
 const study=branch.studies?.find((s:any)=>s.id===studyId)??branch.studies?.at(-1);
 const sealCheck=useMemo(()=>study?verifyStudySeal(study):null,[study]);
 const allReports=useMemo(()=>branch.reports?.filter((r:any)=>r.studyId===study?.id)??[],[branch.reports,study?.id]);
 const reports=useMemo(()=>latestReports(allReports),[allReports]);
 const asset=study?.assets?.find((a:any)=>a.code===code)??study?.assets?.[0];
 const selectedDate=date&&date>=study?.origin&&date<=study?.end?date:(reports.at(-1)?.date??study?.origin);
 const report=allReports.find((r:any)=>r.id===reportId&&r.date===selectedDate)??reports.find((r:any)=>r.date===selectedDate),selectedRaw=report?.rows?.find((r:any)=>r.code===asset?.code),selectedRow=sealCheck?.valid?selectedRaw:{...selectedRaw,a:null,b:null,observed:{a:null,b:null}};
 const pathRow=asset?.rows?.find((r:any)=>r.date===selectedDate),days=study?datesBetween(study.origin,study.end):[];
 const formal=sealCheck?.valid?metricSummary(report,mode):{},co=report?.summary?.coMovement;
 const magnitudeKnown=study?.policy?.scoring?.magnitudeToleranceReturn!=null;
 const rows=(study?.assets??[]).map((a:any)=>report?.rows?.find((r:any)=>r.code===a.code)??{code:a.code,name:a.name,status:'MISSING_ACTUAL',blockers:['이 날짜의 평가 보고서 없음'],a:null,b:null,observed:{a:null,b:null},actual:null}).map((r:any)=>sealCheck?.valid?r:{...r,a:null,b:null,observed:{a:null,b:null},blockers:[...(r.blockers??[]),'SEAL_INVALID']});
 const visible=rows.filter((r:any)=>{const b=scoreOf(r,'b',mode);return filter==='all'||(filter==='hit'&&b?.direction?.matched===true)||(filter==='miss'&&b?.direction?.matched===false)||(filter==='missing'&&!b)||(filter==='both'&&b?.category==='BOTH')||(filter==='directionOnly'&&b?.category==='DIRECTION_ONLY')||(filter==='magnitudeOnly'&&b?.category==='MAGNITUDE_ONLY')||(filter==='neither'&&b?.category==='NEITHER');});
 const selectDate=(value:string)=>{setDate(value);setReportId('');};
 const chooseStock=(value:string,focus=false)=>{setCode(value);if(focus)requestAnimationFrame(()=>{chartRef.current?.focus();chartRef.current?.scrollIntoView?.({block:'nearest',behavior:'smooth'});});};
 const chooseFilter=(value:string)=>{setFilter(value);requestAnimationFrame(()=>tableRef.current?.focus());};
 const exportFile=(value:any,name:string)=>{try{downloadJson(value,name);setMessage('파일을 만들었습니다. 브라우저 다운로드 목록에서 확인하세요.');}catch{setMessage('이 브라우저에서 파일을 만들지 못했습니다. 다운로드 권한을 확인하세요.');}};
 if(!study||!asset)return <section className="sealed-panel sealed-empty" data-sealed-study><span className="section-kicker">봉인 시험</span><h2>아직 봉인한 시험이 없습니다</h2><p>A/B 경로와 정보 기준, 실제 생성 시각을 함께 기록한 뒤 표시합니다. 기존 운영 전망은 별도로 보존됩니다.</p>{branch.errors?.length>0&&<details><summary>생성·갱신 기록</summary>{branch.errors.map((e:any,i:number)=><p key={i}>{reason(e)}</p>)}</details>}</section>;
 const seal=study.seal??{},digest=seal.digest??'',proofs=(branch.proofs??[]).filter((p:any)=>p?.studyId===study.id),hasProofRecord=proofs.some((p:any)=>p.studyDigest===digest&&p.status==='VERIFIED_AGAINST_PROVIDED_ROOT'&&p.fixtureOnly===false);
 const counts={a:study.assets.filter((a:any)=>a.rows?.some((r:any)=>finite(r.a?.price))).length,b:study.assets.filter((a:any)=>a.rows?.some((r:any)=>finite(r.b?.price))).length};
 const prospectiveDates=new Set(reports.filter((r:any)=>r.summary?.prospective===true&&r.summary?.formalPaired>0).map((r:any)=>r.date)).size;
 const sealValid=sealCheck?.valid;
 return <section className="sealed-panel" data-sealed-study>
  <header className="sealed-heading"><div><span className="section-kicker">보관 자료 · 이전 비교 시험</span><h2>이전 연구예측 기록</h2><p>그래프에는 보관 연구예측 하나와 실제 종가를 표시합니다. 기준가 비교와 당시 채점·봉인 자료는 아래 기록에 남아 있습니다.</p></div><label>봉인 버전<select aria-label="봉인 버전" value={study.id} onChange={e=>{setStudyId(e.target.value);setDate('');setReportId('');setCode('');setFilter('all');}}>{branch.studies.map((s:any)=><option key={s.id} value={s.id}>{s.origin} 기준 · {s.id.slice(-8)}</option>)}</select></label></header>
  <div className="sealed-provenance"><div><small>정보 기준 시각</small><b>{stamp(study.informationCutoff)}</b></div><div><small>실제 생성 시각</small><b>{stamp(study.createdAt)}</b><span>{study.retrospective?'9/17 사후 재구성 · 당시 발행본 아님':'생성 시각에 기록'}</span></div><div data-sealed-proof-display-only><small>외부 시각 도장</small><b>{hasProofRecord?'외부 인증 검증 기록 있음':'외부 시각 인증 미확보'}</b><span>{hasProofRecord?'저장 기록 표시 · 이 화면에서 토큰 재검증하지 않음':'9/17 발행을 소급 인증하지 않음'}</span></div></div>
  <details className="sealed-evidence"><summary><b>봉인 증거 보기</b><span>{digest?`${digest.slice(0,18)}…`:'지문 미확보'} · {sealValid===false?'불일치':sealValid===true?'현재 내용 지문 일치':'검사 불가'}</span></summary><dl><dt>내용 지문 SHA256</dt><dd><code data-sealed-digest>{digest||'미확보'}</code></dd><dt>시험 식별값</dt><dd>{study.id}</dd><dt>레코드</dt><dd>{study.recordCount??study.assets.length*2}개 · A 수치 {counts.a}종목 · B 수치 {counts.b}종목 · B 미산정 {study.assets.length-counts.b}종목</dd></dl><p>지문은 내용 변경을 검사합니다. 자체 생성 시각은 외부 인증이 아니며, 토큰도 자료의 진실성·예측 우위를 인증하지 않습니다.</p><div className="sealed-actions"><button disabled={!digest} onClick={async()=>{try{await navigator.clipboard.writeText(digest);setMessage('내용 지문을 복사했습니다.');}catch{setMessage('복사 권한이 없습니다. 펼쳐진 지문을 직접 선택해 복사하세요.');}}}>지문 복사</button><button onClick={()=>exportFile({study,proofs},`ATLAS_sealed_${study.id}.json`)}>봉인 묶음 받기</button></div><details><summary>봉인한 계산·채점 정책</summary><pre>{JSON.stringify(study.policy,null,2)}</pre></details>{proofs.length>0&&<details><summary>외부 인증 기록 {proofs.length}개</summary><pre>{JSON.stringify(proofs,null,2)}</pre></details>}</details>
  <div className="sealed-goal"><b>전향 평가 {prospectiveDates}거래일 / 장기 관측 목표 250일</b><span>10/30 1차 기록 마감 · 예측 우위 미입증</span><small>전향 날짜는 로컬 생성 시각 기준이며 외부 시각 증명과 다릅니다. 보고서 {reports.length}개 고유 날짜 · 같은 날 52종목과 인접 날짜는 독립 시험이 아닙니다.</small></div>
  {sealValid===false&&<p role="alert" className="sealed-warning">봉인 내용이 지문과 일치하지 않습니다. 정식 채점을 유보하며 원본 확인이 필요합니다.</p>}
  <div className="sealed-report-controls"><label>날짜별 보고서<select aria-label="날짜별 보고서" value={selectedDate} onChange={e=>selectDate(e.target.value)}>{days.map((d:string)=><option key={d} value={d}>{d}{reports.some((r:any)=>r.date===d)?' · 기록 있음':study.sessions?.includes(d)?' · 평가 대기':' · 휴장 참고'}</option>)}</select></label><div className="sealed-mode" role="group" aria-label="성적 자료 구분"><button aria-pressed={mode==='formal'} onClick={()=>setMode('formal')}>정식 평가</button><button aria-pressed={mode==='observed'} onClick={()=>setMode('observed')}>관측 진단</button></div><button disabled={!report} onClick={()=>exportFile(report,`ATLAS_daily_${selectedDate}_${report?.id}.json`)}>이 날짜 보고서 받기</button></div>
  <p className="sealed-mode-note" role="status">{report&&<b>보고서 수정 {report.revision??0} · </b>}{mode==='formal'?'정식 평가: 가격 기준·빈티지·봉인 자격을 통과한 값만 채점합니다.':'관측 진단: 보관 가격으로 계산한 참고값입니다. 미검증 가격·재구성 구간을 실전 적중 성적으로 세지 않습니다.'} {report?`실제 확보 ${report.summary?.actualAvailable??0}/${study.assets.length}종목 · A/B 정식 비교 ${report.summary?.formalPaired??0}종목`:'이 날짜의 보고서가 없습니다. 미래 가격이나 휴장일 성적을 만들지 않습니다.'}</p>
  <div className="sealed-metrics"><button onClick={()=>chooseFilter('hit')}><small>연구예측 방향 일치</small><strong>{rate(formal.b?.directionRate)}</strong><span>{formal.b?.directionCorrect??0} / {formal.b?.count??0}종목 · 목록 보기</span></button><button onClick={()=>chooseFilter('all')}><small>연구예측 절대 오차</small><strong>{pp(formal.b?.meanAbsoluteErrorPP)}</strong><span>A {pp(formal.a?.meanAbsoluteErrorPP)} · 작을수록 좋음</span></button><button onClick={()=>chooseFilter('all')}><small>보관 구간 포함 · 폭 점수</small><strong>{rate(formal.b?.coverage)}</strong><span>점수 {pp(formal.b?.meanIntervalScorePP)} · 작을수록 좋음</span></button><button onClick={()=>chooseFilter('missing')}><small>연구예측 미산정 목록</small><strong>{rows.filter((r:any)=>!scoreOf(r,'b',mode)).length}종목</strong><span>{study.policy?.scoring?.magnitudeToleranceReturn==null?'크기 적중 허용 오차 미확정':'크기 기준 '+percent(study.policy.scoring.magnitudeToleranceReturn)+' 고정'}</span></button></div>
  <div className="sealed-comparison-note"><span>A 대비 중심 개선 <b>{pp(formal.centerImprovementPP)}</b></span><span>같은 날 다수 방향 <b>{rate(co?.majorityShare)}</b> ({co?.available??0}종목)</span><span>코스피 대비 예측 적중률 <b>미산정</b></span><span>B 크기 적중 <b>{rate(formal.b?.magnitudeRate)}</b> ({formal.b?.magnitudeCorrect??0}/{formal.b?.magnitudeCount??0}종목)</span><small>양수 개선량은 B의 오차가 작다는 뜻입니다. 다수 방향 비율은 상관계수가 아닙니다.</small></div>
  <details className="sealed-stock-picker" open><summary>종목을 눌러 확인 · {study.assets.length}종목</summary><div role="group" aria-label="봉인 시험 종목 선택">{study.assets.map((a:any)=><button key={a.code} data-sealed-code={a.code} aria-pressed={asset.code===a.code} onClick={()=>chooseStock(a.code)}>{a.name}<small>{a.code}</small></button>)}</div></details>
  <div className="sealed-focus" ref={chartRef} tabIndex={-1} aria-label={`${asset.name} 봉인 비교 상세`}>
   <div className="sealed-plot"><div className="sealed-stock-title"><div><small>{asset.sector} · {asset.code}</small><h3>{asset.name}</h3></div><div className="sealed-reference-price"><small>9/17 기준가 참고</small><span>{won(asset.originPrice)}</span></div></div><StudyChart asset={asset} study={study} reports={reports.map((r:any)=>r.date===selectedDate&&report?report:r)} date={selectedDate} onDate={selectDate} sealValid={sealValid}/><p className="sealed-baseline-note">9/17 기준가(A)는 비교용 숫자입니다. 예측선으로 표시하지 않습니다.</p><div className="sealed-date-strip" role="group" aria-label="종목 날짜 선택">{days.map((d:string)=><button key={d} aria-pressed={selectedDate===d} onClick={()=>selectDate(d)} data-sealed-date={d}>{shortDate(d)}</button>)}</div></div>
   <aside className="sealed-day-detail" aria-label="선택 날짜의 비교와 근거" tabIndex={0}><small>선택 날짜</small><h3>{selectedDate}</h3><div className="sealed-day-prices"><div><span>보관 연구예측</span><b>{won(sealValid?pathRow?.b?.price:null)}</b></div><div><span>실제 종가</span><b>{won(selectedRow?.actual?.price)}</b></div></div>{!finite(pathRow?.b?.price)&&<p className="sealed-warning">연구예측은 미산정입니다. 기준가격을 대신 예측선으로 표시하지 않습니다.</p>}{!study.sessions?.includes(selectedDate)&&<p>휴장일입니다. 새로운 종가·평가일로 세지 않습니다.</p>}<p>가격 기준: {reason(asset.priceBasisStatus??'UNVERIFIED')}</p><dl className="sealed-day-scores">{(['b'] as const).map(line=>{const s=scoreOf(selectedRow,line,mode);return <React.Fragment key={line}><dt>예측 방향 / 크기</dt><dd>{judgement(s?.direction?.matched)} · 오차 {pp(s?.absoluteErrorPP)}</dd><dt>예측 하루 방향</dt><dd>{judgement(s?.dailyDirection?.matched)} · 전 거래일 대비</dd><dt>보관 구간 / 폭 점수</dt><dd>{s?.interval?.inside===true?'포함':s?.interval?.inside===false?'범위 밖':'미산정'} · {pp(s?.interval?.scorePP)}</dd></React.Fragment>})}</dl><details open><summary>이 종목의 사용·유보 근거</summary>{[...(asset.reasons??[]),...(pathRow?.reasons??[]),...(selectedRow?.blockers??[]),...(selectedRow?.intervalBlockers??[])].map((r:any,i:number)=><p key={i}>{reason(r)}</p>)}{!(asset.newsEvidence?.length)&&<p>이 시험에서 사용할 수 있는 종목별 뉴스 반응 근거가 없습니다.</p>}{asset.newsEvidence?.map((e:any,i:number)=><article key={e.id??i}><b>{e.name??e.title??e.eventId??'사건 근거'}</b><p>{reason(e.status??e.reason??'검토 기록')}</p>{e.reasons?.map((r:any,j:number)=><p key={j}>{reason(r)}</p>)}<small>공개 {stamp(e.publishedAt??e.knownAt)}</small>{(e.sources??[e.source??e.sourceUrl]).map((source:any,j:number)=>safeSource(source)&&<a key={j} href={safeSource(source)!} target="_blank" rel="noreferrer">근거 원문 {j+1} ↗</a>)}</article>)}</details></aside>
  </div>
  <div className="sealed-list-heading"><div><h3>52종목 · {selectedDate}</h3><p>{mode==='formal'?'정식 평가':'관측 진단'} · B 방향별 목록 · 같은 종목과 날짜로 A/B 비교</p></div><div className="sealed-filter" role="group" aria-label="B 방향 판정 목록">{[['all','전체'],['hit','방향 일치'],['miss','방향 불일치'],['missing','미산정'],...(magnitudeKnown?[['both','방향·크기 일치'],['directionOnly','방향만'],['magnitudeOnly','크기만'],['neither','둘 다 불일치']]:[])].map(([v,t])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{t}</button>)}</div></div>
  <div className="sealed-table-scroll" ref={tableRef} tabIndex={0} role="region" aria-label="52종목 봉인 비교 평가표"><table className="sealed-table"><caption>{visible.length}종목 표시 · 오차와 폭 점수 단위는 %포인트</caption><thead><tr><th scope="col">종목</th><th scope="col">실제 종가</th><th scope="col">A 방향 / 오차</th><th scope="col">B 방향 / 오차</th><th scope="col">A 담김 / 폭 점수</th><th scope="col">B 담김 / 폭 점수</th><th scope="col">실제 코스피 대비</th><th scope="col">상태·미산정 이유</th></tr></thead><tbody>{visible.map((r:any)=>{const a=scoreOf(r,'a',mode),b=scoreOf(r,'b',mode);return <tr key={r.code} data-sealed-row={r.code}><th scope="row"><button onClick={()=>chooseStock(r.code,true)}>{r.name}</button><small>{r.code}</small></th><td>{won(r.actual?.price)}<small>{percent(r.actual?.return)}</small></td>{[a,b].map((s:any,i:number)=><td key={'score'+i}>{judgement(s?.direction?.matched)}<small>{s?`${direction(s.direction?.predicted)} → ${direction(s.direction?.actual)}`:'평가 없음'}</small><small>하루 방향 {judgement(s?.dailyDirection?.matched)}</small><b>{pp(s?.absoluteErrorPP)}</b><small>크기 {judgement(s?.magnitudeHit)}</small></td>)}{[a,b].map((s:any,i:number)=><td key={'band'+i}>{s?.interval?.inside===true?'포함':s?.interval?.inside===false?'범위 밖':'미산정'}<small>{pp(s?.interval?.scorePP)}</small></td>)}<td>{percent(r.benchmark?.actualExcessReturn??r.benchmark?.excessReturn)}<small>동일 출발일 대비</small>{r.benchmark?.reasons?.map((v:any,j:number)=><small key={j}>{reason(v)}</small>)}</td><td><span>{reason(r.status)}</span>{[...(r.blockers??[]),...(r.intervalBlockers??[])].length>0&&<details><summary>이유 {[...(r.blockers??[]),...(r.intervalBlockers??[])].length}개</summary>{[...(r.blockers??[]),...(r.intervalBlockers??[])].map((v:any,i:number)=><p key={i}>{reason(v)}</p>)}</details>}</td></tr>})}</tbody></table>{!visible.length&&<p className="sealed-empty">이 조건에 해당하는 종목이 없습니다.</p>}</div>
  <details className="sealed-report-history"><summary>날짜별 보고서·수정 기록 {allReports.length}건</summary><p>수정 전 보고서를 보존합니다. 기본은 날짜별 최신 기록입니다. 과거 수정 번호를 누르면 선택 날짜의 당시 보고서와 실제값을 확인합니다.</p>{[...allReports].reverse().map((r:any)=><div key={r.id}><button onClick={()=>{setDate(r.date);setReportId(r.id);}}>{r.date} · 수정 {r.revision??0}</button><span>{stamp(r.createdAt)} · 실제 {r.summary?.actualAvailable??0}종목</span><button onClick={()=>exportFile(r,`ATLAS_daily_${r.date}_${r.id}.json`)}>기록 받기</button></div>)}</details>
  <p className="sealed-download-status" role="status" aria-live="polite">{message}</p>
 </section>;
}
